package.json

reverting this until https://github.com/hashicorp/yamux/issues/30 is fixed

revert yamux back to my patch pending hashicorp/yamux#30

---

p2p/net/swarm/swarm.go

Expose this here so we can use it in the swarm commands to clear the dial backoff

expose backoff manager in swarm

---

p2p/net/swarm/limiter.go
p2p/net/swarm/swarm_addr.go
p2p/net/swarm/swarm_net_test.go

removes some dead code and adds more tests, hits 82.8% code coverage

p2p/net/swarm: improve code coverage

---

p2p/net/swarm/swarm_dial.go

swarm: externalize secio handshake errors

---

p2p/net/mock/mock_conn.go
p2p/test/reconnects/reconnect_test.go
package.json

update packages to add support for getStreams

---

p2p/host/basic/basic_host.go
p2p/protocol/identify/id.go

We had random streams building up with no owners.  This should address the issue.

make sure to always close streams when youre done with them

---

examples/echo/README.md
examples/echo/main.go

* Extended explanations and links to relevant godocs
* Some renames (the host is not dummy, it's basic)
* Use addAddr() and let NewStream open the connection to show how to make use of the peerstore.
I had also fixed the example but @lgierth submitted it first. I have merged my fixes with his.

Improve echo example

---

package.json

After that I have floodsub kad-dht and go-ipfs left to bubble it through.

Update deps for Priv Networks

---

examples/echo/main.go

imports cleanup, remove dup

---

examples/echo/main.go

Found another one, sorry I missed it the first time!

more imports cleanup, another dup.

---

tutorial/001-the-host/README.md
tutorial/001-the-host/host.go

Started out making a 'libp2p' tutorial from some of the things posted in this issue: https://github.com/ipfs/docs/issues/17#issuecomment-286908929
Feel free to contribute to this PR and make your own.

add first tutorial, showing creation of a host

---

p2p/net/mock/mock_stream.go

Before, on close, we:
1. Weren't completing the write.
2. Flushing the buffer without waiting the latency delay.
This fixes that by using two separate channels for close/reset and ignoring the
close channel in deliverOrWait.

make sure to not drop writes on close

---

.gx/lastpubver
.travis.yml
Makefile
package.json

* msgio (moved)
* secio
* testutil

update gx deps

---

p2p/discovery/mdns.go

Does not wait for first interval to elapse as in case we don't need frequent announcements and interval is set e.g. to several minutes - first announcement will happen only after it.
Closes #256

mDNS discovery starts announcing right away

---

package.json

License: MIT
Signed-off-by: Hector Sanjuan <hector@protocol.ai>

gx: update go-multistream

---

.gx/lastpubver
package.json

License: MIT
Signed-off-by: Hector Sanjuan <hector@protocol.ai>

gx publish 5.0.18

---

examples/libp2p-host/README.md

update README of the host example

---

NEWS.md

This should cover most of the breaking changes but doesn't cover some of the new
features.
Still need to flesh out the zombie streams documentation (e.g., FullClose etc.)

[WIP] Add a draft write-up for the release

---

p2p/net/mock/mock_notif_test.go
p2p/net/mock/mock_stream.go

Fix the *actual* bug behind https://github.com/libp2p/go-libp2p/pull/388
(note: I'd still like to merge that PR)

mock stream fixes

---

p2p/net/mock/mock_conn.go
p2p/net/mock/mock_link.go
p2p/net/mock/mock_stream.go
package.json

Part of libp2p/go-libp2p-net#27.

Add Stat to mock net conns and streams

---

defaults.go

Signed-off-by: gukq <gukaiqiang@gmail.com>

Just repair spelling mistake

---

package.json

Pulls in update to fix #415. Thanks @cannium!

gx: update go-libp2p-nat

---

.travis.yml
package.json

(disables discovery by default)

gx: update go-libp2p-circuit

---

config/config.go
defaults.go
libp2p_test.go
options.go

Enable relay by default in New

---

p2p/host/routed/routed.go

fix relay-specific address dialing in routed host

---

p2p/host/basic/basic_host_test.go

(we'll need this when doing a gx update)

fix buggy addr equal in test

---

config/config.go
defaults.go
options.go

Per @marten-seemann's suggestion.

switch to DisablePing instead of PingCustom

---

p2p/host/relay/autorelay.go

don't advertise the raw public address in autorelay

---

.gx/lastpubver
package.json

gx publish 6.0.40

---

.travis.yml
go.mod
go.sum
p2p/host/routed/routed.go

Also includes the relevant gomod updates and kills gx travis builds.

Respect nodial option in routed host

---

p2p/host/basic/basic_host.go

So that we don't spawn extra goroutines on identify push to handle cancellation.

Use cancelable background context in identify

---

go.mod
p2p/host/relay/autorelay_test.go

test: disable flaky autorelay test in CI

---

go.mod
go.sum

fixes a panic and has a few more perf improvements

dep: update goprocess

---

defaults.go
p2p/host/basic/basic_host_test.go
p2p/net/mock/interface.go
p2p/net/mock/mock_net.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/test/backpressure/backpressure_test.go

Just a few nit-picky typo fixes.

Fixed typos

---

p2p/host/basic/basic_host.go
p2p/net/mock/mock_stream.go

No need to manually subtract timestamps.

Make use of time.Until & time.Since

---

p2p/host/basic/basic_host.go
p2p/protocol/identify/id.go

No need to convert these types.

Avoid unnecessary conversions

---

go.mod
go.sum

Fixes a race condition when a user modifies the address list returned by InterfaceListenAddresses.

dep: update go-libp2p-swarm

---

go.mod
go.sum

chore: update yamux

---

p2p/discovery/mdns.go

This will trigger whenever we're, e.g., offline.

fix: reduce log level of a noisy log line

---

p2p/protocol/identify/id.go

use transient connections in identify streams

---

p2p/host/basic/basic_host.go

fix go vet

---

scripts/mkreleaselog

fix(mkreleasenotes): handle first commit

---

examples/go.sum
examples/ipfs-camp-2019/go.mod
examples/ipfs-camp-2019/go.sum
examples/pubsub/chat/go.sum

Otherwise `go test` will fail.

run go mod tidy in the examples

---

examples/go.sum
examples/ipfs-camp-2019/go.sum
examples/pubsub/chat/go.sum
go.mod
go.sum

chore: update zeroconf to v2.1.1

---

README.md

remove dead API link in README

---

p2p/protocol/holepunch/pb/holepunch.pb.go
p2p/protocol/holepunch/pb/holepunch.proto

See https://github.com/libp2p/specs/pull/375.

make the Type field required in the HolePunch protobuf

---

p2p/host/autorelay/addrsplosion_test.go
p2p/host/autorelay/autorelay_test.go

make it possible to run the auto relays tests multiple times

---

examples/go.mod
examples/go.sum
examples/ipfs-camp-2019/go.mod
examples/ipfs-camp-2019/go.sum
examples/pubsub/chat/go.mod
examples/pubsub/chat/go.sum
go.mod
go.sum
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_stream.go
p2p/protocol/circuitv2/client/conn.go
p2p/protocol/circuitv2/client/dial.go
p2p/protocol/circuitv2/client/handlers.go

Depends on https://github.com/libp2p/go-libp2p-swarm/pull/298.

use the new network.ConnStats

---

p2p/test/reconnects/reconnect_test.go

Fixes #1208.
TCP RST handling is flaky on OSX, see https://github.com/golang/go/issues/50254.
We can avoid this test from randomly failing by using QUIC instead.

run reconnect test using QUIC

---

p2p/net/mock/mock_notif_test.go

The problem here seems to be the following: The stream is inserted in the `nn.streamState` map by the `OpenedStream` notification. However, it's not guaranteed that this notification is processed before the stream is closed, so it might happen that we retrieve a `nil` channel from that map, receiving from which will block indefinitely.

fix flaky TestNotifications test

---

config/config.go
defaults.go
go.mod
go.sum
limits.go
p2p/host/basic/basic_host.go
p2p/net/mock/mock_stream.go
p2p/protocol/identify/id.go

Default ResourceManager

---

config/config.go
defaults.go
go.mod
go.sum
limits.go
p2p/host/autonat/client.go
p2p/host/autonat/svc.go
p2p/host/basic/basic_host.go
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_stream.go
p2p/protocol/circuitv1/relay/relay.go
p2p/protocol/circuitv2/client/dial.go
p2p/protocol/circuitv2/relay/relay.go
p2p/protocol/holepunch/coordination.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_delta.go
p2p/protocol/ping/ping.go

Integrate the resource manager in libp2p bundled services and initializes a default resource manager.
Includes #1289 squashed in.

Integrate the ResourceManager

---

p2p/host/autonat/svc.go

fix race condition causing TestAutoNATServiceDialError test failure

---

p2p/net/connmgr/decay_test.go

This will help debugging #1324.

speed up the connmgr tests

---

defaults.go
go.mod
go.sum

remove mplex from the list of default muxers

---

p2p/transport/quic/conn_test.go

quic: fix flaky holepunching test

---

p2p/transport/quic/reuse_test.go

quic: fix flaky TestReuseGarbageCollect test

---

p2p/transport/quic/conn_test.go

quic: fix flaky TestConnectionGating test

---

p2p/protocol/holepunch/svc.go

fix race condition in holepunch service

---

p2p/transport/quic/conn_test.go

quic: fix flaky TestResourceManagerAcceptDenied

---

p2p/net/swarm/dial_test.go

swarm: fix flaky and racy TestDialExistingConnection

---

p2p/host/basic/basic_host_test.go

basichost: fix flaky TestSignedPeerRecordWithNoListenAddrs

---

p2p/net/swarm/dial_worker_test.go

fix racy connection comparison in TestDialWorkerLoopBasic

---

p2p/protocol/holepunch/holepunch_test.go

holepunch: fix flaky TestEndToEndSimConnect test

---

p2p/net/conn-security-multistream/ssms_test.go

This was the only place where we imported `go-libp2p-testing/suites/sec`.

remove dependency on go-libp2p-testing/suites/sec

---

p2p/protocol/identify/id_test.go

Fixes #1565 by waiting a bit for the event

identify: fix flaky test

---

p2p/net/swarm/swarm_listen.go

swarm: fix logging of accepted connections

---

go.mod
go.sum

chore: remove duplicate clock dep

---

version.json

See https://github.com/libp2p/go-libp2p/issues/1514

Release v0.21.0

---

p2p/host/pstoremanager/pstoremanager_test.go

pstoremanager: fix flaky TestClose

---

p2p/host/autorelay/autorelay_test.go

autorelay: fix flaky TestMaxAge

---

p2p/transport/webtransport/listener.go
p2p/transport/webtransport/transport.go

webtransport: add and check the ?type=noise URL parameter

---

p2p/security/tls/transport_test.go

tls: fix flaky handshake cancellation test

---

core/network/network.go

Fixed small typo in network module

core/network: fix typo

---

go.mod
go.sum

https://github.com/marten-seemann/webtransport-go/pull/52

chore: update webtransport-go to get fix

---

go.mod
go.sum
p2p/transport/webtransport/transport_test.go

quic: update quic-go to v0.31.1

---

defaults.go

add WebTransport to the list of default transports

---

README.md

Show off how flaky/or not we are. And give a handy link to the notebook.
closes https://github.com/libp2p/go-libp2p/issues/1821

feat: add ci flakiness score to readme

---

test-plans/cmd/ping/main.go

see https://github.com/libp2p/test-plans/issues/107 for more context.

feat: ci test-plans: Parse test timeout parameter for interop test

---

p2p/net/swarm/grafana-dashboards/swarm.json

Fixes the dashboard by allowing users to select their Prometheus datasource.

swarm metrics: fix datasource for dashboard

---

p2p/transport/webtransport/crypto_test.go

closes https://github.com/libp2p/go-libp2p/pull/1884

webtransport: tidy up some test output

---

p2p/host/autonat/autonat.go
p2p/host/autorelay/autorelay.go
p2p/host/autorelay/relay_finder.go
p2p/host/pstoremanager/pstoremanager.go
p2p/host/relaysvc/relay.go
p2p/protocol/holepunch/svc.go
p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go

set names for eventbus event subscriptions

---

p2p/host/resource-manager/obs/grafana-dashboards/resource-manager.json
p2p/host/resource-manager/obs/stats.go

rcmgr: add libp2p prefix to all metrics

---

go.mod
go.sum
test-plans/go.mod
test-plans/go.sum

chore: update webtransport-go to v0.5.1

---

CHANGELOG.md

Having the changelog in VCS is creating an immense amount of churn...

chore: fix typo in Changelog

---

README.md

... and `ls -al` will show you all the files in the root directory. No need to point out the obvious.

chore: remove superfluous testing section from README

---

p2p/test/transport/integration_test.go

Adds basic integration tests for our transports. This is the first pass and we can add more tests in a future PR.

tests: add some basic transport integration tests

---

p2p/test/transport/integration_test.go

tests: add a stream read deadline transport test

---

p2p/transport/webtransport/transport.go

Revert "webtransport: initialize the certmanager when creating the transport"

---

dashboards/resource-manager/README.md
p2p/host/resource-manager/README.md
p2p/host/resource-manager/rcmgr.go
p2p/host/resource-manager/stats.go
p2p/test/resource-manager/rcmgr_test.go

depends on #2388 
closes #2372

rcmgr: enable metrics by default

---

p2p/net/swarm/dial_worker.go

Thanks to @sukunrt's persistent work on this component, the code is now a lot cleaner and better commented.

swarm: remove leftover TODO

---

p2p/host/basic/basic_host_test.go

Also do not sort the test cases twice.

tests: add a CertHashes testcase in TestInferWebtransportAddrsFromQuic

---

p2p/transport/webrtc/transport.go

Separate PR targeting #2337, to make it easier to review.

webrtc: mark the transport as experimental

---

p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

libp2phttp: don't initialise ServeMux if not nil

---

options.go
p2p/host/peerstore/pstoreds/protobook.go
p2p/host/peerstore/pstoremem/addr_book.go
p2p/host/peerstore/pstoremem/protobook.go
p2p/host/resource-manager/scope_test.go
p2p/net/connmgr/connmgr.go
p2p/net/gostream/gostream_test.go
p2p/net/mock/mock_test.go
p2p/net/swarm/swarm_metrics.go
p2p/transport/webtransport/cert_manager_test.go
p2p/transport/webtransport/transport_test.go

Used linter to detect unnecessary type conversions
https://github.com/mdempsky/unconvert

chore: remove unnecessary conversions

---

.github/ISSUE_TEMPLATE/config.yml

Add config.yml to add links to the technical go-libp2p forum and the libp2p community forum.

chore(cfg): Add config.yml for new issues

---

p2p/http/example_test.go

Use any port, not a specific one for HTTP examples

---

p2p/host/autorelay/addrsplosion.go

DNS protocol address is not reserved

fix: DNS protocol address is not reserved

---

p2p/test/transport/transport_test.go

Similar to the previous test `TestCloseConnWhenBlocked` but focused on WebRTC.

Test that the conn attempt is dropped when the rcmgr blocks it for WebRTC

---

README.md

[tau](https://github.com/taubyte/tau) is a distributed PaaS that uses libp2p for networking, routing and discovery. As of now tau has over 1500 stars on github.

Adding tau to `Notable Users` in README.md

---

go.mod
go.sum
test-plans/go.mod
test-plans/go.sum

This fixes the level for logs
```
sctp ERROR: 2024/07/24 12:29:44 [0xc00d787a40] stream 0 not found)
```

chore: update pion/sctp

---

funding.json

This reverts commit bdbe37e4286ee8c791118314a4c2875c7e8b2742. We do not push to master.

Revert "Create funding.json"

---

.github/workflows/go-test-config.json

Adds time and I don't think there's much value

Remove 32-bit tests

---

p2p/transport/tcp/metrics.go

tcp: fix metrics for multiple calls to Close

---

.github/workflows/release-check.yml

Until the fix in
https://github.com/ipdxco/unified-github-workflows/pull/96 is in

Use fork of release-check

---

p2p/net/pnet/psk_conn.go

pnet: wrap underlying error when reading nonce fails

---

p2p/net/swarm/dial_worker.go

swarm: remove stray print stmt

---

dashboards/autonatv2/autonatv2.json
dashboards/host-addrs/host-addrs.json
p2p/host/basic/addrs_manager.go
p2p/host/basic/addrs_manager_test.go
p2p/host/basic/addrs_metrics.go
p2p/host/basic/addrs_metrics_test.go
p2p/host/basic/addrs_reachability_tracker.go
p2p/host/basic/addrs_reachability_tracker_test.go
p2p/host/basic/basic_host.go
p2p/protocol/autonatv2/autonat.go
p2p/protocol/autonatv2/client.go
p2p/protocol/autonatv2/metrics.go
p2p/protocol/autonatv2/metrics_test.go

Adding some metrics to see autonat v2 performance.

autonatv2: add metrics
