p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/host/host.go
p2p/host/routed/routed.go
p2p/net/interface.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_net.go
p2p/net/swarm/swarm_test.go
p2p/protocol/ping/ping.go
p2p/protocol/relay/relay.go
p2p/protocol/relay/relay_test.go
p2p/test/backpressure/backpressure_test.go
p2p/test/reconnects/reconnect_test.go

this will allow dials caused by `NewStream` calls to be cancelled. They have a bad habit of hanging otherwise.

make new stream calls accept a context

---

p2p/crypto/secio/rw.go

go-msgio implements the message length limit (currently 8MB), so the
secio reader can get away without re-implementing this logic.
Instead, the reader lets go-msgio allocate a buffer when the output
buffer is too small to hold the incoming message. This buffer is kept
and drained into the output buffer(s) of Read() calls and released back
to the msgio instance once it is fully drained.
License: MIT
Signed-off-by: Randall Leeds <randall@bleeds.info>

Leave overflow logic to go-msgio

---

.travis.yml
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

the main change is question is on line 193, the rest is just a quick readability cleanup.
It doesnt appear that we ever add the actual address we get from the actual connection to the peerstore. That seems like a fairly severe oversight to me...

add remote multiaddr from active connection to peerstore

---

.travis.yml
p2p/net/conn/dial.go
p2p/net/conn/interface.go
p2p/net/swarm/dial_test.go
p2p/net/swarm/swarm_test.go
p2p/net/transport/fallback.go
p2p/net/transport/transport_test.go

Previously we were unable to dial on a given transport if there were no
listener addresses defined for that. This meant that most people couldnt
use utp (as they had no utp listener transport to dial from).

Add fallback dialer

---

p2p/net/conn/dial_test.go
p2p/net/conn/listen.go
package.json

Doing the multistream negotiation in sync causes hanging issues.
This commit accepts transport connections and starts the negotiation
in a separate goroutine, sending it down a channel when its ready.

Handle incoming conns in their own goroutines

---

p2p/net/filter/filter.go
p2p/net/filter/filter_test.go
p2p/net/swarm/swarm_test.go

License: MIT
Signed-off-by: Lars Gierth <larsg@systemli.org>

Fix address filtering for /ip6, add tests

---

p2p/net/conn/dial.go

we do this on the listener side, but forgot to add it on the dial

add a read deadline for the multistream select on dial

---

p2p/protocol/identify/id.go

If the `NewStream` or `SelectProtoOrFail` returns an error currently, anyone waiting for that connection would hang forever since the wait channel wouldnt get closed.

close wait channel in all cases, not just success

---

.gx/lastpubver
package.json

contains:
- ID service hang fix #49 
- Yamux stream hang patches #50

gx publish version 3.2.1

---

package.json

https://github.com/hashicorp/yamux/pull/28 and https://github.com/hashicorp/yamux/pull/29 were merged, this updates libp2p to use the official code as opposed to the hacked together fix i pushed earlier

update to official yamux fixes

---

p2p/discovery/mdns.go
p2p/host/basic/basic_host.go
p2p/host/host.go
p2p/host/routed/routed.go
p2p/net/interface.go
p2p/net/mock/interface.go
p2p/net/mock/mock_net.go
p2p/net/mock/mock_peernet.go
p2p/net/swarm/dial_test.go
p2p/net/swarm/peers_test.go
p2p/net/swarm/simul_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_addr_test.go
p2p/net/swarm/swarm_net.go
p2p/net/swarm/swarm_test.go
p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/ping/ping_test.go
p2p/test/util/util.go
package.json

This will make updates to the peerstore cause much less churn on the dependency tree.

split peerstore from peer package

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

This should resolve https://github.com/ipfs/go-ipfs/issues/2771

fix consumption of observed remote addrs

---

p2p/host/basic/basic_host.go
p2p/host/host.go
p2p/host/match.go
p2p/host/match_test.go
p2p/host/routed/routed.go
p2p/protocol/identify/id.go

This lets protocols easily match based on semver, so for example, `/bitswap/1.0.0` and `/bitswap/1.0.2` would be compatible.

p2p/host: expose multistream function matching and add semver func

---

examples/justtcp/main.go
p2p/net/swarm/swarm.go
package.json

This lets the 'empty' swarm constructor take in the stream muxer to use, also giving us the option to pass in 'nil' to avoid set up stream multiplexing (for use in the justtcp) example

swarm: pass in stream muxer on construct

---

p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_net.go

We call connectedness quite a lot, at least once every time we get a findPeer DHT rpc. Optimizing this saves us a lot of small objects that need to be garbage collected and map accesses

swarm: add optimized method for checking connectedness to peer

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

d767ab5 (jbenet, 73 seconds ago)
identify: tests verify we have public keys
d58b668 (jbenet, 2 minutes ago)
identify: consume public key in message.
Make sure to verify that our keys match. In the rare event they do not,
make sure to investigate what's wrong, and log errors.
65273ab (jbenet, 2 minutes ago)
identify: send public key in message

identify: send + consume public keys too

---

CONTRIBUTE.md
README.md

Addresses https://github.com/libp2p/go-libp2p/issues/41

Fix libp2p spec link

---

p2p/net/swarm/dial_sync.go
p2p/net/swarm/dial_sync_test.go
p2p/net/swarm/dial_test.go
p2p/net/swarm/limiter.go
p2p/net/swarm/limiter_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go

The previous dialsync code was susceptible to the issue described in #105 
This fixes that and adds some tests around the whole thing

Improve swarm dial sync code

---

p2p/discovery/mdns.go
p2p/discovery/mdns_test.go

The current code runs the `Connect` calls for each peer discovered over mdns in the same goroutine. If a connect call starts to hang, then it gums up the entire mdns discovery process.

don't block on DiscoverHandler

---

README.md

The linked repo seems to have been left behind vs the examples folder which contains working examples.

Readme.md: point to the right location for examples.

---

p2p/host/basic/basic_host.go
p2p/net/mock/mock_net.go

We get a fair number of goroutines hanging in negotiate here. This should at least help prevent the buildup.

add negotiate timeout option to basichost

---

p2p/host/basic/basic_host_test.go
p2p/protocol/identify/id.go
package.json

This solves the issue of mis-remembering that a peer supports a given protocol if they downgrade their versions (or no longer support a known preferred version).

address protocol downgrade bug

---

p2p/protocol/identify/id.go

We're starting to have non-standard libp2p nodes in the network, this should help differentiate things for easier testing.

identify: make agent version mutable

---

.gitignore
.travis.yml
Makefile
examples/echo/README.md
examples/echo/main.go
examples/http-proxy/README.md
examples/http-proxy/proxy.go
examples/multicodecs/README.md
examples/multicodecs/main.go

Improved echo example
Added example for multicodecs
Related to https://github.com/ipfs/docs/issues/17

Libp2p examples

---

package.json

Depends on:
- https://github.com/libp2p/go-libp2p-net/pull/7
- https://github.com/libp2p/go-libp2p-metrics/pull/2
- https://github.com/libp2p/go-libp2p-host/pull/3
- https://github.com/libp2p/go-libp2p-swarm/pull/22
- https://github.com/libp2p/go-libp2p-netutil/pull/4
- https://github.com/libp2p/go-libp2p-blankhost/pull/1

gx: update go-libp2p-peerstore

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

This is for ipfs/go-ipfs#3613. I decided to cheat and just sidestep the whole passing-options-through-n-layers-of-node-initialization. The calling code will simply pass a closure as the `AddrsFactory` option which applies the announced/noAnnounced addrs if neccessary.
(I'm open to better names than AddrsFactory.)
TODO:

basichost: allow overriding Addrs()

---

p2p/host/basic/basic_host.go
p2p/host/basic/natmgr.go
p2p/net/mock/mock_net.go
p2p/protocol/identify/id.go

- I'd like to do a similar thing with Swarm
- The first commit (allow overriding Addrs) is from an unrelated PR (#196)
---
There were previously 4 different ways of passing various options
into BasicHost construction.
1. Function parameters to New
2. Option parameters to New
3. Global variables, e.g. NegotiateTimeout
4. Options struct, in the calling code in go-ipfs
This changeset deprecates all of these, and introduces the HostOpts
struct to replace them. It also introduces a new constructor called
NewHost, which accepts a *HostOpts.
The old New constructor continues to work the same way,
but is from now on deprecated too.

basichost: refactor BasicHost construction

---

package.json

Depends on:
- https://github.com/libp2p/go-libp2p-conn/pull/10
- https://github.com/libp2p/go-libp2p-swarm/pull/24
- https://github.com/libp2p/go-libp2p-netutil/pull/5
This PR with gx updates has been created using gx-workspace: https://github.com/ipfs/gx-workspace

gx: update go-addr-util, go-libp2p-swarm

---

p2p/host/routed/routed.go

RoutedHost: NewStream ensures we have the means to connect to the peer

---

p2p/host/basic/basic_host.go
p2p/net/mock/mock_net.go
package.json

Integrates Circuit Relay as a transport option in basic_host.NewHost.
See #209

Circuit Relay integration with basic_host

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
package.json

I worked on [go-multiaddr-dns](https://github.com/multiformats/go-multiaddr-dns) a bit more and I think it's good enough now. Typing docs and dnsaddr specs too.
This will be used for 1) DNS-enabled bootstrap, and 2) configurable announced swarm addresses.
For a first try I picked BasicHost.Connect as the place for integration. Another way I thought about is async resolution from within Peerstore whenever we learn about a new address.

Resolve /dns4, /dns6, /dnsaddr multiaddrs

---

p2p/net/mock/mock_notif_test.go
p2p/net/mock/mock_peernet.go

this makes the test cases a bit more accurate.

tests: update test cases to act like go-peerstream 1.7.0

---

package.json

Depends on:
- https://github.com/libp2p/go-libp2p-conn/pull/12
- https://github.com/libp2p/go-libp2p-connmgr/pull/3
- https://github.com/libp2p/go-libp2p-host/pull/6
- https://github.com/libp2p/go-libp2p-swarm/pull/28
- https://github.com/libp2p/go-libp2p-netutil/pull/8
- https://github.com/libp2p/go-libp2p-blankhost/pull/3
- https://github.com/libp2p/go-libp2p-circuit/pull/10
This PR with gx updates has been created using gx-workspace: https://github.com/ipfs/gx-workspace

gx: update go-testutil

---

examples/echo/README.md

When not using -secio, this command prints a warning. This confuses users so we should just tell users to use it in the instructions.
fixes #179
fixes #215

examples/echo: recommend -secio

---

README.md

We need to download dependencies for all packages in the repo, not just the
root (there are no packages at the root).
fixes #219

Fix the go get command.

---

examples/protocol-multiplexing-with-multicodecs/README.md

As is go build ./examples/protocol-multiplexing-with-multicodecs
will make the binary name protocol-multiplexing-with-multicodecs
so the next command ./multicodecs won't run
using -o will name the outputfile

Protocol Multiplexing Example: Fixing build instruction so copy and pasting from the Readme works

---

p2p/host/basic/basic_host.go

The warning message is malformed; clear intention was to use `log.Warningf`:
```
12:07:34.885 WARNI  basichost: protocol mux failed: %s (took %s)connection reset 70.660962ms basic_host.go:258
```

basic_host: fix warning message

---

examples/echo/main.go
examples/libp2p-host/host.go
libp2p.go
package.json

Trying to make using go-libp2p as simple as possible

first hack at a nice libp2p constructor

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

This commit
1. Registers the identify service for disconnect notifications (so we don't just keep all observed addresses indefinitely).
2. Prevents us from repeatedly extending the lifetimes (on disconnect) of all observed addresses if a peer keeps on reconnecting.
It also fixes two race conditions:
1. We may end up processing a disconnect after a re-connect and may accidentally give the addresses associated with that peer a RecentlyConnectedAddrTTL instead of a ConnectedAddrTTL.
2. We may end up processing a connect after the associated disconnect storing the associated peer addresses indefinitely.

fix peerstore apocalypse redux

---

libp2p.go

Added default muxer in case when none was provided.

---

p2p/protocol/identify/id_test.go

make the identify test less racy

---

p2p/discovery/mdns_test.go

This tests fails about 9 out of 10 times for me, making the use of gx-workspace on libp2p related trees rather annoying.
Should get re-enabled after https://github.com/libp2p/go-libp2p/issues/257 is done.

Skip TestMdnsDiscovery

---

examples/http-proxy/proxy.go
examples/multipro/echo.go

I'm not sure *why* gx threw a fit over the module name but... it should have been called `pb` anyways.

fix CI and gx

---

examples/README.md
examples/chat/README.md
examples/chat/chat.go

Please let me know if this chat application is worth adding to the example folder. 
This example demonstrate connecting two peers and opening a stream and chat on that stream. It can work if both the peers are on the same network or if any one of them has a public IP address.
@Stebalien can you please review this PR.
Let me know if some changes needs to be done.

Added example "chat" with README

---

libp2p.go
libp2p_test.go

This change adds an option to enable NAT traversal by including `NATPortMap()` in the `[]Option`. I also went ahead and added a basic test for the constructor, although I noticed this package does not yet have any, and wonder if that might be intentional. I also switched to the `basichost.NewHost` constructor, since `New` is depreciated.

added NAT traversal option and constructor test

---

package.json

it does not seem used here or anywhere.
License: MIT
Signed-off-by: Hector Sanjuan <hector@protocol.ai>

Remove go-metrics from package.json

---

.gx/lastpubver
config/config.go
config/constructor_types.go
config/muxer.go
config/muxer_test.go
config/reflection_magic.go
config/reflection_magic_test.go
config/security.go
config/transport.go
defaults.go
error_util.go
examples/chat/chat.go
examples/echo/main.go
examples/http-proxy/proxy.go
examples/multipro/main.go
examples/protocol-multiplexing-with-multicodecs/main.go
libp2p.go
libp2p_test.go
options.go
p2p/discovery/mdns_test.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/net/mock/mock_conn.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/ping/ping_test.go
p2p/test/backpressure/backpressure_test.go
p2p/test/reconnects/reconnect_test.go
package.json

Also, make the libp2p constructor fully useful. There should now be no need to manually construct a swarm/host. That's actually where most of the new code comes from (hence the +450 lines of (actual) code). This allows me to actually use the libp2p constructor in go-ipfs.
DO NOT MERGE (yet)
Part of: libp2p/go-libp2p#297

refactor for transport changes

---

examples/libp2p-host/README.md

so reader can see all the supported configuration for the
host constructor

add a link to options.go in the host example

---

p2p/net/mock/mock_test.go

This PR adds a simple test which demonstrates how one might configure a `Mocknet` with some latency.

Add test which demonstrates how Mocknet latency works

---

p2p/host/basic/basic_host.go

`%!s(func() peer.ID=0x7e4280)`

function cannot be formatted as string

---

p2p/host/basic/basic_host.go
p2p/host/routed/routed.go

(counting open connections requires copying)

check for connectedness using Connectedness

---

p2p/protocol/identify/id.go

This happens all the time in tests where we intentionally use fake keys for
performance.
Anyways, users probably don't want their logs spammed with errors they can't do
anything about.

reduce error to warning and log the error

---

p2p/host/basic/natmgr.go

related to #383
I won't call this *fixed* yet but it should help.

when we do a nat port mapping, explicitly remember the mapped address

---

p2p/host/basic/natmgr.go

This reverts commit aca83b9b6302000167c95dfb96eb4812cf1c0e93, reversing
changes made to 86b8929d4ddf3d38d4ee4cca6651abb9d05f16da.
This was is not the correct fix. We already expose these addresses via the
host's AllAddrs method. The real problem is probably that we just don't ever
tell anyone about them (unless we disconnect and reconnect to our nearby DHT
nodes).
We need an address gossip protocol.

Revert "Merge pull request #386 from libp2p/fix/correct-external-addr"

---

config/muxer.go
config/muxer_test.go
config/security.go

Without adding the transport to the set, we'll never identify if there
are duplicates in the slice of secure transports provided by the config.

Ensure duplicate transports are filtered

---

libp2p_test.go
options.go

So, in go-ipfs at least, we *don't* pass the listen addresses into the libp2p constructor. Instead, we specify them later.
This option allows us to tell libp2p to not listen by default.
The alternative is to just revert that PR and tell users that they need to configure libp2p to listen on some port. The question is really: "what's more surprising?"

add options for disabling the default listen address/transports

---

p2p/discovery/mdns.go
package.json

Fixes #392. Depends on https://github.com/whyrusleeping/mdns/pull/3.
We should merge this *before* rolling out an IPFS release with QUIC support. This fix is necessary to be able to activate QUIC logging.

use the new DisableLogging mdns option, don't turn off logging globally

---

p2p/protocol/identify/id.go

fixes #419
Also call FullClose in a goroutine; no need to block this.
(not happy with that but I'm starting to think we need to rethink stream closing, again...)

always remove connection from identify service map

---

p2p/host/basic/basic_host.go

Sometimes `ipfs id` show duplicate addresses since peer observed addresses are likely same as interface listen addresses or NAT external addresses.

Deduplicate addresses of host output

---

p2p/host/basic/basic_host.go
p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

Fix https://github.com/libp2p/go-libp2p/issues/416

Track more info for observed addresses

---

p2p/host/basic/basic_host.go

There is no real information conveyed (so it's really not INFO) and there is tons of it.
The more pertinent question is why I see so many of them -- probably because of prevalence of undialable addrs

downgrade protocol mux failure log to debug

---

config/config.go
defaults.go
options.go
p2p/host/basic/basic_host.go
p2p/protocol/ping/ping.go
p2p/protocol/ping/ping_test.go

Adds the ping service to basic_host, with a libp2p constructor option to control its instantiation; it's enabled by default.

Add ping service in basic host and libp2p constructor option (enabled by default)

---

p2p/protocol/identify/id.go
package.json

Sending a protocol version is nice. However, this "disconnect if our versions are different" logic makes the version entirely useless (because we can't change it).
Really, each indevidual protocol is versioned so let's just leave it at that. If we make a breaking change that requires a protocol bump, we can do that and then switch on the other side's version. However, we'll have to wait for the entire network to upgrade for that to work.

don't disconnect on protocol version mismatch

---

p2p/net/mock/mock_stream.go

This was causing https://github.com/ipfs/go-ipfs/pull/5637#issuecomment-432792969

fix a data-race in the mock net

---

p2p/net/mock/mock_net.go
p2p/net/mock/mock_test.go

RandLocalTCPAddress is mostly useful when we *actually* want to listen on a real
address. Unfortunately, when running a bunch of tests, we can actually run
out.
With this change, a collision means we have a duplicate peer ID so yeah...
fixes #473

mocknet: use peer ID in peer address

---

p2p/host/relay/autorelay_test.go
p2p/host/relay/relay.go

This came up in https://github.com/libp2p/go-libp2p-discovery/issues/5
Also increases the test autonat identify delay to 500ms to make it less flaky in macos.

Add delay in initial relay advertisement to allow the dht time to bootstrap

---

config/config.go
options.go
p2p/host/relay/autorelay_test.go

necessary for https://github.com/ipfs/go-ipfs/pull/5785

explicit option to enable autorelay

---

config/config.go
p2p/host/relay/autorelay.go

Fixes a subtle bug: if the discovery module returns no addresses for the relay peers, then we might not be able to connect to them because we only have a basic host.

Use PeerRouting in autorelay to find relay peer addresses

---

p2p/host/relay/relay.go

5s is too short to initialize the DHT.

increase initial relay advertisement delay to 30s

---

p2p/net/mock/mock_conn.go
p2p/net/mock/mock_stream.go

- changed GetStreams function from mock_conn.go to call allStreams which has the same functionality but is concurrent safe
- changed protocol field from mock_stream to be concurrent safe. Taken the implementation from swarm_stream.go

Fixed race conditions in mock package mock_stream and mock_conn

---

p2p/host/basic/basic_host.go

It has no functional difference but it shakes the tree and asserts that p2p is the correct code. I did fix something ages back rewrote p2p codes to ipfs, even when they originally were not. This is a similar assertion.

Resolve addrs with P2P instead of IPFS

---

go.mod
go.sum
p2p/host/basic/basic_host.go
p2p/host/basic/natmgr.go
p2p/host/relay/autorelay_test.go
p2p/net/mock/mock_link.go
p2p/net/mock/mock_test.go
p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go
package.json

1. Update to work with https://github.com/libp2p/go-libp2p-nat/pull/14.
2. Avoid observed addrs when our NAT tells us about external addrs.
3. Ignore bad addrs reported by our NAT. Substitute with observed addrs.
4. Fix https://github.com/libp2p/go-libp2p/issues/428.
(really, I'm just trying to get NAT port mapping working on my network...)

better nat mapping

---

p2p/net/README.md

"Requet" -> "Request", "tls" -> "TLS"

Fix typos in p2p/net/README.md

---

p2p/protocol/identify/id.go

LocalMultiaddr May return the Unspecified Address, if so, we need to
check if we listen on the Unspecified address and they were equal.

Fix UDP listen on a Unspecified Address and Dial from the Unspecified Address

---

p2p/host/relay/autorelay.go

StringCast will do the panicking for us.

relay: simplify declaration of multiaddr var

---

go.mod
go.sum
p2p/host/relay/autorelay.go

Reduces the autorelay boot delay to take advantage of recent autonat optimizations and also correctly handles the private->public transition by scheduling an identify push in that case.
Depends on https://github.com/libp2p/go-libp2p-autonat/pull/20 [go mod update needed]

Reduce autorelay boot delay and correctly handle private->public transition

---

README.md

Links to our shiny new [discussion forum](https://discuss.libp2p.io) and [docs site](https://docs.libp2p.io)

Link to docs & discuss in readme

---

config/config.go
options.go
p2p/host/relay/autorelay.go
p2p/host/relay/doc.go
p2p/host/relay/relay.go

relay: turn autorelay into a service and always filter out relay addresses

---

p2p/protocol/identify/id.go

1. Never record addresses _we_ observe. Only store addresses if a peer tells us to. This could make dialing back a bit harder but should give nodes more control over the addresses they care to advertise.
2. Only record reported observed addresses if they match the transports of some address we're already advertising. For example, we should only advertise relay addresses if we're already advertising other relay addresses.
Note: I don't believe this is related to #575 but, IMO, it's still a good idea.

identify: be more careful about the addresses we store

---

p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

The test added here is just to benchmark the effect of lock contention. In my tests, this patch makes things ~4x faster (54 seconds to 14.5 seconds)

move things outside of the lock in obsaddr

---

p2p/protocol/identify/obsaddr.go

1. Don't bother formatting the address as a _string_.
2. Use SplitFirst to avoid parsing the entire address.

identify: avoid parsing/printing multiaddrs

---

p2p/host/basic/basic_host.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

Overhauls the observed address set to be more friendly to relays:
- Optimizes the lock contention in Addrs, AddrsFor by stopping the eager clean up of expired entries
- Adds a background worker for adding and gc'ing observed address, with a very short buffer
Closes #584

Improve observed address handling

---

p2p/protocol/identify/obsaddr.go

The activated check cleans up, which leads to panics with concurrent reads.
This moves the seenBy set clean up into gc, where it belongs

fix panic in observed address activation check

---

README.md

Following on with https://github.com/libp2p/go-libp2p/issues/589, we want to go all in on gomod.
This removes instructions for using `gx` and adds a link to the https://github.com/libp2p/workspace-go-libp2p repo, with some context on why you should use it.
I also added an "About gx" section for people that are or were using it to encourage them to make the switch.

Deprecate gx in readme & link to workspace repo

---

go.mod
go.sum

Switches to libp2p/go-nat which has some improved gateway detection logic.

dep: update go-libp2p-nat

---

go.mod
go.sum

This time, don't try to map the same internal/external port. Random ports are safer as not all NAT devices can handle port conflicts...

dep: update go-libp2p-nat again

---

go.mod
go.sum

Merges in the longer `TempAddrTTL`.

gomod: update go-libp2p-peerstore

---

p2p/protocol/identify/id.go

Replace peer addresses in identify

---

config/config.go
config/config_test.go
libp2p.go
libp2p_test.go

This can make it significantly easier to configure libp2p with optional options.

constructor: allow nil options

---

config/config.go
p2p/host/basic/basic_host.go
p2p/net/mock/mock_test.go
p2p/protocol/identify/id.go

Adds a background task to basic host, that periodically schedules an identify push if the address set has changed.

Periodically schedule identify push if the address set has changed

---

p2p/host/relay/addrsplosion.go
p2p/host/relay/addrsplosion_test.go
p2p/host/relay/autorelay.go
p2p/host/relay/autorelay_test.go
p2p/host/relay/relay.go

Relays, as discovered in the DHT, are _addrsploded_. The current (pre-)computation of advertised relay addrs fails to account for this fact, resulting in the advertisement of many dead addresses. In addition, many relays discovered in the DHT are actually dead.
This patch adds logic to deal with the situation
- relay addrs are dynamically recomputed by the address factory using the relay addrs present in the peerstore instead of pre-computing based on what was advertised.
- a special clean up pass is done on the relay address set to remove addrsploded addrs.
- a retry pass is added to `findRelays` that deals with the case of no live relays in the discovered set.
- we also increase the relay advertisement boot delay to 15 min so that some minimum node stability is ensured.
Note: the patch …

autorelay: curtail addrsplosion

---

p2p/host/relay/autorelay.go

(@stebalien is picky and opinionated...)
* No goto.
* No counters (except the "retry" counter).
* Dedup retry-wait logic.
* Smaller functions.

autorelay: break findRelays into multiple functions and avoid the goto

---

p2p/host/relay/autorelay.go

`relayAddrs` is not the cheapest of methods and can be called potentially hundreds of times within a short period of time whenever there is a push.
This patch adds a bit of logic to cache the result for a short period of time, enough to cover a single push.

cache relayAddrs for a short period of time

---

p2p/host/relay/autorelay.go

now that we have the lock for the duration of the method, we don't need the intermediate
relays array. This removes it, and also extends the pre-allocation of the result array
by 2 so that it can cover two localhost and two private address bindings.

avoid intermediate allocation in relayAddrs

---

go.mod
go.sum

1. It now supports go modules.
2. It should spawn fewer goroutines, especially when used with contexts.

dep: update goprocess

---

p2p/protocol/ping/ping.go
p2p/protocol/ping/ping_test.go

Otherwise, we can't return errors. This is a breaking change but unlikely to have a large impact on anyone but go-ipfs.
This _also_ ensures canceling ping actually aborts the ping without waiting.
Part of https://github.com/ipfs/go-ipfs/issues/6298.

ping: return a stream of results

---

go.mod
go.sum
p2p/host/relay/autorelay.go
p2p/host/relay/relay.go

It has been observed that relays are not always discoverable, presumably because of DHT churn.
This cuts down the relay advertisement TTL to 30min (from 3hrs).

Frequent Relay Advertisements

---

p2p/host/basic/basic_host.go

As long as we _accept_ a context, we need to obey it.
fixes https://github.com/libp2p/go-libp2p-connmgr/issues/49

basic_host: ensure we close correctly when the context is canceled

---

go.mod
go.sum
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

This PR makes identify emit completion/failed events on the eventbus.
NOTE: Ignore the `fmt.Println` in the review, they are intentional; need to show @whyrusleeping something.

identify: emit events on completion/failure.

---

go.mod
go.sum
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/net/mock/mock_test.go

fix: use the goprocess for closing

---

p2p/net/mock/mock_peernet.go

We don't use `cs` here, drop it.

Removed ineffectual assignments

---

p2p/test/backpressure/backpressure_test.go

Just slightly easier to read/parse, in my opinion.

Simplify increments

---

p2p/host/relay/autorelay_test.go

Since err gets assigned, I assume we also want to check for it being nil.

Added missing error check in test

---

go.sum
p2p/discovery/mdns.go

We don't want to use the transformed/munged host addresses for local announcements. Ideally, we'd take a more scientific approach to this (i.e., "host, please give me addresses relative to X") but we can't do that yet.
Note: this is causing mdns to break when used with autorelay

mdns: always use interface addresses

---

go.mod
go.sum
p2p/host/relay/autorelay.go

autorelay: ensure candidate relays can hop

---

config/config.go
config/security.go

Hey @bigs & @raulk, I realized that I never closed the loop on this and pushed the go-libp2p branch that uses the new plaintext constructor. Sorry about that!

use new constructor for insecure transport

---

options.go

The new `Filters` option allows users to take ownership of the `Filters` struct and is suitable for cases where the addresses you want to accept/deny can change over time. We're using it in [0x Mesh](https://github.com/0xProject/0x-mesh) to implement IP-based rate-limiting/banning (see https://github.com/0xProject/0x-mesh/pull/392).

Add Filters option

---

README.md

We do not want to contribute to informing Google of every single user that uses go-libp2p, thanks.
Also, the default proxy (proxy.golang.org) contains old and deprecated `+incompatible` versions that the Go toolchain selects over the more recent go-modded versions.
See https://github.com/golang/go/issues/34189 and https://github.com/golang/go/issues/34217.
Fixes #730.

readme: add instructions for bypassing default gomod proxy.

---

p2p/protocol/identify/obsaddr.go

Also: fix the comments and try to explain how the activation/aliveness of
addresses happen (and write the correct defaults)

Identify: Make activation threshold configurable

---

p2p/protocol/identify/id.go

Some transports return 0.0.0.0 for the local address. Really, if one side is local, both we're on the same machine.
fixes https://github.com/libp2p/go-libp2p-quic-transport/pull/66

fix(identify): announce localhost as long as one side of the connection is local

---

go.mod
go.sum

Fixes a potential panic due to a race condition in `go-ssdp`.

update go-libp2p-nat to v0.0.5

---

go.sum
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

We currently only resolve /dnsaddr addresses once. This patch resolves up to 32 dnsaddr addresses per dial.
fixes https://github.com/libp2p/go-libp2p/issues/744

feat(host): recursively resolve addresses

---

p2p/host/basic/basic_host.go

Otherwise, we spam an error every time we try to negotiate a protocol on a
closed stream (e.g., when the underlying connection closes on us).

fix: demote stream deadline errors to debug logs

---

p2p/host/basic/basic_host.go

Announce both non-public port mapping address and observed address.
Fixes #769

enable non-public address port mapping announcement

---

config/config.go
options.go
p2p/host/relay/autorelay.go

So that we can avoid hitting the DHT; also changes the desired relays parameter to 1 (from 3).
See #694

options to configure static relays for autorelay

---

p2p/net/mock/mock_test.go

CI is slow so we should increase our tolerance. This is just a test for our _mock_ network anyways.

chore(ci): fix a flaky test

---

p2p/host/routed/routed.go

@raulk 
While working on the REPL, which uses a `RoutedHost`, I realized we need to make it introspectable
for a caller to be able to fetch the ListenAddresses.

Make routed host introspectable

---

go.mod
go.sum
libp2p.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

_**Merge strategy: squash and merge.**_
With this PR, go-libp2p:
1. starts emitting identification complete/failed events when identify runs on a peer.
2. filters loopback addresses from identify.
I'm not 100% sold on the latter change, and I'm seeking validation/input. See original discussion on #657; I only merged that patch to stabilize, but now that it's percolating up to master, it's worthy of reconsideration.

identify: emit events; filter out loopback addresses

---

config/muxer.go
config/security.go
defaults.go
libp2p.go
options.go

After going through the code I found a few inconsistencies on comment sentences.
Some comment sentences did not end in a period, which causes inconsistent docs with the majority of libp2p docs and broader go ecosystem. [golang/go/wiki/CodeReviewComments#comment-sentences](https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences) recommends that we end with this period, which we mostly do in the codebase.
Also fixed a minor typo.

docs: uniform comment sentences

---

p2p/net/mock/mock_stream.go

Use of mux.ErrReset in mocknet

---

config/config.go

Given that if static relays are passed in to the `AutoRelay` constructor we should be able to construct an `AutoRelay` even when there are no `ContentRouting` implementations passed in.
@willscott ran into this issue when trying to construct testground integration tests of autorelay. We can hack around it by passing in a `Null ContentRouter` implementation, but that seems incorrect.

EnableAutoRelay should work without ContentRouting if there are StaticRelays defined

---

p2p/protocol/identify/id_delta.go

The stream handler runs in a goroutine anyways. We might as well block it.

fix: remove an unnecessary goroutine

---

options.go

Routing is only required for autorelay when no static relays are configured.

doc(options): fix autorelay documentation

---

p2p/net/mock/complement.go
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_link.go
p2p/net/mock/mock_notif_test.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_stream.go

* Export StreamComplement/ConnComplement convenience functions.
* Make the TestNotifications test pass reliably, even when we have a bunch of streams (identify, etc.).
* Make the mock net order disconnect events after connect events.
* Make closing one side of a connection actually close both sides.
* Make it possible to extract a mock stream's complement.
* Fire remote events at the same time as the local events.
I'm hoping this will put an end to spurious test failures due to mocknet issues.
Just kidding, that'll never happen.

feat(mock): reliable notifications

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/host/relay/autorelay.go

Pulls out the address change event from https://github.com/libp2p/go-libp2p/pull/747.

Local addr updated event

---

config/config.go

Currently, the AutoNAT dialer spins up a full host with identify, ping, etc. this switches to a blankhost.
This also avoids running a relay, listening on transports, etc (regression).

fix: minimal autonat dialer

---

go.mod
go.sum
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/host/relay/autorelay.go

Signal address change

---

config/config.go
libp2p_test.go

Otherwise, it the node fails to build.

fix: set the private key when constructing the autonat service

---

go.mod
go.sum

Bump go-libp2p-yamux and go-libp2p-mplex to point releases that have disabled write coalescing until more testing of that change occurs.

disable write coalescing

---

go.mod
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

Remove goprocess from Host

---

options.go

Clearer naming of nat override options

---

config/config.go
options.go

Exposes the underlying autonat options for throttling at the libp2p level.

Expose option for setting autonat throttling

---

defaults.go
go.mod
go.sum

But don't make it the default per https://github.com/libp2p/go-libp2p/pull/710#pullrequestreview-382182995.

feat: support TLS by default

---

p2p/net/mock/mock_conn.go

slightly less naive address selection.

deprioritize unspecified addresses in mock connections

---

go.mod
go.sum
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/net/mock/mock_test.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

The DHT now assumes that the protocols will be set in the peerstore once the identify event has fired. However, if we ended up identifying the peer multiple times (multiple calls to Connect at the same time, multiple connections, etc.), we'd end up unsetting the protocols temporarily.
This change:
1. Avoids ever unsetting the protocols, ever.
2. Avoids running the identify protocol on the same connection multiple times, ever.
3. Always waits for identify to complete (or fail) before using a connection.
Chang 2 should not cause any performance degradation:
1. Before this change, if the connection had not yet been identified, we'd wait at least one round-trip per new stream to negotiate the protocol.
2. After the change, we now wait exactly one round trip to complete the identify handshake. …

fix: refactor logic for identifying connections

---

go.mod
go.sum
p2p/host/basic/basic_host.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_delta.go
p2p/protocol/identify/id_push.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/peer_loop.go
p2p/protocol/identify/peer_loop_test.go

For #823 & #903 .
Blankhost PR at https://github.com/libp2p/go-libp2p-blankhost/pull/42.

Remove race between ID, Push & Delta

---

p2p/host/basic/basic_host.go
p2p/net/mock/mock_net.go
p2p/protocol/identify/id.go
p2p/protocol/identify/opts.go

For https://github.com/libp2p/go-libp2p/issues/929.
Mocknets use Bogus private keys which shouldn't be used for signing records. However, this leads to the peer sending malformed signed peer records which floods up our test logs. 
This PR exposes an Option on the Host to disable generation of signed peer records. It also ensures that Identify responses we send ONLY have unsigned addresses. 
ONLY Mocknets uses this Option.

Disable generation of Signed peer record for Mockenets

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

This shows off what I think is causing https://github.com/libp2p/go-libp2p/issues/939
The problem is that we're starting our hosts without listen addrs, and apparently the peerstore isn't keeping our signed records since they don't have any addrs. Then, when we call `.Listen`, it takes ~ 5 seconds for the change to be detected and the new record to be generated.
cc @aarshkshah1992 @raulk @vyzo

add test to demo missing peer records after listen

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

fix: don't try to marshal a nil record

---

p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

Filter observed addresses

---

options.go
options_filter.go

There's no reason for this adapter to be public and muddy the public namespace:
* The user can only set `Filters` via the constructor.
* In no other place would a user need to convert an existing `Filters` to a `ConnectionGater`. `ConnectionGaters` are also set via the constructor.

make the {F=>f}iltersConnectionGater private.

---

p2p/protocol/identify/id_test.go

@Stebalien 
We should create the `EvtPeerIdentificationCompleted ` subscriber before we connect to the other peer.
For #944.

Fix potential flakiness in TestIDService

---

p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

In #917, we started dropping additional address observations if we had multiple for the same transport set. However, on further consideration, this isn't quite correct. We _want_ to keep additional observations for multiple IP addresses. The real issue is many observations for different ports.
So this patch simply changes the key with which we group observations from "address protocols" to "address without the port" (well, with the port set to 0).

fix: group observations by zeroing port

---

p2p/protocol/identify/id_test.go

For https://github.com/libp2p/go-libp2p/issues/950.

Fix flaky TestIdentifyPushOnAddrChange

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

Previously, we'd keep addresses discovered through the DHT for up to 2 minutes (temporary TTL) and previously seen addresses (recently connected) for up to 10 minutes (the TTL).
1. Make sure to downgrade both connected and recently connected addresses to the "temporary" ttl before adding new addresses.
2. Finally, downgrade addresses with the temporary TTL to 0.
This could be more efficient with a better peerstore abstraction, but this is better than nothing.

fix: remove old addresses in identify immediately

---

go.mod
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

@Stebalien @willscott 
For #911 .

Filter Interface Addresses

---

p2p/host/basic/basic_host.go

See https://github.com/libp2p/go-libp2p/pull/936.

Fixed compilation error due to net.Notify

---

go.mod
go.sum

go-libp2p-core@v0.5.7
go-libp2p-connmgr@v0.2.4 [indirect]
go-eventbus@v0.2.1

gomod: update dependencies

---

p2p/net/mock/mock_link.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_glass_test.go
p2p/protocol/identify/obsaddr_test.go

We call this _very_ frequently when computing our local addresses.
This PR also:
* Unexports some exported types to reduce confusion.
* Fixes a bug in the mock net.
* Ensures we don't clobber an _inbound_ observation with an outbound observation.
Review commit by commit.

optimize numInbound count

---

p2p/protocol/identify/id.go
p2p/protocol/identify/peer_loop.go
p2p/protocol/identify/peer_loop_test.go

Alternative to #963. Instead of using atomics, this patch ensures that all state changes are performed on the main thread. It also:
* Threads the context through explicitly to make sure fields changed by the main thread are never read by the handler goroutines. This isn't strictly necessary but it makes it easier to reason about.
* Uses a callback to signal "on done". There may be cleaner ways to do this (I hate callbacks), but this nicely decouples the peer handler from the main loop.
fixes #963

Fix peer handler race

---

p2p/host/basic/basic_host.go

We switched `listenAddrs` from the _interface_ addresses to the raw addresses we
were listening on. Unfortunately, we needed the resolved addresses later in the
function when resolving port mappings.

fix(nat): use the right addresses when nat port mapping

---

p2p/host/basic/natmgr.go

Before, we would:
1. Receive a "listen close" event from an event handler, after the teardown started.
2. Try to add a child process to handle the event. This would block because we were in the teardown.
3. In the teardown, try to unregister the event handler and deadlock
I've now:
* Removed the teardown.
* Switched to a single event loop.
Ideally, we'd remove goprocess entirely. But we'd need to refactor natmgr.
fixes #933

fix: avoid a close deadlock in the natmanager

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

This patch fixes several address advertisements bugs that slipped through into go-ipfs 0.6.0.
* Fallback on advertising all interface addresses if looking up the default route fails (#973).
* Don't ever advertise unspecified addresses, even if our NAT lies to us.
* Resolve addresses before trying to lookup observed addresses.
We _really_ need tests for this code, but that will likely require some mocking.

Fix address advertisement bugs

---

config/config.go
p2p/host/basic/basic_host.go

Consider the following scenario:
peers deployed on a cloud server, which may **provides an elastic ip** accessible to the public network, but **not have an external network card**, so net.InterfaceAddrs() can't get the public ip [(call by InterfaceMultiaddrs for get addresses associated with host)](https://github.com/multiformats/go-multiaddr-net/blob/f512d0e050a043c10980e1a6c9a9ffd726572184/net.go#L382)
**The host can indeed be dialed by autonat public addr, but lost the public addr to announce!**

fix host can be dialed by autonat public addr, but lost the public addr to announce

---

p2p/host/basic/basic_host.go

Previously, we'd construct addresses like `/ip4/.../udp/...` instead of `/ip4/.../udp/.../quic` because we'd use mapped addr (ip + transport + port) instead of the full external address (ip + transport + port + other transports...).

fix: use the correct external address when NAT port-mapping

---

p2p/discovery/mdns.go

I want to have P2P communication fully based on IPv6, with local discovery using mDNS.
I am a beginner with libp2p so don't hesitate to bring your insights.

Added parsing of IPv6 addresses for incoming mDNS requests

---

options_filter.go
options_test.go

Fixed bug for inbound connections gated by the deprecated filter option

---

.codecov.yml
go.mod
go.sum
p2p/net/conngater/conngater.go
p2p/net/conngater/conngater_test.go

Basic Connection Gater Implementation

---

go.mod
go.sum
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_notif_test.go
p2p/net/mock/mock_peernet.go
p2p/protocol/identify/id.go

Depends on https://github.com/libp2p/go-libp2p-core/pull/172.

use a context when opening streams

---

libp2p.go
p2p/host/basic/basic_host.go

For https://github.com/libp2p/go-libp2p/issues/1030.

Close peerstore and document Host Close

---

config/config.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

fix https://github.com/ipfs/go-ipfs/issues/7947
move `BasicHost.AutoNat` to a private field (it has no public method and shouldn't be accessed afaik.
Instead add a setter for config that sets it while holding the address mutex to prevent reads of the
field at the same time.

fix autonat race

---

config/config.go
go.mod
go.sum
options.go
p2p/discovery/mdns.go
p2p/host/basic/basic_host.go
p2p/host/relay/addrsplosion.go
p2p/host/relay/autorelay.go
p2p/host/relay/autorelay_test.go
p2p/host/relay/log.go
p2p/host/relay/relay.go
p2p/host/routed/routed.go
p2p/net/conngater/conngater.go
p2p/net/mock/mock.go
p2p/net/mock/mock_net.go
p2p/net/mock/mock_test.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_delta.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/peer_loop.go
p2p/protocol/ping/ping.go
p2p/test/backpressure/backpressure_test.go
p2p/test/reconnects/reconnect_test.go

various fixes for staticcheck
For context: https://github.com/protocol/.github/issues/41

static check fixes

---

p2p/host/basic/basic_host_test.go

1. Don't write "nil". Not all writers handle this well.
2. Write/read an entire string.
3. Improve debuggability.
4. Move the sleep. We _don't_ need to wait for disconnect notifications. We _do_ need to wait for the protocol event change to propagate.

test: deflake TestProtoDowngrade

---

p2p/host/basic/basic_host.go

Unfortunately, lotus relies on this and we don't have a good alternative at the moment.
1. The "correct" way to get the status is to subscribe to the "discoverability" events and read the first event (you're guaranteed to see a "current status" event). However, this is a bit annoying.
2. Ideally, you'd call host.Addrs() to get the list of "good" addresses. Unfortunately, we don't feed enough information back into the Host from AutoNAT for this to be truly useful (yet).

fix: re-expose AutoNAT service on BasicHost

---

.github/ISSUE_TEMPLATE/release.md

1. Don't bother with making a release branch. We don't have enough changes being merged to master to need one.
2. Remove preload, hydra, filecoin, etc. infra testing. This really isn't necessary for a libp2p release.
3. Note that the release process should be updated post release.

doc: update the release process after running through it

---

options.go

Otherwise, it's completely undiscoverable.

doc: document standard connection manager

---

codecov.yml

No need for a special config here. Our default config should be sufficient.

remove Codecov config

---

.github/workflows/interop.yml
.github/workflows/upstream.yml

Add tests to link in new libp2p release in upstream repos and interop tests. This way, we'll very quickly know if something is broken.
Known issues:

feat: add upstream & interop tests

---

p2p/protocol/identify/obsaddr_test.go

I might be missing something here, but it looks like this test doesn't test anything (other than the fact that the code doesn't panic). Doing 10000 operations with a 1ms `time.Sleep` is not such a good idea, as this one test case will take at least 10s.

remove slow ObservedAddrManager test that doesn't test anything

---

p2p/net/mock/mock_test.go

It's probably not worth spending more than a minute on this single test case.

speed up the mock tests

---

go.mod
go.sum

This fixes a backwards incompatible change in a previous version.

chore: update yamux to v0.5.4

---

examples/go.mod
examples/go.sum
examples/ipfs-camp-2019/go.mod
examples/ipfs-camp-2019/go.sum
examples/pubsub/chat/go.mod
examples/pubsub/chat/go.sum
p2p/net/mock/mock_peernet.go

Side A could already be running Identify with side B before B had the
connection in the connsByPeer, this lead to Connectedness returning
NotConnected and Identify failing.

Fix race in adding connections to connsByPeer

---

p2p/host/basic/basic_host.go

`basic_host.background` is used for handling address changed events, but the `node` may be created with `libp2p.NoListenerAddrs`.
the `h.updateLocalIpAddr` is cost a little CPU time.
But I use `NoListenerAddrs` with many (one thousand) tiny test nodes, and all these test nodes communicate with other peers by a  full feature node (by pubsub or relay) in the same process. 
The basic_host.background would use many CPU time and add 1000 useless goroutine in this situatuion.
-------------------------------------------------------------
I'm not sure whether the `network` could do `listen` after `host.background` started.  
So I just keep the background goroutine and skip one round if there hasn't any listener address.

perf/basic_host: Don't handle address change if we hasn't anyone

---

examples/multipro/echo.go
examples/multipro/ping.go

Error assignment fix

---

examples/echo/main.go
examples/echo/main_test.go

If we run the listener async, we might get expected events out of order.

test: fix flaky example test

---

p2p/host/basic/basic_host.go

When i create some `NewStream`
A long time later,GetStreams() resulted many unused stream.
Finnally, I found the cause of the error

fix(basic_host): stream not closed when context done

---

examples/multipro/echo.go
examples/multipro/main.go
examples/multipro/ping.go

Specifically, wait for the handlers to finish printing before exiting.

fix: deflake multipro echo test

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

Fixes https://github.com/libp2p/go-libp2p/issues/1145.

Make BasicHost.evtLocalAddrsUpdated event emitter stateful.

---

config/muxer_test.go
p2p/discovery/mdns_test.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/protocol/ping/ping_test.go
p2p/test/backpressure/backpressure_test.go
p2p/test/reconnects/reconnect_test.go

remove deprecated basichost.New constructor

---

go.mod
p2p/host/relay/autorelay_test.go

It was only detecting Travis anyway. We've run this test on GitHub Actions successfully.

stop using jbenet/go-cienv

---

defaults.go
examples/go.mod
examples/go.sum
examples/ipfs-camp-2019/go.sum
examples/libp2p-host/host.go
examples/pubsub/chat/go.sum
go.mod
go.sum

This means that we'll finally be able to set the QUIC version in go-libp2p as well.

make QUIC a default transport

---

p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

This is part of the ongoing effort to stop using contexts to control shutdowns.
Most importantly, this PR removes a dependency on the swarm's `Process` in https://github.com/libp2p/go-libp2p/blob/fd4d2a47e21fc516dc97fa0077c2b8a87c35d2c3/p2p/protocol/identify/obsaddr.go#L257.

don't use a context for closing the ObservedAddrManager

---

README.md

One can love or hate the Go module proxy, but there's no need to burden go-libp2p users with doing anything out of the ordinary.

remove recommendation about Go module proxy from README

---

config/config.go
p2p/host/relay/autorelay.go

Not a big fan of this change. I'd have preferred to save the `AutoRelay` on the `BasicHost`, but that's not possible (import cycle).

don't use the context to shut down the relay

---

p2p/protocol/circuitv1/relay/relay.go
p2p/protocol/circuitv2/relay/relay.go

On top of #1186 
In both relay v1 and v2 implementations, with a fixed value of 2. The value is purposefully very low, serving as an indicator to distinguish idle connections from connections with hop circuits during connection manager prunes.

Tag relay hops in relay implementations

---

p2p/protocol/circuitv2/client/reservation.go
p2p/protocol/circuitv2/client/reservation_test.go

reject circuitv2 reservations with nonsensical expiration times

---

config/config.go
examples/pubsub/chat/go.sum
go.mod
options.go
p2p/host/autorelay/addrsplosion.go
p2p/host/autorelay/addrsplosion_test.go
p2p/host/autorelay/autorelay.go
p2p/host/autorelay/autorelay_test.go
p2p/host/autorelay/doc.go
p2p/host/autorelay/host.go
p2p/host/autorelay/log.go
p2p/host/autorelay/relay.go

Changes:
- Move the autorelay code to `p2p/host/autorelay`
- Move the host wrapper to the autorelay package.
- Add support for circuitv2 relays
Next steps: refactor the relay discovery logic to support the Flare strategy of an army of relays; this can happen in a subsequent pr, and we can even wait for deployment before we do it.
For now, user must configure relays statically.

autorelay support for circuitv2 relays

---

p2p/protocol/holepunch/coordination_test.go

Fixes https://github.com/libp2p/go-libp2p/issues/1182.

fix flaky TestEndToEndSimConnect holepunching test

---

p2p/host/basic/basic_host_test.go

Fixes #1094.
The problem here is that we're dialing a TCP and QUIC connection simultaneously. Occasionally, the timing works out such that the dial limiter kills the QUIC connection right after it has been dialed: https://github.com/libp2p/go-libp2p-swarm/blob/88ef86a16cf0bbc451c3799f63278d345aaf56ea/limiter.go#L228-L234.
From the other host's side (acting as the the QUIC server), this connection looks like a fully functioning connection, and it will happily open a stream on this connection, just to learn a moment later that the connection is getting closed, resulting in the errors we're seeing.
The fix is to have the host that dialed the connect (i.e. the QUIC client) open the stream. This PR therefore swaps the roles of stream initiator / receiver in most tests.

fix flaky BasicHost tests

---

config/reflection_magic.go
config/transport_test.go

We use them for "options". Ideally we'd be able to forward options through, but that would require real dependency injection.

fix: skip variadic params in constructors

---

examples/go.sum
examples/ipfs-camp-2019/go.mod
examples/ipfs-camp-2019/go.sum
examples/pubsub/chat/go.sum
go.mod
go.sum
p2p/protocol/holepunch/coordination_test.go

We need this version so we can use the assigned roles (client, server) during simultaneous open.

chore: update go-tcp-transport to v0.3.0

---

p2p/protocol/identify/id_glass_test.go

fix flaky TestFastDisconnect identify test

---

config/config.go
examples/pubsub/chat/go.sum
options.go
p2p/host/basic/basic_host.go
p2p/host/relaysvc/relay.go

I'm not satisfied with the names for the config options, but I struggle to come up with something better. Suggestions would be highly appreciated.
I wish we could use `EnableRelay()` here, but unfortunately this is already taken to enable the *relay transport*.

add an option to start the relay v2

---

config/reflection_magic.go
config/transport.go
config/transport_test.go
options.go

Background: The libp2p constructor uses reflection magic to figure out the arguments that a `Transport` requires. This allows us to write
```go
host, err := libp2p.New(
libp2p.Transport(tcp.NewTCPTransport),
libp2p.Transport(quic.NewTransport),
)
```
even though the TCP and the QUIC constructor have completely different signatures.
https://github.com/libp2p/go-tcp-transport/pull/99 now adds TCP options as variadic parameters to the TCP constructor. #1204 added a fix to simply ignore all variadic parameters, making it possible to merge the PR in the TCP repository, but leaving us unable to actually use these options.
This PR now makes it possible to use the option. For example, you can now write
```go
host, err := libp2p.New(
libp2p.Transport(tcp.NewTCPTransport, tcp.DisableReuseport(), …
```

make it possible to pass options to a transport constructor

---

p2p/protocol/identify/id.go

close the ObserverAddrManager when the ID service is closed

---

p2p/test/backpressure/backpressure_test.go

Fixes #1209.
The bug here is the same one we fixed for the `BasicHost` tests in #1202.

fix flaky TestStBackpressureStreamWrite test

---

config/config.go
options.go
p2p/host/autorelay/autorelay.go

Static relays don't have any use outside of `AutoRelay`. We can clean up our config options a bit by making it an option to `EnableAutoRelay`, instead of its own option.

pass static relays to EnableAutoRelay, deprecate libp2p.StaticRelays and libp2p.DefaultStaticRelays

---

p2p/host/autorelay/autorelay.go
p2p/host/autorelay/autorelay_test.go

This refactor introduces 3 improvements:
* fixes a long-standing TODO to run relay discovery in a separate Go routine, thereby not blocking the main loop for up to 2.5 minutes at a time
* we now use the `EvtPeerConnectednessChanged` to detect disconnects from relays
* we immediately acquire a reservation if we detect that we connect to a static relay (before we'd have to wait until the refresh timer triggered a refresh of relays), thereby deflaking the [0182 sharness test in go-ipfs](https://github.com/ipfs/go-ipfs/blob/master/test/sharness/t0182-circuit-relay.sh)

refactor the AutoRelay code

---

p2p/host/basic/basic_host.go
p2p/protocol/holepunch/coordination.go
p2p/protocol/holepunch/coordination_test.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_delta.go
p2p/protocol/identify/id_push.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/peer_loop.go

If we don't have any public addresses, the hole punch attempt is bound to fail - there's no address that can be used to dial us.
Question: Any idea how to fix the tests? `IDService.OwnObservedAddrs()` always returns an empty set of addresses, as we're not really running the ID protocol (and we're only listening on localhost anyway). The obvious solution would be to mock the `IDService`, but it's not an interface.

reject hole punching attempts when we don't have any public addresses

---

p2p/protocol/identify/obsaddr.go

Closes #1252.
When using AutoRelay, we set the `AddrsFactory` such that the listening addresses are not part of `host.Addrs()` any more. When connecting to the relay server, we get one of our "public" (though not dialable) addresses, which we need for coordinating the hole punch.

identify: also match observed against listening addresses

---

examples/go.sum
examples/ipfs-camp-2019/go.mod
examples/ipfs-camp-2019/go.sum
examples/pubsub/chat/go.sum
go.mod
go.sum

This should be all the deps we need for v0.17.0 (unless we want to get the mplex fix in).

chore: update deps

---

examples/pubsub/chat/go.sum
go.mod
p2p/net/mock/interface.go
p2p/net/mock/mock.go
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_link.go
p2p/net/mock/mock_net.go
p2p/net/mock/mock_notif_test.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_test.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/obsaddr_test.go

That was the last place we used goprocess in libp2p.

remove goprocess from the mock package

---

examples/go.mod
examples/go.sum
examples/ipfs-camp-2019/go.mod
examples/ipfs-camp-2019/go.sum
examples/pubsub/chat/go.sum
go.mod
go.sum
p2p/host/basic/basic_host.go

Part of our move to deprecate this repo.
Full deprecation will require us to update go-libp2p-swarm here (which will happen with the rcmgr changes).

remove direct dependency on libp2p/go-addr-util

---

options.go

Fixes a typo while I was looking over docs  :+1:

Fix typo in options.go

---

config/config.go
options.go

Depends on https://github.com/libp2p/go-libp2p-swarm/pull/302.

add an option for the swarm dial timeout

---

p2p/net/mock/mock_test.go

fix flaky TestStreamsStress test

---

p2p/host/autorelay/autorelay_test.go

speed up the autorelay test, fix flaky TestAutoRelay test

---

go.mod
go.sum
p2p/net/mock/mock_net.go
p2p/protocol/identify/obsaddr_test.go

Depends https://github.com/libp2p/go-libp2p-netutil/pull/60 and https://github.com/libp2p/go-libp2p-testing/pull/45.

use the netutil package that was moved to go-libp2p-testing

---

p2p/protocol/identify/id.go

This is obviously very important once the rcmgr is used. This PR also cleans up some rather messy `defer` logic that was used for error handling.

don't close the connection when opening the identify stream fails

---

p2p/protocol/identify/id_test.go

These changes reduce the execution time of identify tests from 30s to 13s.

speed up identify tests

---

go.mod
go.sum
p2p/net/connmgr/bench_test.go
p2p/net/connmgr/connmgr.go
p2p/net/connmgr/connmgr_test.go
p2p/net/connmgr/decay.go
p2p/net/connmgr/decay_test.go
p2p/net/connmgr/options.go
p2p/net/connmgr/watchdog_cgo.go
p2p/net/connmgr/watchdog_no_cgo.go

This is easy, as go-libp2p doesn't yet depend on this package yet.
We will initialize a default connection manager in an upcoming PR very soon though.

move the go-libp2p-connmgr here

---

itest/echo.go
itest/echo_test.go
itest/rcmgr_test.go

Basic resource manager integration tests

---

p2p/protocol/identify/id.go
p2p/protocol/identify/peer_loop.go

This avoids stream storms that can clog the transient scope when we have a largish number of peers.

add semaphore to control push/delta concurrency

---

go.mod
go.sum
version.json

Dependencies:
- https://github.com/libp2p/go-libp2p-transport-upgrader/pull/104
- https://github.com/libp2p/go-libp2p-resource-manager/pull/9

update deps, fixing nil peer scope pointer issues in connection upgrading

---

itest/echo.go
itest/rcmgr_test.go

fix flaky resource manager tests

---

examples/relay/main_test.go

Fixes #1158.
Yet another flaky test due to multiple connections being established at the same time (see https://github.com/libp2p/go-libp2p/issues/1158 for a more detailed description).

disable flaky relay example test on CI

---

itest/rcmgr_test.go

deflake resource manager tests, take 2

---

p2p/host/autorelay/autorelay_test.go

fix flaky TestAutoRelay test

---

.github/actions/go-test-setup/action.yml

This will prevent quic-go from spamming our logs with
```
2022/02/07 05:44:20 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

increase the UDP receiver buffer size on CI

---

p2p/discovery/backoff/backoffconnector_test.go

fix flaky TestBackoffConnector test

---

p2p/discovery/mdns/mdns.go

`manet.DialArgs` returns `ip{4,6}` for `/dns` addresses. The address returned in that case is a domain name, not an IP address, which would make our zeroconf implementation throw up.

fix parsing of IP addresses for zeroconf initialization

---

p2p/discovery/backoff/backoffconnector_test.go

fix flaky BackoffConnector test

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

BasicHost.NewStream will try to establish a connection if one doesn't already exist.  This will fail if the destination host's addresses have not yet been resolved.  This PR resolves the destination host's addresses before creating the stream and possible new connection.
Fixes #1302

Resolve addresses when creating a new stream

---

examples/http-proxy/proxy.go

fix go vet error in proxy example

---

p2p/host/autorelay/relay_finder.go

fix race condition in AutoRelay candidate handling

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_go117.go
p2p/protocol/identify/id_go118.go

For example, when built as a go-ipfs dependency, this would be: `github.com/ipfs/go-ipfs@dfd01b1e1e8d31b148290e2b5dd51b7a676605fe (dirty)`.

use the vcs information from ReadBuildInfo in Go 1.18

---

p2p/host/autorelay/autorelay_test.go
p2p/host/autorelay/options.go
p2p/host/autorelay/relay_finder.go
p2p/protocol/holepunch/holepunch_test.go

Circuit v1 support is disabled by default. It can be reenabled using the `WithCircuitV1Support` option, and it is expected that go-ipfs will do that when static relays are in use.

improve AutoRelay v1 handling

---

p2p/test/reconnects/reconnect_test.go

Fixes #1386. The old test was way too complicated, and a major source of flakiness.
Review tip: Ignore the git diff. Just review the new code, it's a complete rewrite anyway.

rewrite the reconnect test

---

p2p/host/autorelay/relay_finder.go

We didn't have any protection against multiple go routines running `handleNewCandidate` in parallel. This could lead to an oversubscription to relays if both relays accept the connection.

make sure to not oversubscribe to relays

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature.md

Update the issue templates to direct to https://github.com/libp2p/specs for general ideas concerning libp2p.
Discussed in https://github.com/libp2p/rust-libp2p/pull/2611#discussion_r846418526.

redirect to libp2p/specs for general libp2p ideas

---

p2p/test/reconnects/reconnect_test.go

Fixes #1405.
https://github.com/golang/go/issues/50254 is coming back to bite us. Again.

fix flaky reconnect test

---

p2p/host/basic/basic_host.go

When a host is closed, it should close its resource manager.  Otherwise, goroutines are leaked.
Generally this is not a problem when a host exists for the life of a program, but can be a problem if hosts are created and closed.

Close resource manager when host closes

---

config/transport_test.go
defaults.go
go.mod
libp2p_test.go
p2p/net/swarm/dial_worker_test.go
p2p/net/swarm/testing/testing.go
p2p/protocol/circuitv2/relay/relay_test.go
p2p/transport/tcp/metrics.go
p2p/transport/tcp/metrics_darwin.go
p2p/transport/tcp/metrics_general.go
p2p/transport/tcp/metrics_linux.go
p2p/transport/tcp/metrics_windows.go
p2p/transport/tcp/reuseport.go
p2p/transport/tcp/tcp.go
p2p/transport/tcp/tcp_test.go

move go-tcp-transport here

---

p2p/net/swarm/swarm_test.go

Fixes #1419.
The peer's resource manager is blocking any new stream. Depending on how quickly we receive the stream reset, it surfaces either during the `Write` or the `Read` call.
The problem with repo consolidation is that you're also consolidating all the flaky tests...

fix flaky TestResourceManagerAcceptStream test

---

defaults.go
go.mod
go.sum
p2p/transport/websocket/LICENSE-APACHE
p2p/transport/websocket/LICENSE-MIT
p2p/transport/websocket/addrs.go
p2p/transport/websocket/addrs_test.go
p2p/transport/websocket/conn.go
p2p/transport/websocket/listener.go
p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go

move go-ws-transport here

---

libp2p_test.go

Fixes #1170.
This test is flaky *by design*: There's half a RTT between a connection is fully set up on one host and the other, so closing the connection right away will occasionally lead to "connection reset by peer" errors.
TCP Simultaneous Connect should (and is) tested in the swarm.

remove flaky TestTcpSimultaneousConnect

---

config/muxer_test.go
defaults.go
go.mod
p2p/muxer/yamux/conn.go
p2p/muxer/yamux/stream.go
p2p/muxer/yamux/transport.go
p2p/muxer/yamux/transport_test.go
p2p/net/swarm/dial_worker_test.go
p2p/net/swarm/testing/testing.go

move go-libp2p-yamux here

---

p2p/net/swarm/swarm_test.go

If the stream was canceled, QUIC will return an error when calling Close.

swarm: don't check return value of str.Close in TestResourceManager

---

go.mod
p2p/transport/tcp/tcp_test.go
p2p/transport/websocket/websocket_test.go

mplex makes the test flakies, but randomly resetting streams. It's just what mplex does and what we hate it for so passionately.

use yamux instead of mplex in tests

---

go.mod
go.sum
p2p/muxer/mplex/conn.go
p2p/muxer/mplex/stream.go
p2p/muxer/mplex/transport.go
p2p/muxer/mplex/transport_test.go

move go-libp2p-mplex here

---

config/security.go
go.mod
p2p/net/conn-security-multistream/ssms.go
p2p/net/conn-security-multistream/ssms_test.go
p2p/net/swarm/dial_worker_test.go
p2p/net/swarm/testing/testing.go
p2p/transport/tcp/tcp_test.go
p2p/transport/websocket/websocket_test.go

move go-conn-security-multistream here

---

config/config.go
go.mod
go.sum
p2p/net/swarm/dial_worker_test.go
p2p/net/swarm/testing/testing.go
p2p/net/upgrader/conn.go
p2p/net/upgrader/gater_test.go
p2p/net/upgrader/listener.go
p2p/net/upgrader/listener_test.go
p2p/net/upgrader/threshold.go
p2p/net/upgrader/upgrader.go
p2p/net/upgrader/upgrader_test.go
p2p/transport/tcp/tcp.go
p2p/transport/tcp/tcp_test.go
p2p/transport/websocket/websocket_test.go

move go-libp2p-transport-upgrader here

---

p2p/net/mock/mock_net.go
p2p/protocol/identify/obsaddr_test.go

The performance impact of key generation should be negligible. This will allow us to deprecate go-libp2p-testing/netutil entirely. Security-wise, eliminating a way to generate fake keys is a win as well.

use real keys in tests instead of go-libp2p-testing/netutil fake keys

---

p2p/protocol/holepunch/holepunch_test.go
p2p/protocol/holepunch/holepuncher.go

Fixes #1477.
This is **bad**. We'll need to backport this and release v0.19.2.

holepunch: fix incorrect message type for the SYNC message

---

p2p/transport/quic/conn_test.go

Unfortunately, this uses an unexported member variable, but the only option is a long timeout.

quic: deflake the holepunching test

---

p2p/transport/quic/reuse_test.go

quic: adjust timeout for reuse garbage collector detection in tests

---

p2p/net/swarm/dial_sync_test.go

Fixes #1489.
The counter needs to be compared and incremented atomically, otherwise it might be 0 for both calls to `Dial`.

swarm: fix race condition in TestFailFirst

---

p2p/transport/tcp/tcp_test.go
p2p/transport/testsuite/stream_suite.go
p2p/transport/testsuite/transport_suite.go
p2p/transport/testsuite/utils_suite.go
p2p/transport/websocket/websocket_test.go

merge the transport test suite from go-libp2p-testing here

---

p2p/security/tls/transport_test.go

tls: fix flaky handshake cancelation test

---

itest/rcmgr_test.go
p2p/net/connmgr/decay_test.go
p2p/transport/quic/reuse_test.go

As pointed out by @MarcoPolo in https://github.com/libp2p/go-libp2p/pull/1486#issuecomment-1128108298.

increase overly short require.Eventually intervals

---

p2p/transport/testsuite/stream_suite.go
p2p/transport/testsuite/utils_suite.go

Fixes #1498
Reduces the 50 conn test to 5 conns. Then runs the 50 conn test on linux only. See the linked issue for more context.

tcp: limit the number of connections in tcp suite test on non-linux hosts

---

p2p/net/swarm/dial_test.go

Fixes #1504.
Our good old friend, the simultaneous establishment of a TCP and a QUIC connection again...

swarm: fix flaky TestDialExistingConnection test

---

go.mod
p2p/net/reuseport/dial.go
p2p/net/reuseport/listen.go
p2p/net/reuseport/multidialer.go
p2p/net/reuseport/reuseport.go
p2p/net/reuseport/reuseport_plan9.go
p2p/net/reuseport/reuseport_posix.go
p2p/net/reuseport/reuseport_test.go
p2p/net/reuseport/singledialer.go
p2p/net/reuseport/transport.go
p2p/net/reuseport/transport_test.go
p2p/transport/tcp/tcp.go

move go-reuseport-transport here

---

p2p/transport/quic/conn_test.go

Fixes #1492.
I struggled to reproduce this in any environment. A QUIC handshake is mildly expensive, I can accept that it occasionally takes longer than 100ms on CI.

quic: increase timeout in hole punching test

---

p2p/protocol/identify/id_test.go

Fixes #1497 by removing the sleeps/waits. In general, sleeps will cause flakiness in CI so anyway we can completely avoid them will let our tests be more resilient to exogenous performance impacts.
This doesn't remove all the sleeps in this file. But if this looks good I can remove the other cases as well.

identify: fix flaky tests

---

p2p/discovery/backoff/backoffcache.go
p2p/discovery/backoff/backoffcache_test.go
p2p/discovery/mocks/mocks.go
p2p/discovery/routing/routing_test.go

Fixes #1502 by introducing a mocked clock. Time can be incremented in the mock clock and things check the clocks time via `.Now()`. If no clock is passed in, the default realClock uses `time.Now`
This means that these tests are not dependent on actual wall clock times, but our monotonically increasing mock clock.
This PR also fixes a subtle bug that would cause the limit of a `sendingChs` to be ignored. And a bug that prevented other `sendingChs` from getting sent data.

backoff: fix flaky tests in backoff cache

---

p2p/net/swarm/dial_worker_test.go

swarm: only dial a single transport in TestDialWorkerLoopBasic

---

scripts/mkreleaselog

fix: mkreleaselog exclude autogenerated files

---

p2p/net/swarm/dial_worker_test.go

This tests now completes in 2s (= 2 dial timeouts) instead of 25s.

swarm: speed up the TestDialWorkerLoopConcurrentFailureStress test

---

p2p/net/connmgr/decay_test.go

I haven't been able to reproduce #1369. And this test already uses a mock clock. I'm adding this assertion with the hope that maybe it helps debug this issue in the future.

connmgr: Add sanity check to test

---

p2p/host/autorelay/autorelay.go

I got this error from go-ipfs (probably because I put my laptop to sleep?) but I couldn't get any details.

chore: log autorelay start failure error

---

p2p/security/tls/transport_test.go

Fixes https://github.com/libp2p/go-libp2p/issues/1529.
The amount of trivial things that simply don't work reliably on Windows is mind blowing. Absolutely incredible.
This PR should not work around those and make the TLS tests pass on Windows.

tls: fix flaky TestInvalidCerts on Windows

---

p2p/protocol/identify/id_test.go

Fixes #1575 
We can get events happening as soon as we connect and if we subscribe after we started the connection, then we could miss these events.
Repro'd this issue by sleeping for 2 seconds after starting the connection. That caused the test to fail since the event already happened.

identify: fix flaky TestIdentifyDeltaOnProtocolChange (again)

---

p2p/host/basic/basic_host_test.go

Fixes #1528. The fix here is to increase the timeout.

basichost: fix flaky TestSignedPeerRecordWithNoListenAddrs

---

p2p/host/pstoremanager/pstoremanager_test.go

Fixes #1585 by actually making sure the event is sent before we close, instead of waiting and expecting the event to be sent by then.

pstoremanager: fix test timeout

---

p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_test.go

Recreating https://github.com/libp2p/go-libp2p-swarm/pull/319.
Add the missing `ListenClose` method, as it is impossible to close existing listeners.
Useful in many situations, especially on systems that no longer handle listeners after the operating system has suspended them without closing them, when applications run in the background for example (iOS).
This offers the possibility to update the network listener without completely restarting the swarm.
I think this method should also be added to the network interface.
The decision is yours

swarm: add ListenClose

---

p2p/host/basic/natmgr.go

fix natManager to close natManager.nat

---

p2p/transport/websocket/websocket.go

fixes #1593
This fixes an issue where the WSS dialer can only handle IP multiaddrs not DNS https://github.com/libp2p/go-libp2p/blob/d7ba37217c6f1a0d739666f78ac19a87728a7280/p2p/transport/websocket/websocket.go#L26
A couple areas to consider here for improvement (recommendations or maintainers pushing commits to this PR are welcome).

feat: allow dialing wss peers using DNS multiaddrs

---

p2p/muxer/mplex/conn.go
p2p/muxer/mplex/transport.go
p2p/muxer/yamux/conn.go
p2p/muxer/yamux/transport.go

Expose a function to create a MuxedConn from the base type: if a user has a *mp.Multiplex or a *yamux.Session, they should be able to construct the libp2p wrapper without going through the Transport interfaces.

muxer: expose func to create MuxedConn from backing Conn

---

go.mod
go.sum

Update github.com/multiformats/go-multistream version to include fix: https://github.com/multiformats/go-multistream/releases/tag/v0.3.2

chore: update github.com/multiformats/go-multistream to v0.3.2

---

p2p/transport/tcp/tcp.go

All that users care about is that the transport constructed is a `tpt.Transport`, they don't care about the (incorrectly capitalised) `TcpTransport`.
This PR doesn't solve any particular issue, but it's part of a cleanup of our exposed API. As a reference point, the QUIC transport doesn't expose any transport either.

tcp: unexport TcpTransport.Upgrader

---

go.mod
go.sum
p2p/net/swarm/addrs.go

This allows us to ditch `github.com/whyrusleeping/multiaddr-filter`.
In draft until we have a new go-multiaddr release.

use multiaddr ipcidr to parse multiaddr filters

---

go.mod
go.sum
p2p/net/upgrader/upgrader.go
p2p/security/noise/transport.go
p2p/security/tls/transport.go

Adds logging when a peer fails our security handshake or fails to setup a muxer

logging: Add canonical log for misbehaving peers

---

p2p/host/basic/basic_host_test.go
p2p/net/swarm/swarm_dial.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

No functional change expected, but this is removing 67 LoC. DRY!

chore: use the new multiaddr.Contains function

---

go.mod
go.sum

Update github.com/multiformats/go-multistream version to include fix: https://github.com/multiformats/go-multistream/releases/tag/v0.3.3
I can cherry pick this into the release-branch-v020 when this is approved and release a new patch release.

chore: update github.com/multiformats/go-multistream to v0.3.3

---

p2p/protocol/ping/ping_test.go

Fixes #1616.
If we end up with 2 connections (TCP and QUIC) between the nodes, the dialing node might close one of those connection.
This will cause a stream reset on the connection that the dialed node might have chosen for its ping stream.

ping: fix flaky test

---

p2p/net/swarm/swarm_dial.go

The previous location would prevent explicit calls to `Connect`, but not implicit connections on `NewStream`. Given that the host calls `Connect` before calling `NewStream`, it's unclear whether or not this would likely be triggered by user code, but we still need to fix it.

fix: deny connections to peers in the right place

---

defaults.go
go.mod
go.sum
limits.go
p2p/test/resource-manager/rcmgr_test.go

Depends on https://github.com/libp2p/go-libp2p-resource-manager/pull/48.

rcmgr: use autoscaling limits

---

p2p/net/swarm/dial_worker.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go

Otherwise, we can return, e.g., a transient connection that can't actually be used.
I noticed bitswap was trying to use transient connections, which shouldn't be possible. To really fix this issue, we'd also need to fix #1603 as well, but that's harder.

fix: return the best _acceptable_ conn in NewStream

---

p2p/host/routed/routed.go

A circuit multiaddr contains an encoded multiaddr, so we need to decode it: https://github.com/libp2p/specs/tree/master/addressing#p2p-circuit-relay-addresses
Not 100% sure that this is correct, please review carefully.

routedhost: fix decoding of relay peer ID

---

go.mod
go.sum

* Upgrades rcmgr and core by a patch release
* Dowgrades grpc indirect dep to avoid breaking downstream users unnecessarily (see: https://github.com/weaveworks/common/issues/239)
* removed btcd dep

chore: update core dep

---

p2p/net/swarm/swarm_dial.go

This is probably an insufficient change, given how many WebTransport nodes we'll see coming up once we enable it by default. But it's better than nothing.

swarm: mark dialing WebTransport addresses as expensive

---

go.mod
go.sum

We now use the go dev's version, which is faster. Unfortunately, minio's sha256 implementation is still significantly faster than the built-in version, so we can't drop that yet.
part of #1646

chore: update go-multihash to remove blake2b-simd dep

---

p2p/security/noise/handshake.go

On my 11th gen Intel laptop, this library is 3x faster than the default
one (and is the one we use in go-multihash).
See below (GEN_ is the builtin version, SHA_ is this library).
BenchmarkHash/SHA_/8Bytes-8           94.31 ns/op	  84.82 MB/s
BenchmarkHash/SHA_/1K-8               926.9 ns/op	1104.74 MB/s
BenchmarkHash/SHA_/8K-8                6793 ns/op	1205.98 MB/s
BenchmarkHash/SHA_/1M-8              883694 ns/op	1186.58 MB/s
BenchmarkHash/SHA_/5M-8             4347298 ns/op	1206.01 MB/s
BenchmarkHash/SHA_/10M-8            8810864 ns/op	1190.09 MB/s
BenchmarkHash/GEN_/8Bytes-8           283.2 ns/op	  28.25 MB/s
BenchmarkHash/GEN_/1K-8                3587 ns/op	 285.48 MB/s
BenchmarkHash/GEN_/8K-8               27706 ns/op	 295.68 MB/s
BenchmarkHash/GEN_/1M-8             3414827 ns/op …

feat: switch noise to use minio's SHA256 implementation

---

go.mod
go.sum
p2p/protocol/ping/ping.go

1. We shouldn't use time-seeded random numbers. They contain very, very little entropy.
2. We only need to initialize a `math/rand` random number generator once per `Ping` invocation.
3. We don't need to use `go-ipfs-util` for this, bringing down the number of dependencies (therefore: part of #1646).

ping: optimize random number generation

---

.github/workflows/interop-test.yml

Add a workflow that calls the testground interop testing on every push and pull request.
- master: https://github.com/laurentsenta/go-libp2p/runs/7148996579?check_suite_focus=true
- pull request: https://github.com/laurentsenta/go-libp2p/pull/3
- run: https://github.com/laurentsenta/go-libp2p/runs/7149039457?check_suite_focus=true
- note the `GitReference=d9f4b4447188fafe7c15b66b70d98b0ba6e0eeb6 GitTarget=github.com/laurentsenta/go-libp2p` parameters in "Run the composition file" job.
- pull request that breaks the ping service: https://github.com/laurentsenta/go-libp2p/pull/4
- run: https://github.com/laurentsenta/go-libp2p/runs/7149252149?check_suite_focus=true
- note the `protocol not supported` errors
- This PR will work with local branches & forks, but it will test the latest commit …

ci: run testground:ping plan on pull requests

---

p2p/security/tls/crypto.go
p2p/security/tls/crypto_test.go
p2p/security/tls/transport_test.go

This PR was originally opened here https://github.com/libp2p/go-libp2p-tls/pull/99 and relates to this issue: fixes https://github.com/libp2p/go-libp2p/issues/1538
`libp2ptls.NewIdentity` generates a new `Identity` which includes an x509 certificate with a special signed extension which ties the TLS key pair to a libp2p network identity. In flow, we use this key pair to secure a gRPC interface which is accessible to nodes on the network as well as external public clients, allowing them to verify that they've connected to the correct staked node.
The current implementation of `NewIdentity` does not support customizing the certificate template, and uses default options that aren't compatible with standard TLS clients (e.g. Subject doesn't include a `cn` field).
This PR refactors …

Support generating custom x509 certificates

---

p2p/net/connmgr/watchdog_cgo.go
p2p/net/connmgr/watchdog_no_cgo.go

Add the ability to disable watchdog even if cgo is enabled.
I logicaly tested the configuration using a truth table to cover each case:
| p | q | p∧¬q | ¬p∨q | (p∧¬q)⊕(¬p∨q) |
|:-:|:-:|:----:|:----:|:-------------:|
| T | T |   F  |   T  |       T       |
| T | F |   T  |   F  |       T       |
| F | T |   F  |   T  |       T       |
| F | F |   F  |   T  |       T       |
**Where**:
- `p`: `cgo` tag
- `q`: `nowatchdog` tag
- `p∧¬q`: `watchdog_cgo.go` compiled if `true`
- `¬p∨q`: `watchdog_no_cgo.go` compiled if `true`
- `(p∧¬q)⊕(¬p∨q)`: only one of these files is compiled if `true`
```shell
$ go build -tags nowatchdog .
```
This fixes an old problem I reported a few months ago: [libp2p/go-libp2p-connmgr#98](https://github.com/libp2p/go-libp2p-connmgr/issues/98).
I couldn't find a …

connmgr: add nowatchdog go build tag

---

p2p/security/noise/crypto_test.go
p2p/security/noise/handshake.go
p2p/security/noise/intermediate_transport.go
p2p/security/noise/session.go
p2p/security/noise/session_transport.go
p2p/security/noise/transport.go
p2p/security/noise/transport_test.go

Allows adding the prologue to an existing noise transport. This is for potential use in implementing the webrtc transport.
Related discussion: https://github.com/libp2p/specs/pull/412#discussion_r931163931

Allow adding prologue to noise connections

---

p2p/host/routed/routed.go
p2p/protocol/holepunch/svc.go

routed: respect force direct dial context

---

examples/pubsub/chat/ui.go

Update ui for example
examples/pubsub/chat/ui.go:125
Remove unneeded lock on peersList textview.
Clear method already has lock.
```golang
// Clear removes all text from the buffer.
func (t *TextView) Clear() *TextView {
t.Lock()
defer t.Unlock()
t.clear()
return t
}
```

examples: fix unresponsive pubsub chat example

---

p2p/host/autorelay/autorelay.go
p2p/host/autorelay/autorelay_test.go
p2p/host/autorelay/options.go
p2p/host/autorelay/relay_finder.go
p2p/host/autorelay/timer.go

Fixes #1569. Fixes #1440. Closes #1577.
Unblocks https://github.com/libp2p/go-libp2p/pull/1576 and https://github.com/libp2p/go-libp2p/pull/1615.

autorelay: poll for new candidates when needed

---

defaults.go

Cryptographically, there's no reason to prefer RSA over Ed25519 (quite the contrary, actually!).
The peer ID spec says that all implementations MUST support Ed25519, so this _should_ be a safe change to make.
@vyzo @Stebalien Are you aware of any backwards compatibility issues this might cause (that wouldn't be better handled by the application that requires backwards compatibility)?

change the default key type to Ed25519

---

p2p/host/autorelay/relay_finder.go
p2p/host/blank/blank.go
p2p/net/mock/mock_peernet.go

Found with https://github.com/alexkohler/prealloc
Make my IDE complain less when I vendor libp2p and probably dirty slightly less memory.

chore: preallocate slices with known final size

---

p2p/host/resource-manager/limit.go
p2p/host/resource-manager/limit_defaults.go
p2p/host/resource-manager/limit_test.go

I'm changing the scale logic to be a bit simpler. The proposed change doesn't subtract 128 MiB before doing the scale logic. This means you can explain the behavior by saying:
"For every GiB of memory allowed we increase the imit by LimitIncrease"
Contrast this with the previous behavior of:
"For every GiB of memory allowed we increase the imit by LimitIncrease, except that we first subtract 128MiB."
The difference is subtle, but I think it's more intuitive. Consider also this graph of the two behaviors:

Resource Manager: Logic changes to make scaling more intuitive

---

p2p/host/resource-manager/README.md

Moves https://github.com/libp2p/go-libp2p-resource-manager/pull/78/files to here.

Update resource manager readme

---

core/crypto/key_not_openssl.go
core/crypto/key_openssl.go
core/crypto/key_test.go
core/crypto/secp256k1.go
go.mod
go.sum

This updates the `core/crypto/secp256k1` code to make use of the `dcrec/secp256k1/v4` module directly instead of using `btcec/v2` which itself is now just a shim around `dcrec/secp256k1/v4` anyway.
This has the benefit of removing the additional transitive `github.com/btcsuite/btcd/chaincfg/chainhash` dependency since `dcrec/secp256k1/v4` is its own module and does not rely on it.
It also updates to the latest `v4.1.0` release which implements direct key generation and has some other nice optimizations that speed up signature verification as compared to the `v4.0.1` release.
---
This was originally opened as libp2p/go-libp2p-core#280 and is being reopened here as requested.
Also, per discussion on the referenced PR, I confirmed that this is actually not a breaking change to the API …

crypto/secp256k1: Remove btcsuite intermediary.

---

.github/workflows/go-crypto.yml
core/crypto/bench_test.go
go.mod
go.sum

crypto: add better support for alternative backends 

---

p2p/transport/quic/conn.go
p2p/transport/quic/conn_test.go
p2p/transport/quic/listener.go
p2p/transport/quic/options.go
p2p/transport/quic/transport.go

Moved from  https://github.com/libp2p/go-libp2p-quic-transport/pull/272
---
Fixes #1428 
Hey, I just started to add the `DisableReuseport` options to quic transport.  It seems to be working as expected with some cellular operators that couldn't maintain the connection (I tried with this script https://github.com/gfanton/libp2p-reuseport-test)
Just some few things:
- It seems that there is no option/configuration mechanism, so I added one. Let me know if you are ok with this or if you want to use another method to pass the argument.
- I wrapped all the `conn_tests` with a simple table test case to test everything conn related with the reuseport_on/off
- I have to use `net.ListenUDP` instead of `net.DialUDP` for the Dial method to work, otherwise the call to the `WriteTo` method fails.
Also …

quic: add `DisableReuseport` option

---

p2p/net/connmgr/connmgr.go
p2p/net/connmgr/connmgr_test.go

This prioritized closing connections with peers that have no active streams. This enables us to prune inactive connections rather than a potentially active but lower value connection.
Removes `SortByValue` and changes `SortByValueAndStreams` to work for both the normal case and the emergency memory free up mode.

connmgr: prefer peers with no streams when closing connections

---

config/config.go
config/constructor_types.go
config/muxer.go
config/reflection_magic.go
config/security.go
config/transport.go
config/transport_test.go
defaults.go

This injects the DNS resolver into transport constructors.

feat: inject DNS resolver

---

defaults.go
libp2p_test.go
p2p/test/resource-manager/echo_test.go
p2p/test/resource-manager/rcmgr_test.go

add default listen addresses for QUIC

---

p2p/transport/quic/options.go
p2p/transport/quic/tracer.go
p2p/transport/quic/transport.go

... and only expose metrics if this option is passed to the constructor.

quic: add a WithMetrics option

---

p2p/transport/quic/tracer.go

See comments for motivation. With the standard buffer size, I'm seeing a ton of syscalls just for writing the qlog file, taking almost as much CPU time as writing QUIC packets to the wire.
This should be ok from a resource perspective, because you wouldn't run with qlogging enabled in production anyway.

quic: increase the buffer size used for encoding qlogs

---

p2p/net/connmgr/connmgr.go
p2p/net/connmgr/connmgr_test.go
p2p/net/connmgr/decay.go
p2p/net/connmgr/options.go

Uses a clock interface rather than real time. This lets tests pass a mock clock.
This also fixes the failing tests here: https://github.com/libp2p/go-libp2p-pubsub/pull/498 because that test is timing sensitive and the connmgr did a good job of keeping the conns below the hi mark. That test also used a mock clock for the decayer, but not for the connmgr which could lead to some weird behavior. The test passes if the same mock clock is passed to both the connmgr and decayer.
Also shaves 3s off our test runtime :)

connmgr: use clock interface

---

.github/ISSUE_TEMPLATE/release.md

If we're cutting more frequent and smaller releases, we need to cut down on the overhead a release is creating.
Most of these changes just reflect what we've been doing (or rather, what we've _not_ been doing) in the past.

simplify the release checklist

---

p2p/host/resource-manager/scope.go
p2p/host/resource-manager/scope_test.go

Fixes #1721 
This changes the code to check for overflows and handle them.
This also adds a special case to check if the limit is MaxInt64 and return early since we assume this is an infinite limit (just to save a big int multiplication).

rcmgr: Fix threshold calculation

---

.github/workflows/interop-test.yml

Update workflows on push & PR:
* `run-ping-interop-cross-version`: runs a Testground interoperability test between multiple versions of go-libp2p, including master, and the current branch (during a pull request)
* `run-ping-interop-cross-implementation`: runs a Testground interoperability test between go-libp2p and rust-libp2p, including master, and the current branch (during a pull request)
We rely on the https://github.com/libp2p/test-plans/ repository to retrieve and run the tests.
Demonstration:
* passing PR: https://github.com/laurentsenta/go-libp2p/pull/6
* breaking PR: https://github.com/laurentsenta/go-libp2p/pull/5

ci: add cross-version interop

---

p2p/security/noise/crypto_test.go
p2p/security/noise/handshake.go
p2p/security/noise/session.go
p2p/security/noise/session_transport.go
p2p/security/noise/transport.go
p2p/security/noise/transport_test.go

This is a new version of #1645, extending the API introduced in #1663. Closes #1645.
Part of #1717.
This PR is a prerequisite for moving go-libp2p-webtransport into this repo.

noise: implement an API to send and receive early data

---

p2p/host/resource-manager/limit_defaults.go

rcmgr: increase default connection memory limit to 32 MB

---

p2p/host/autorelay/autorelay_test.go

autorelay: fix race condition in TestBackoff

---

go.mod
go.sum
p2p/muxer/testsuite/mux.go
p2p/muxer/yamux/conn.go
p2p/muxer/yamux/stream.go
p2p/muxer/yamux/transport.go

Depends on https://github.com/libp2p/go-yamux/pull/100.
Will merge after go-yamux v4 has been released (https://github.com/libp2p/go-yamux/pull/101).

yamux: pass constructors for peer resource scopes to session constructor

---

config/config.go
core/transport/transport.go
go.mod
go.sum
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/net/swarm/dial_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_dial_test.go
p2p/net/swarm/swarm_test.go
p2p/net/swarm/testing/testing.go
p2p/transport/websocket/addrs.go
p2p/transport/websocket/listener.go
p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go

fixes https://github.com/libp2p/go-libp2p/issues/1597
This adds a new Resolver interface that can be optionally implemented by transports. This lets a transport resolve a single multiaddr into many multiaddrs, while still letting the swarm handle concurrency in the actual dialing step.
This PR also fixes secure websockets (wss) by having the websocket transport resolve a multiaddr with a dns hostname and `/wss` into a multiaddr that explictly defines the `sni` component. e.g. converts `/dns4/example.com/tcp/1234/wss` into `/dns4/example.com/tcp/1234/tls/sni/example.com/ws`. This is useful so that when the swarm resolves the dns4 address the websocket transport still has access to the hostname so that it can properly set the SNI. e.g. the swarm converts …

Add Resolver interface to transport

---

p2p/security/noise/handshake.go
p2p/security/noise/transport_test.go

I just realized that the change we introduced in #1728 would preclude us from rolling out the change that @julian88110 is working on (see https://github.com/libp2p/specs/pull/446). This means that this PR must make it into v0.23.0.

noise: don't fail handshake when early data is received without handler

---

p2p/transport/webtransport/listener.go

There's some discussion about the security properties of that check here: https://security.stackexchange.com/questions/115716/is-the-origin-header-really-useful-for-securing-a-websocket.
In the p2p world, we want to have cross-origin WebTransport sessions. In fact, that's the whole point of it!

webtransport: disable HTTP origin check

---

p2p/host/autorelay/autorelay_test.go
p2p/host/autorelay/options.go
p2p/host/autorelay/relay_finder.go

The main point of this is to stop the search when the libp2p stops.
I've added that this *might* be used in the future to notify when AutoRelay is satisfied just to not close any door in the future but havn't implemented anything like that.

autorelay: Add a context.Context to WithPeerSource callback

---

p2p/net/swarm/swarm_addr_test.go
p2p/net/swarm/swarm_transport.go

With WebTransport's `/webtransport/certhash/xyz` addresses, the assumption that the last component of a multiaddr identifies the transport to use for dialing doesn't hold any more.
Note that WebRTC will probably also use the `certhash` multiaddr component to encode its certificate hashes.
This is a draft until we actually move the webtransport transport into this repo (#1737), but I'm asking for reviews nonetheless. Please review carefully, this has the potential to break us in painful ways.

swarm: fix selection of transport for dialing

---

p2p/security/noise/crypto_test.go
p2p/security/noise/handshake.go
p2p/security/noise/session.go
p2p/security/noise/session_transport.go
p2p/security/noise/transport.go
p2p/security/noise/transport_test.go
p2p/transport/webtransport/listener.go
p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

So far, only the client could send early data in its first handshake message, which the server would then receive.
This PR extends the logic, such that the server can now also send early data in its first handshake message.
Needed for https://github.com/libp2p/specs/pull/404#discussion_r968836367. Also needed for https://github.com/libp2p/specs/pull/446, if I understand correctly.

noise: make it possible for the server to send early data

---

p2p/transport/webtransport/cert_manager.go
p2p/transport/webtransport/listener.go
p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

As suggested in https://github.com/libp2p/specs/pull/455.
This PR builds on top #1750. **Please only review the last commit**. I'll rebase this PR once #1750 is merged.

webtransport: move certhash verification to the client

---

p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_dial_test.go

Question: Should we have something similar for WebSocket and TCP?

swarm: skip dialing WebTransport addresses when we have QUIC addresses

---

p2p/transport/webtransport/multiaddr_test.go
p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

The continuation of https://github.com/libp2p/go-libp2p/pull/1719 for webtransport. Fixes #1760

webtransport: add custom resolver to add SNI

---

p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go

It's possible (and common) to have a WebSocket transport without a tls client config. This leads to a nil pointer deref error when we set the ServerName.
This sets a default empty `tlsClientConf` and adds a test case.
Fixes https://github.com/libp2p/go-libp2p/issues/1769

websocket: fix nil pointer in tlsClientConf

---

go.mod
go.sum

I'll cut v0.23.2 once this is merged.

chore: update webtransport-go to v0.1.1

---

p2p/transport/quic/conn_test.go

This reduces the execution time of this test from ~4.6s to ~0.6s on my machine.

quic: speed up the stateless reset test case

---

p2p/transport/webtransport/transport.go

I think we forgot to update this comment after changing the handshake protocol.

webtransport: fix comment in webtransport client auth handshake

---

p2p/host/autorelay/autorelay_test.go

Few failures due to timeout. This simply bumps the timeout in CI.
Previous failures:
* https://github.com/libp2p/go-libp2p/actions/runs/3113398662/jobs/5047981099
* https://github.com/libp2p/go-libp2p/actions/runs/3100214212/jobs/5020238941

autorelay: flaky: bump timeout in CI for flaky test

---

p2p/net/connmgr/decay_test.go

Attempts to workaround flakiness here by increasing timeouts in CI. 
Previous failed runs:
* https://github.com/libp2p/go-libp2p/actions/runs/3114264197/jobs/5049905885#step:24:2854
* https://github.com/libp2p/go-libp2p/actions/runs/3114264197/jobs/5049905982#step:24:2712

connmgr: flaky: bump timeout in CI for flaky test

---

p2p/protocol/circuitv2/client/reservation_test.go

I'm not sure why this causes flakiness. It's pretty rare (2 instances in the last 16 days). But we don't need the resource manager for this test. And the test is checking that there is a specific error condition. So it seems okay (but not ideal) to not use the resource manager here so that we are more likely to see the error we want. Another argument is that this test has nothing to do with the resource manager, and the only reason it was in there originally was for convenience.
Flaky runs:
* https://github.com/libp2p/go-libp2p/actions/runs/3094283154/jobs/5007493400
* https://github.com/libp2p/go-libp2p/actions/runs/3092850661/jobs/5004581612

circuitv2: flaky: don't use rcmgr in this test

---

p2p/transport/quic/reuse_test.go

Increases these timeouts 10x if in CI. We got two failures here were these failed because of the timeout:
* https://github.com/libp2p/go-libp2p/actions/runs/3114377990/jobs/5050146995#step:7:2541
* https://github.com/libp2p/go-libp2p/actions/runs/3114811283/jobs/5051064314#step:7:2541

fix: try increasing timeouts if we're in CI for this test

---

README.md
ROADMAP.md

I took a first stab at our roadmap for the next half a year. This document contains that are specific to the go-libp2p stack. General libp2p project items are listed in the [roadmap in the specs repo](https://github.com/libp2p/specs/blob/master/ROADMAP.md). Sections are in no particular order.
**This document is intended as a conversation starter**. 
I intend to keep this PR open for at least a week to give plenty of time for feedback.

add a roadmap for the next 6 months

---

examples/chat-with-mdns/main.go

Fixes [#1797](https://github.com/libp2p/go-libp2p/issues/1797)
Added if condition to make sure it is not attempting self dial .
Added for loop so that multiple peers can join chat .

examples: connect to all peers in example mdns chat app

---

examples/routed-echo/bootstrap.go

curl -X POST "http://127.0.0.1:5001/api/v0/id
https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-id

ipfs /api/v0/id is post

---

p2p/transport/websocket/addrs.go
p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go

Closes #1829. Fixes a regression in not sending the host header. Sends the host header on WSS dials when an SNI is specified. Also adds a test to verify the host header is seen by the server.
@thibmeu wrote the original patch and I contributed to the test.

websocket: set the HTTP host header

---

ROADMAP.md

* Appendix sorted high -> low priority
* Add ToC
* Add Vision
* Add Benchmarking and Testing section
* reference [test-plans roadmap](https://github.com/libp2p/test-plans/pull/44) and [testground roadmap](https://github.com/testground/testground/pull/1484)
* migrate Future-proof Testing and Future-proof Benchmarking to [libp2p/test-plans roadmap](https://github.com/libp2p/test-plans/pull/56)
* 
* cleanup/reorganize
---
Addresses items in https://github.com/libp2p/go-libp2p/issues/1806#issuecomment-1272113970

roadmap: reorder priority, reorganize sections

---

core/network/rcmgr.go
go.mod
go.sum
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_stream.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial_test.go
p2p/net/upgrader/listener_test.go
p2p/net/upgrader/upgrader.go
p2p/net/upgrader/upgrader_test.go
p2p/protocol/circuitv2/client/reservation_test.go
p2p/protocol/internal/circuitv1-deprecated/dial.go
p2p/transport/quic/transport.go
p2p/transport/tcp/tcp.go
p2p/transport/tcp/tcp_test.go
p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go
p2p/transport/webtransport/conn.go
p2p/transport/webtransport/listener.go
p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

Fixes #1826.
Depends on https://github.com/marten-seemann/webtransport-go/pull/35.

webtransport: use the rcmgr to control flow control window increases

---

p2p/security/noise/benchmark_test.go
p2p/security/noise/pb/payload.pb.go
p2p/security/noise/pb/payload.proto
p2p/security/noise/session.go
p2p/security/noise/transport.go
p2p/security/noise/transport_test.go
p2p/transport/websocket/websocket_test.go
p2p/transport/webtransport/transport.go

Muxer negotiation using early data of Noise handshake. 
This is the Noise implementation of issue #1789

noise: use Noise Extension to negotiate the muxer during the handshake

---

core/peerstore/peerstore.go

Extracting this commit out of #1835, to better preserve history when squashing.

core/peerstore: removed unused provider addr ttl constant

---

core/peerstore/peerstore.go
p2p/host/routed/routed.go
p2p/host/routed/routed_test.go

For context: https://github.com/ipfs/kubo/issues/9264
---
If we cannot connect to a remote host, check if we can find more up-to-date Multiaddresses in the DHT. If we have found at least one additional Multiaddress, attempt to connect again.

routed host: search for new multi addresses upon connect failure

---

p2p/security/tls/crypto.go

The field has been deprecated since Go 1.17.

tls: don't set the deprecated tls.Config.PreferServerCipherSuites field

---

p2p/protocol/ping/ping.go

Changes the ping protocol to close the stream instead of reset the stream when we exit the read/write loop (happens if the peer closes their stream).
This is needed to better interop with the JS client ping implementation. That implementation will write the 32 bytes, then close the write stream, then wait for the response to be read. This is racey since the Go side will reset the stream, so the echoed bytes may have been dropped and will never be received by the JS side. Instead the JS side will see a stream reset and the ping will fail.
Came up after I made js-libp2p-webtransport close its stream after calling `sink`: https://github.com/libp2p/js-libp2p-webtransport/pull/23#discussion_r1012228549 Since I'm using ping as a test this behavior made the ping test flaky.
Afaik there's no way …

protocol/ping: close ping stream when we exit the loop

---

p2p/net/swarm/swarm_dial.go

Commit [`f654b4b`](https://github.com/libp2p/go-libp2p/commit/f654b4bd6970d41737b2098fa0998ca686916118) introduced multiaddress resultion by transport and changed the return value from `goodAddrs` to `resolved`. I guess this should be `goodAddrs` again?
cc @MarcoPolo

swarm: return filtered addrs in addrsForDial

---

p2p/net/connmgr/connmgr.go
p2p/net/connmgr/connmgr_test.go
p2p/net/connmgr/decay.go

Fixes https://github.com/libp2p/go-libp2p/issues/1847 by taking the "segment" lock for the relevant peerInfo we're using. Adds a "bucketsMu" to prevent deadlocks from concurrent processes each getting multiple segment locks (e.g. goroutine 1 takes locks A, then B. goroutine 2 takes locks B, then A. They both get the first lock and are now deadlocked).

fix: connmgr: concurrent map access in connmgr

---

options.go
p2p/host/autorelay/autorelay_test.go
p2p/host/autorelay/relay_finder.go

Fixes https://github.com/libp2p/go-libp2p/issues/1852 by adding guard rails and some more documentation.

fix: autorelay: add some guard rails and docs

---

p2p/security/noise/crypto_test.go
p2p/security/noise/handshake.go
p2p/security/noise/session.go
p2p/security/noise/session_transport.go
p2p/security/noise/transport.go
p2p/security/noise/transport_test.go

Allows the `SecureOutbound` call to be called with an unknown peer ID (empty string). This is required for https://github.com/libp2p/specs/pull/412#discussion_r977698490

noise: add an option to allow unknown peer ID in SecureOutbound 

---

core/protocol/switch.go

This function was deprecated more than half a year ago.

core/protocol: remove deprecated Negotiator.NegotiateLazy

---

options.go
p2p/host/autorelay/options.go

These relays were decomissioned recently.

autorelay: remove the default static relay option

---

options.go
p2p/protocol/holepunch/holepunch_test.go

This option was deprecated in Nov last year. One year should be plenty of time to stop using it.

remove deprecated StaticRelays option

---

p2p/test/webtransport/webtransport_test.go
p2p/transport/websocket/websocket_test.go
p2p/transport/webtransport/cert_manager.go
p2p/transport/webtransport/cert_manager_test.go
p2p/transport/webtransport/crypto.go
p2p/transport/webtransport/crypto_test.go
p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

Closes https://github.com/libp2p/go-libp2p/issues/1824

webtransport: use deterministic TLS certificates

---

p2p/host/resource-manager/limit_defaults.go

ServicePeerDefault wasn't being applied in the Apply method, which led to these limits being 0 instead of mirroring the limits from the Apply call in some usage patterns.

rcmgr: fix missing service peer default in LimitConfig.Apply

---

p2p/security/noise/transport.go
p2p/security/noise/transport_test.go
p2p/security/tls/transport.go
p2p/security/tls/transport_test.go

As the integration test (#1887) has revealed, TLS and Noise both selected the muxer according to the server's preferences, whereas the multistream negotiation selects according to the client's preferences. This PR changes TLS' and Noise's behavior to match the multistream behavior.
Since TLS' ALPN selection algorithm also selects according to the server's preferences, we have to play a little trick to overwrite that behavior.

tls / noise: prefer the client's muxer preferences

---

config/config.go
p2p/net/upgrader/conn.go
p2p/net/upgrader/upgrader.go
p2p/test/muxer-negotiation/muxer_test.go

Fixes #1836. Depends on #1885. Closes #1851. Closes #1840.
The test currently fails since apparently the early muxer negotiation respects the server's preferences, not the client's. We should fix that. Will do in another PR.

add an integration test for muxer selection

---

go.mod
go.sum
p2p/transport/quic/transport.go

In draft until quic-go v0.31.0 is released.
Depends on https://github.com/lucas-clemente/quic-go/pull/3621.

quic: update quic-go to v0.31.0

---

p2p/protocol/holepunch/filter.go
p2p/protocol/holepunch/holepunch_test.go
p2p/protocol/holepunch/holepuncher.go
p2p/protocol/holepunch/svc.go

This PR adds a new option to the holepunch service that allows filtering of multi addresses during the DCUtR protocol.

holepunch: add multiaddress filter

---

go.mod
go.sum

Updates the go-netroute dependency to get this fix: https://github.com/libp2p/go-netroute/pull/26/files.
Fixes #1849 
The sorting of priorities was wrong/incomplete, so we would return the wrong interface to dial out. When a VPN is setup like wireguard, the VPN interface should have higher priority (well technically a smaller number). If we don't check this priority we could try to use the non-VPN interface to dial out and that would fail since the host probably has rules to prevent any packets not sent out over the VPN (to avoid leaks).
By bringing in this fix, we check the priority properly and use the correct (VPN) interface to dial out.

chore: update go-netroute so that we get the correct priority of routes

---

p2p/protocol/circuitv2/client/reservation_test.go

Fixes https://github.com/libp2p/go-libp2p/issues/1816
Fixes https://github.com/libp2p/go-libp2p/issues/1765
Fixes https://github.com/libp2p/go-libp2p/issues/1730
Fixes https://github.com/libp2p/go-libp2p/issues/1668

circuitv2: disable the resource manager in tests

---

config/config.go
core/network/conn.go
options.go
p2p/test/negotiation/muxer_test.go
p2p/test/negotiation/security_test.go

Recreating #1908, which was killed by GitHub (see https://github.com/libp2p/go-libp2p/pull/1908#issuecomment-1322694258).
Fixes #1906.

respect the user's security protocol preference order

---

core/network/conn.go
p2p/net/upgrader/conn.go
p2p/transport/quic/conn.go
p2p/transport/websocket/conn.go
p2p/transport/websocket/listener.go
p2p/transport/websocket/websocket.go
p2p/transport/webtransport/conn.go

Prerequisite for our metrics effort, specifically #1910.

transports: expose the name of the transport in the ConnectionState

---

p2p/security/tls/transport_test.go

Explanation: https://github.com/libp2p/go-libp2p/blob/84ded7d47a74c7bfb8e6e257f32b01ea54ea3ad2/p2p/security/tls/transport_test.go#L289-L291

tls: fix flaky TestHandshakeConnectionCancellations test

---

go.mod
go.sum
p2p/transport/webtransport/conn.go
p2p/transport/webtransport/listener.go
p2p/transport/webtransport/stream.go
p2p/transport/webtransport/transport.go

Not really sure what to do with the error codes here. At some point, we probably should standardize libp2p error codes, and at that point, all the codes we've been using so far will become deprecated, so that we can distinguish between new and legacy nodes.

webtransport: update webtransport-go to v0.3.0

---

p2p/host/resource-manager/limit_defaults.go

We see flakiness in CI because a client will dial with concurrency 8 but the limit on the server is 4 so we get rcmgr failures. We notice this when we have a lot of addrs to dial.
Fixes #1816
Fixes #1765
Fixes #1730
Fixes #1668
(will rebase to master after https://github.com/libp2p/go-libp2p/pull/1881 is merged)

swarm / rcmgr: synchronize the concurrent outbound dials with limits

---

p2p/host/autorelay/autorelay_test.go

autorelay: fix flaky TestReconnectToStaticRelays

---

core/transport/transport.go
p2p/host/autonat/dialpolicy_test.go
p2p/net/swarm/swarm_addr.go
p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_test.go
p2p/net/upgrader/listener.go
p2p/net/upgrader/listener_test.go
p2p/net/upgrader/upgrader_test.go
p2p/transport/quic/cmd/server/main.go
p2p/transport/quic/conn_test.go
p2p/transport/quic/listener.go
p2p/transport/quic/listener_test.go
p2p/transport/quic/transport.go
p2p/transport/quic/virtuallistener.go
p2p/transport/tcp/tcp_test.go
p2p/transport/testsuite/stream_suite.go
p2p/transport/testsuite/transport_suite.go
p2p/transport/websocket/listener.go
p2p/transport/websocket/websocket_test.go
p2p/transport/webtransport/listener.go
p2p/transport/webtransport/transport_test.go

Fixes #1904
Undoes part of the work in https://github.com/libp2p/go-libp2p/pull/1881. The QUIC transport now returns a virtual listener that only handles one QUIC version. If a user then listens on another QUIC version with the same multiaddr, we return another virtual listener that uses the same underlying listener but only advertises the other QUIC version.
This is ready for review, but I see some flakiness in the tests (maybe also from #1905 ) so I'll continue debugging that.

transport.Listener,quic: Support multiple QUIC versions with the same Listener. Only return a single multiaddr per listener.

---

defaults.go

The current behavior in `go-libp2p` is that the transports are provided through `fx` by default when no other options are specified. 
QUIC is listed in the defaults but does not support PSK usage, so creating a new app will always result in an error.
The way that libp2p is currently bootstrapped does not allow for dynamically enabling/disabling transports, so we cannot disable QUIC once it's been provided as a value group.
This PR adds a new default transport option that gets activated when `cfg.Transports == nil && cfg.PSK != nil`. The new option is mutually exclusive with the current one on the condition of `cfg.PSK == nil`.  
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>

use a different set of default transports when PSK is enabled

---

p2p/net/swarm/swarm_addr_test.go
p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

That way, it won't be possible to construct a host with a PSK when WebTransport is enabled. This is desireable since WebTransport doesn't support private network (same as QUIC).

webtransport: add PSK to constructor, and fail if it is used

---

p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

This needs more thought before we enable support.

webtransport: disable support for signed/static TLS certificates

---

.github/workflows/interop-test.yml

https://github.com/libp2p/test-plans/pull/70 broke our CI, since the composition file was moved.

ci: fix path to interop test plan composition file

---

p2p/transport/quic/conn_test.go

Fixes #1913.
The server shouldn't close the connection before the client had the chance to accept it.

quic: fix race condition in TestClientCanDialDifferentQUICVersions

---

p2p/transport/webtransport/transport.go
p2p/transport/webtransport/transport_test.go

This will fix https://github.com/ipfs/kubo/issues/9516 in an easier way than #1960, which might be more appropriate for a patch release.

webtransport: initialize a NullResourceManager if none is provided

---

go.mod
go.sum
p2p/discovery/backoff/backoffconnector.go
p2p/host/peerstore/pstoreds/addr_book.go
p2p/host/peerstore/pstoreds/addr_book_gc.go
p2p/host/peerstore/pstoreds/cache.go

This PR upgrades golang-lru to the generics branch v2.

chore: use generic LRU cache

---

ROADMAP.md

As an early result of the swarm metrics effort (#1910), we've discovered that >80% of the connections that a (full) node on the IPFS network establishes / accepts are QUIC connections. We can expect similar numbers for other libp2p networks that use go-libp2p (and that enabled the QUIC transport).
It therefore makes sense to focus our attention on cutting down roundtrips for QUIC users. This makes sense for multiple reasons:
1. At the risk of stating the obvious, improving the handshake latency for >80% of the connections is more impactful than improving the handshake latency for <20% of the connections.
2. Optimizing the TCP-based handshake by getting rid of the security protocol negotiation reduces the latency of a TCP handshake 4 to 3 RTTs (including Identify in the calculation here), …

roadmap: remove optimizations of the TCP-based handshake

---

.github/actions/go-check-setup/action.yml
.github/workflows/go-check-config.json
core/network/mocks/network.go
go.mod
p2p/host/pstoremanager/mock_peerstore_test.go
p2p/host/pstoremanager/pstoremanager_test.go
p2p/transport/quic/conn_test.go
p2p/transport/webtransport/transport_test.go
tools.go

This will make it easy to accept contributions that change the Protobuf: Since we know they're regenerated and checked on CI, we don't have to worry about incorrect and malicious Protobuf files.

ci: run go generate as part of the go-check workflow

---

p2p/host/resource-manager/limit.go
p2p/host/resource-manager/limit_test.go

Ignoring zero values when marshaling zero values as it's done here https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/limit_defaults.go#L111
Outputs will change from:
```json
"Transient": {
"Conns": 10,
"ConnsInbound": 0,
"ConnsOutbound": 0,
"FD": 0,
"Memory": 0,
"Streams": 0,
"StreamsInbound": 0,
"StreamsOutbound": 0
}
```
to:
```json
"Transient": {
"Conns": 10
}
```
We need to confirm what zero means for Resource Manager. My understanding after asking @marten-seemann is that zero means zero, not infinite or not set.
If zero means zero, we need to specify a way to define no limits for some of the fields inside a BaseLimit or a BaseLimitIncrease object. We can use `-1` or use pointers to allow `nil` values.

Fix: Ignore zero values when marshalling Limits.

---

p2p/host/peerstore/pstoremem/addr_book.go
p2p/host/peerstore/test/addr_book_suite.go

Fixes #2005.
You can now use the peerstore with an empty peer ID. It's treated like any regular peer ID, which means that it's possible to save and retrieve addresses for that empty peer ID.
You most likely don't want to do this. Any peer _should_ have a real peer ID.

peerstore: make it possible to use an empty peer ID

---

p2p/host/resource-manager/error.go
p2p/host/resource-manager/scope.go

This lets users match against these errors with `.Is()`.

feat: rcmgr: Export resource manager errors

---

defaults.go
libp2p.go
p2p/muxer/mplex/transport.go
p2p/muxer/yamux/transport.go
p2p/net/swarm/dial_worker_test.go
p2p/net/swarm/testing/testing.go
test-plans/cmd/ping/main.go

The protocol IDs of the stream multiplexers are not exposed as constants, which makes using them a pretty miserable experience since you have to hunt through the code to find them. This is particularly true for mplex which, while still being the only multiplexer used in parts of the libp2p ecosystem, does not have its protocol ID referenced in go-libp2p outside of tests anymore (also the constructor documentation said `mplux` instead of `mplex`).
This exposes the protocol IDs with an exported constant `ID` as is done for Noise and TLS.
Also, fixes a documentation bug indicating that mplex was used by default.
Note: the various ipfs-camp-2019 examples can be updated as well post-release so that the constants are only defined once within go-libp2p.

Expose muxer ids

---

config/config.go
p2p/net/swarm/grafana-dashboards/swarm.json
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_conn.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_metrics.go
p2p/net/swarm/swarm_metrics_test.go
p2p/net/upgrader/upgrader.go

Fixes #1910.
Due to our experience with OpenCensus (#1955), this now uses Prometheus. There's a benchmark test that confirms that (by using a `sync.Pool` for the slices containing the labels) we're not allocating at all.

swarm: add a basic metrics tracer

---

p2p/net/swarm/swarm_conn.go
p2p/protocol/circuitv2/client/transport.go
p2p/transport/quic/conn.go
p2p/transport/quic/listener.go
p2p/transport/quic/transport.go
p2p/transport/tcp/tcp.go
p2p/transport/websocket/websocket.go
p2p/transport/webtransport/listener.go
p2p/transport/webtransport/transport.go

Fixes #2033.
Closes #2025  and closes #2031 .
The general pattern here is replacing 
```
func ...Dial() {
connScope := ...
err := ...
if err != nil {
connScope.Done()
}
err := ...
if err != nil {
connScope.Done()
}
err := ...
if err != nil {
connScope.Done()
}
}
```
With: 
```
func ...Dial() {
connScope := ...
c, err := dialWithScope
if err != nil {
connScope.Done()
return nil, err
}
return c, nil
}
func dialWithScope(..., connScope) {
if err != nil {
return nil, err
}
}
```

rcmgr: *: Always close connscope

---

p2p/protocol/holepunch/holepunch_test.go

holepunch: fix flaky test by not removing holepunch protocol handler

---

p2p/test/quic/quic_test.go

This test now:
1. sets up a node that speaks QUIC draft-29 and v1, and WebTransport
2. connects to that node, validating that if we're offered all 3 addresses, we pick QUIC v1
3. connects to that node, passing only the draft-29 address to the dialer, validating that we can dial a draft-29 connection
4. connects to that node from a node that only speaks WebTransport but not QUIC, validating that we can dial a WebTransport connection

quic / webtransport: extend test to test dialing a draft-29 and a v1 

---

p2p/test/notifications/notification_test.go

Closes #991. Nothing to fix in #991, but we should have a decent test for this behavior.

p2p/test: add test for EvtLocalAddressesUpdated event

---

p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/tracer_metrics.go
p2p/transport/tcp/metrics.go

Due to the performance impact, we're only collecting metrics when explicitly enabled anyway. We shouldn't even register the Prometheus metrics if not.

quic, tcp: only register Prometheus counters when metrics are enabled

---

p2p/test/quic/quic_test.go
p2p/transport/quicreuse/config.go

quic: disable sending of Version Negotiation packets

---

p2p/host/eventbus/basic_metrics.go
p2p/host/eventbus/basic_metrics_test.go
p2p/metricshelper/pool.go
p2p/metricshelper/pool_test.go
p2p/net/swarm/swarm_metrics.go

This PR:
1. Adds a global string slice pool, to be used by all of our metrics collectors. Using a single pool reduces code duplication and makes the `sync.Pool` more efficient.
2. Makes use of this pool for the event bus metrics, bringing down the number of allocs for events from 1 to 0.
cc @sukunrt You can use this for the AutoNAT metrics.

metrics: use a single slice pool for all metrics tracer

---

options.go
p2p/host/autorelay/autorelay_test.go
p2p/host/autorelay/options.go
p2p/host/autorelay/relay_finder.go
p2p/protocol/holepunch/holepunch_test.go

Provide two specific ways to enable the autorelay subsystem libp2p.EnableAutoRelayWithStaticRelays
libp2p.EnableAutoRelayWithPeerSource
fixes: https://github.com/libp2p/go-libp2p/issues/1866

autorelay: Split libp2p.EnableAutoRelay into 2 functions

---

test-plans/cmd/ping/main.go

Updates test to follow https://github.com/libp2p/test-plans/blob/master/multidim-interop/README.md

interop: Update interop test to match spec

---

p2p/host/resource-manager/README.md
p2p/host/resource-manager/limit.go
p2p/host/resource-manager/limit_config_test.backwards-compat.json
p2p/host/resource-manager/limit_config_test.go
p2p/host/resource-manager/limit_defaults.go
p2p/host/resource-manager/limit_test.go
p2p/host/resource-manager/rcmgr_test.go
p2p/test/resource-manager/rcmgr_test.go

This solves the problem around the encoding having different semantics than the config that is passed into the resource manager [context](https://github.com/libp2p/go-libp2p/pull/1998#issuecomment-1386348540). This makes special values explicit (Unlimited, default, block all). And I think it's a more ergonomic API (create a struct with sane defaults, rather than having to copy some pre-initialized struct, then modify relevant values).
The high level idea is you have some custom configuration called `PartialLimitConfig` that gets constructed with a `ConcreteLimitConfig` (a configuration that has no special or missing values, zero means zero, max means max). The `.Build` method fills in any missing information from the `PartialLimitConfig` and returns a complete `ConcreteLimitConfig`. …

feat!: rcmgr: Change LimitConfig to use LimitVal type

---

p2p/test/quic/quic_test.go

This will help debug #1922, since tests won't just time out and panic, but we'll get an actual error.
I also believe this is required to make the test show up as a flaky test.

p2p/test/quic: use contexts with a timeout for Connect calls

---

p2p/host/basic/basic_host.go
p2p/host/resource-manager/obs/stats.go
p2p/metricshelper/dir.go
p2p/net/swarm/swarm_metrics.go
p2p/protocol/identify/grafana-dashboards/dashboard.json
p2p/protocol/identify/id.go
p2p/protocol/identify/metrics.go
p2p/protocol/identify/opts.go

We're introducing some pretty substantial changes to the Identify protocol. It would be good to have some basic metrics.
We can probably do a lot more here, but this is a beginning so we're not flying completely blind.
Part of #2019.

identify: add some basic metrics

---

p2p/net/mock/mock_net.go

#1984 introduced a `.Start` method for the identify service. And this is started when you call `host.Start`. Mocknet, perhaps incorrectly, did not call host.Start after creating the host. This fixes that.

mocknet: Start host in mocknet

---

go.mod
go.sum
test-plans/go.mod
test-plans/go.sum

So callers can compare errors: https://github.com/multiformats/go-multistream/pull/100

chore: update go-multistream

---

p2p/host/eventbus/basic.go
p2p/net/connmgr/decay.go
p2p/net/swarm/dial_sync_test.go
p2p/protocol/circuitv1/relay/relay.go
p2p/protocol/circuitv2/relay/relay.go
p2p/transport/webtransport/transport_test.go

Fixes: https://github.com/libp2p/go-libp2p/issues/2043
@marten-seemann 
There are a bunch of uses of int32 and int64 as atomic counters with atomic.AddInt32 or atomic.AddInt64. We can replace those with atomic.Int32 and atomic.Int64. Should I change those too?

use atomic.Bool instead of int32 operations

---

.github/workflows/interop-test.yml

Uses the new action from https://github.com/libp2p/test-plans/pull/121

interop-tests: use new action with s3 caching

---

p2p/host/autonat/autonat.go
p2p/net/connmgr/decay.go
p2p/net/mock/mock_stream.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_stream.go

fixes: https://github.com/libp2p/go-libp2p/issues/2056

change atomic.Value to atomic.Pointer

---

core/test/crypto.go
p2p/host/autorelay/autorelay_test.go
p2p/host/eventbus/basic.go
p2p/host/eventbus/basic_test.go
p2p/host/eventbus/opts.go
p2p/net/connmgr/connmgr.go
p2p/net/connmgr/connmgr_test.go
p2p/net/mock/mock_conn.go
p2p/net/mock/mock_stream.go
p2p/net/upgrader/listener_test.go
p2p/protocol/circuitv1/relay/relay.go
p2p/protocol/circuitv2/relay/relay.go
p2p/protocol/internal/circuitv1-deprecated/relay.go
p2p/test/resource-manager/rcmgr_test.go

Fixes: https://github.com/libp2p/go-libp2p/issues/2095

use atomic.Int32 and atomic.Int64

---

CHANGELOG.md

In a draft for a discussion.
I like the idea of having a changelog file in the repo that can be updated as features are rolled out. Kubo does this and rust-libp2p does this. The less work we can do at release time the better. Ideally releases should feel almost like a no-op.
For the initial version, I copied the release notes from the tracking issue. In the future, I imagine the tracking issue is used as coordination/planning (as it's done today) and breaking changes/features are added in the changelog as we go. This can then be copy/pasted into the release notes.
I would also like to see the semantic PR titles being used to highlight breaking changes and such. But that's somewhat orthogonal to this change.

chore: Introduce a Changelog

---

p2p/host/autonat/autonat.go
p2p/host/autonat/autonat_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2046
@marten-seemann I've changed:
1. No events are emitted if only the observed address is changed.
2. All observations with reachability = Public and addr = nil are ignored. 
- previously this caused an increase in confidence.
3. transition from unknown to private now begins with confidence = 0. 
- previously this begin with confidence = 1

autonat: don't emit reachability changed events on address change

---

p2p/host/relaysvc/relay.go
p2p/host/relaysvc/relay_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2091

relaymanager: do not start new relay if one already exists

---

config/config.go
p2p/host/autonat/autonat.go
p2p/host/autonat/client.go
p2p/host/autonat/grafana-dashboards/autonat.json
p2p/host/autonat/metrics.go
p2p/host/autonat/metrics_test.go
p2p/host/autonat/options.go
p2p/host/autonat/svc.go
p2p/host/autonat/svc_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2017

autonat: add metrics

---

p2p/host/autonat/metrics_test.go
p2p/host/eventbus/basic_metrics_test.go
p2p/net/swarm/swarm_metrics.go
p2p/net/swarm/swarm_metrics_test.go
p2p/protocol/identify/metrics_test.go

Fixes: https://github.com/libp2p/go-libp2p/issues/2060

metrics: add no alloc metrics for eventbus, swarm, identify

---

p2p/transport/quic/listener.go

Fixes #1928.
I know this PR will make some people unhappy, but we really shouldn't send the peer a detailed error message here, as this might allow an attacker to gain a lot of insight into how a node under attack is coping with the attack. This error message has proved useful in debugging recent incidents on the IPFS network, but ultimately it's the wrong solution to the problem.
For example:
* it only works on QUIC
* and only for errors that occur during connection setup
Instead, we should have error codes: https://github.com/libp2p/specs/issues/479

quic: don't send detailed error messages when closing connections

---

dashboards/swarm/swarm.json
p2p/net/swarm/swarm_conn.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_metrics.go
p2p/net/swarm/swarm_metrics_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2106

swarm: add ip_version to metrics

---

config/config.go
defaults.go
options.go
p2p/host/autonat/metrics.go
p2p/host/basic/basic_host.go
p2p/host/eventbus/basic_metrics.go
p2p/metricshelper/registerer.go
p2p/metricshelper/registerer_test.go
p2p/net/swarm/swarm_metrics.go
p2p/protocol/identify/metrics.go

fixes: https://github.com/libp2p/go-libp2p/issues/2047

metrics: add options to disable metrics and to set Prometheus registerer

---

CHANGELOG.md
core/network/conn.go
dashboards/swarm/swarm.json
p2p/net/swarm/swarm_metrics.go
p2p/net/swarm/swarm_metrics_test.go
p2p/net/upgrader/conn.go
p2p/net/upgrader/upgrader.go
p2p/security/noise/session.go
p2p/security/noise/transport_test.go
p2p/security/tls/transport.go
p2p/security/tls/transport_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2021

swarm: add early muxer selection to swarm metrics

---

p2p/transport/quic/virtuallistener.go
p2p/transport/quicreuse/reuse.go

Fixes a case that only really shows up in CI where a listener can be stalled. This lead to some test flakiness.

quic: fix stalled virtual listener

---

p2p/protocol/circuitv2/relay/options.go

circuitv2: add a relay option to disable limits

---

p2p/net/swarm/dial_test.go

Doing these tests in parallel causes flakiness in CI.

swarm: remove parallel tests from swarm tests

---

p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_conn.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_listen.go

Fixes #2113, closes #2115.
More info here: https://github.com/libp2p/go-libp2p/pull/2115#issuecomment-1441001413

swarm: wrap conn with metrics

---

p2p/host/pstoremanager/pstoremanager.go
p2p/net/connmgr/decay.go
p2p/protocol/holepunch/tracer.go
p2p/transport/quicreuse/reuse.go
p2p/transport/webtransport/cert_manager.go

Generally doing something like `now := <-ticker.C` is wrong. The time in the channel is the time when the ticker was triggered, but may not be the current time when you pull from the channel. In a fast runtime these two are pretty close. In a slow runtime they aren't. This becomes a problem when we drop tick events, so the receiver will only get the old event and not the new one, thus breaking the logic that relies on the current time.
Changes this to make an explicit call to get the current time.

don't use the time value from the time.Ticker channel

---

p2p/net/swarm/swarm_dial.go

We may as well check the context before asking the transport to do any work. In some cases the saves us work since the transport may be doing things before checking the context. You my argue that's an issue with the transport, and that's fair and correct. But it's easy and cheap to check here once before involving the transport.

swarm: Check context once more before dialing

---

p2p/host/basic/basic_host_test.go

Fixes flaky `TestHostProtoPreknowledge` test.

basic_host: Fix flaky tests

---

examples/chat/chat_test.go

If we end the test right away we may miss logging the "Established Connection" line that this test checks for.

examples: Add sleep to fix flaky test

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/obsaddr_test.go

Had a couple of flakes here. This should fix it.

identify: Bump timeouts/sleep in tests

---

p2p/protocol/identify/id.go
p2p/protocol/identify/metrics.go
p2p/protocol/identify/metrics_alloc_test/metrics_test.go

The reason [TestMetricsNoAllocNoCover](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/autonat/metrics_test.go#L50) is flaky is because [go-libp2p-asn-util](https://github.com/libp2p/go-libp2p-asn-util/blob/master/asn.go#L14) spawns a background task in init that does heap allocations.

identify: Fix flaky TestMetricsNoAllocNoCover test

---

p2p/net/connmgr/decay_test.go

These tests relied on some background goroutine doing some work. This changes the equal checks to allow the tests to pass even if the background work doesn't happen instantly.
Fixes https://github.com/libp2p/go-libp2p/issues/1324. Fixes #1687. Fixes #1733. Fixes #1814.

connmgr: Use eventually equal helper in connmgr tests

---

p2p/host/autonat/autonat.go
p2p/host/autonat/autonat_test.go
p2p/host/autonat/client.go
p2p/host/autonat/interface.go
p2p/host/autonat/svc_test.go
p2p/host/basic/basic_host.go

fixes: https://github.com/libp2p/go-libp2p/issues/2102

autonat: don't use autonat for address discovery

---

p2p/host/resource-manager/extapi.go
p2p/host/resource-manager/extapi_test.go

Fixes #2155 
We need a better solution here. Some alternative solutions are here: https://github.com/libp2p/go-libp2p-resource-manager/pull/67#issuecomment-1176820561.
I think we should get a quick fix in here to unblock Kubo folks, but would be good to solve this more generally.

rcmgr: fix JSON marshalling of ResourceManagerStat peer map

---

p2p/protocol/circuitv2/relay/relay.go

fixes: https://github.com/libp2p/go-libp2p/issues/2162

circuitv2: cleanup relay service properly

---

p2p/net/connmgr/connmgr.go

This PR changes the log level for closing connections in connmgr.go from INFO to DEBUG, since as reported in https://github.com/status-im/status-go/issues/3249 these logs add too much noise.

connmgr: reduce log level for closing connections

---

CHANGELOG.md
core/network/conn.go
core/sec/insecure/insecure.go
core/sec/insecure/insecure_test.go
p2p/net/connmgr/connmgr_test.go
p2p/net/mock/mock_conn.go
p2p/net/swarm/swarm_conn.go
p2p/security/noise/session.go
p2p/security/noise/transport_test.go
p2p/security/tls/conn.go
p2p/security/tls/transport.go
p2p/security/tls/transport_test.go
p2p/transport/quic/conn.go
p2p/transport/quic/conn_test.go
p2p/transport/quic/listener.go
p2p/transport/quic/transport.go

core: remove LocalPrivateKey method from network.Conn interface

---

p2p/host/relaysvc/relay_test.go
p2p/protocol/circuitv2/relay/relay.go

fixes: https://github.com/libp2p/go-libp2p/issues/2167

relay: fix deadlock when closing

---

core/network/conn.go
p2p/host/basic/basic_host_test.go
p2p/host/routed/routed_test.go
p2p/net/connmgr/connmgr_test.go
p2p/net/mock/mock_conn.go
p2p/net/swarm/swarm_conn.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/ping/ping_test.go
p2p/test/backpressure/backpressure_test.go
p2p/test/reconnects/reconnect_test.go

fixes #2163 
Adds an `IsClosed` method to `network.Conn`

identify: Fix IdentifyWait when Connected events happen out of order

---

CHANGELOG.md
dashboards/relaysvc/relaysvc.json
p2p/host/basic/basic_host.go
p2p/protocol/circuitv2/relay/metrics.go
p2p/protocol/circuitv2/relay/metrics_test.go
p2p/protocol/circuitv2/relay/options.go
p2p/protocol/circuitv2/relay/relay.go

Metrics Added:
ReservationRequest: Opened, Closed, Renewed
ReservationRequestResponseStatus
ReservationRejectionReason
ConnectionRequest: Opened, Closed
ConnectionRequestResponseStatus
ConnectionRejectionReason
ConnectionDuration
BytesTransferred
RelayStatus

relay service: add metrics

---

p2p/protocol/identify/id.go

https://github.com/libp2p/go-libp2p/pull/2173 removed the requirement that swarm notifies identify before any new streams are started on a connection

identify: fix stale comment

---

p2p/test/websocket/websocket_test.go
p2p/transport/websocket/conn.go
p2p/transport/websocket/listener.go
p2p/transport/websocket/websocket.go

Fixes #2188 
Adds a regression test and makes sure the websocket library isn't allocating the whole message in a byte slice somewhere.

websocket: Don't limit message sizes in the websocket reader

---

p2p/transport/websocket/listener.go
p2p/transport/websocket/websocket_test.go

websocket: don't set a WSS multiaddr for accepted unencrypted conns

---

p2p/host/basic/basic_host.go

Fixes #2195.
This fix is not perfect. The error returned will be a `network.ErrNoConn`. Ideally, the swarm would not count a connection as "fully connected" before opening the first stream (and receiving _something_ from the peer) succeeds. This will also be necessary when we implement 0-RTT.

basichost: prevent duplicate dials

---

core/test/mockclock.go
core/test/mockclock_test.go
p2p/host/autorelay/autorelay_test.go
p2p/host/autorelay/options.go
p2p/host/autorelay/relay_finder.go

Also adds our own custom mock clock that fits a better interface for this module.
The new mock clock implements the following interface:
```go
// InstantTimer is a timer that triggers at some instant rather than some duration
type InstantTimer interface {
Reset(d time.Time) bool
Stop() bool
Ch() <-chan time.Time
}
// ClockWithInstantTimer is a clock that can create timers that trigger at some
// instant rather than some duration
type ClockWithInstantTimer interface {
Now() time.Time
Since(t time.Time) time.Duration
InstantTimer(when time.Time) InstantTimer
}
```
This lets us avoid the issue of https://github.com/libp2p/go-libp2p/pull/2187 altogether.
The new mock clock is about 100 LOC and should behave logically close to a real clock (time shouldn't jump from 0 to 1000 without work being …

autorelay: fix busy loop bug and flaky tests in relay finder

---

test-plans/cmd/ping/main.go
test-plans/ping-version.json

Adds support for listening on a WSS addr. After this is merged, I'll backport this patch to a branch off v0.25 to update the interop tester.

test-plans: Add wss transport to interop tester impl

---

p2p/discovery/backoff/backoff.go

- Fix comment typo & add a comma:
`a random number uniformly chose from` -> `a random number, uniformly chosen from`

discovery (backoff): fix typo in comment 

---

p2p/host/autonat/dialpolicy_test.go

this removes these lines from the test logs:
```
2023-03-26T19:56:27.2037777Z 2023-03-26T19:56:21.026Z	ERROR	swarm2	swarm/swarm_listen.go:118	swarm listener unintentionally closed
```
These lines are logged always currently. One example is in this test run. 
https://github.com/libp2p/go-libp2p/actions/runs/4525497218/jobs/7971850397?pr=2225

autonat: fix closing of listeners in dialPolicy tests

---

p2p/host/autonat/autonat.go
p2p/host/autonat/autonat_test.go

We don't want to update autonat reachability status from public to unknown or from private to unknown when peers reply to dial requests with status dial refused.

autonat: don't change status on dial request refused

---

config/config.go
dashboards/autorelay/autorelay.json
p2p/host/autorelay/autorelay.go
p2p/host/autorelay/metrics.go
p2p/host/autorelay/metrics_noalloc_test.go
p2p/host/autorelay/options.go
p2p/host/autorelay/relay_finder.go
p2p/protocol/circuitv2/client/reservation.go
p2p/protocol/circuitv2/client/reservation_test.go

metrics added:
relay finder status
reservation request outcomes
current reservations
candidate circuit v2 support
current candidates
relay addresses updated
num relay address
scheduled work times
closes: https://github.com/libp2p/go-libp2p/issues/2181

autorelay: add metrics

---

libp2p_test.go
options.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go
p2p/transport/webtransport/multiaddr.go
p2p/transport/webtransport/multiaddr_test.go
p2p/transport/webtransport/transport.go

Fixes #2233. Closes #2227. Fixes #2223.

correctly handle WebTransport addresses without certhashes

---

CHANGELOG.md

In prep for https://github.com/libp2p/go-libp2p/issues/2123

chore: 0.27.0 changelog entries

---

p2p/net/swarm/swarm_listen.go
p2p/net/swarm/swarm_test.go

Multiaddresses need to be compared with `Equal`, not with `==`, since `ma.StringCast(addr) != ma.StringCast(addr)`, but `ma.StringCast(addr).Equal(ma.StringCast(addr))`.

swarm: fix multiaddr comparison in ListenClose

---

p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_glass_test.go

The previous fix in #2235 was so close, but didn't catch this bug since ListenAddrs == InterfaceListeneAddrs in the [mocknet](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/mock/mock_peernet.go#L307).

identify: fix normalization of interface listen addresses

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
test-plans/cmd/ping/main.go

This is a major source of allocations. We can live with a `O(N*log(N))` scaling here.
We probably should move this function to the multiaddr package at some point.

basichost: don't allocate when deduplicating multiaddrs

---

p2p/transport/webtransport/transport.go

This solves a deadlock when `AddCertHashes` is called before `Listen`. It also means that we're initializing a certmanaer even if we're only using the WebTransport transport for dialing and not for listening, but that's a fringe use case anyway.

webtransport: initialize the certmanager when creating the transport

---

p2p/transport/quic/virtuallistener.go

closes #2259 
This doesn't add any extra logging. That's a bit bigger of a change so I'll do that in another PR.

quic virtual listener: don't panic when quic-go's accept call errors

---

.github/ISSUE_TEMPLATE/release.md

Don't consider a release "complete" until it's added to the interop test suite

chore: add interop testing to release checklist

---

.github/workflows/interop-test.yml

Speedup:
* Build step: 20s instead of 1m
* Test step: 10m instead of 15m
Switching to self-hosted runners therefore definitely pays off, even though spinning up the runner (currently) takes 1-2m. It also reduces contention for our quota of 20 GitHub provided runners.

ci: run interop tests on self-hosted runners

---

p2p/transport/quicreuse/connmgr_test.go
p2p/transport/quicreuse/reuse.go
p2p/transport/quicreuse/reuse_test.go

Currently there is a race in kubo between the first dial made by a node on startup and starting to listen on a quic address. 
If the dial happens first, this places an entry in the ```reuse.global``` map. This entry will stay in the map till we get a period of 30 seconds where we make no new dials. In my experiments this entry is removed after 15 minutes of starting the node. This dial happens before listening 5-10% of the times on my machine. 
The impact of this is on holepunching. While this entry is in the map, the function ```reuse.Dial``` in ```p2p/transport/quicreuse/reuse.go``` can return either this connection that we dialed out of but are not listening on, or it can return the correct connection the one on which we are listening.

quic: prioritise listen connections for reuse

---

core/transport/transport.go
p2p/net/swarm/swarm_listen.go
p2p/net/upgrader/listener.go
p2p/net/upgrader/listener_test.go
p2p/protocol/circuitv2/client/listen.go
p2p/transport/quic/virtuallistener.go
p2p/transport/quicreuse/connmgr_test.go
p2p/transport/quicreuse/listener.go
p2p/transport/websocket/listener.go
p2p/transport/webtransport/listener.go

swarm: log unexpected listener errors

---

p2p/host/routed/routed.go
p2p/net/swarm/dial_worker.go
p2p/net/swarm/dial_worker_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2283
`string(addr.Bytes())` is already used in peerstore. https://github.com/libp2p/go-libp2p/issues/2283
Fixes one more instance in `routed.go` https://github.com/libp2p/go-libp2p/blob/master/p2p/host/routed/routed.go#L122

swarm: change maps with multiaddress keys to use strings

---

examples/multipro/ping.go

This has failed a bunch of times for me. Recently here https://github.com/libp2p/go-libp2p/actions/runs/4951020063/jobs/8855433346

examples: fix flaky multipro TestMain

---

p2p/net/mock/mock_conn.go
p2p/net/mock/mock_net.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_test.go

Fixes #2267 + synchronously notifies as Swarm after #1562

net/mock: mimic Swarm's event and notification behavior in MockNet

---

go.mod
p2p/protocol/identify/id.go
p2p/protocol/identify/snapshot_test.go

This definitely happens during node startup: We receive a notification for adding the Identify Push protocol, as well as for starting to listen on our addresses. It might also happen later (maybe?).

identify: avoid spuriously triggering pushes

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

identify: don't send default protocol version

---

p2p/protocol/identify/id.go

Unfortunately, this is impossible to test. I tried using mocknet, but of course that thing is so horribly broken that it can't even reliably set the correct remote address of a connection. It fails at the most easy thing it was designed to do.

identify: filter received addresses based on the node's remote address

---

core/network/network.go
core/network/network_test.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/net/swarm/dial_worker.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_dial_test.go

I moved the DedupAddrs function to `core/network` since that seemed like the most relevant place for it to be so that basic_host and swarm can use it. Really this should probably be part of the multiaddr package. Although I would say we make that change later.
This change makes `swarm.addrsForDial` return only unique addresses. This is assumed by they dialWorker. I also added some existence checks to avoid any potential panics in case the key was missing from the pending map.
Most of this diff is a test or moving code around. The real change is the one line in swarm_dial.go.

swarm: Dedup addresses to dial

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

For multiple reasons:
1. They were not consumed anywhere.
2. We need to filter the addresses to avoid polluting the address book with local addresses.

identify: don't save signed peer records

---

dashboards/holepunch/holepunch.json
go.mod
p2p/host/basic/basic_host.go
p2p/metricshelper/conn.go
p2p/net/swarm/swarm_metrics.go
p2p/protocol/holepunch/holepuncher.go
p2p/protocol/holepunch/metrics.go
p2p/protocol/holepunch/metrics_noalloc_test.go
p2p/protocol/holepunch/metrics_test.go
p2p/protocol/holepunch/svc.go
p2p/protocol/holepunch/tracer.go
p2p/protocol/holepunch/util.go

fixes: https://github.com/libp2p/go-libp2p/issues/2103 and https://github.com/libp2p/go-libp2p/issues/2203

holepunch: add metrics

---

p2p/net/swarm/swarm_conn.go

We should still clean up the resources tracked by the resource manager even if we error here.

Clear stream scope if we error

---

p2p/net/swarm/swarm_dial.go

Removes comment suggesting we dial an address via one goroutine when it's on backoff. We do not do so. 
Removes old code snippets.

swarm: fix stale DialBackoff comment

---

core/test/mockclock.go

originally explained by @marcopolo here: https://github.com/libp2p/go-libp2p/pull/2260#discussion_r1201284744

test: document why InstantTimer is required

---

p2p/transport/webtransport/transport.go

Once the challenge succeeded there is no reason to keep the challenge stream open, it will never be used again.

webtransport: close the challenge stream after the Noise handshake

---

p2p/test/transport/transport_test.go

Related to #2194.
There is a failure with mplex that I haven't spent time yet debugging. If it's not obvious, I'd suggest we fix this in parallel with the webrtc work. Meaning merge this as is and have an issue to fix it soon.

transport tests: many streams and lots of data

---

dashboards/README.md

We're wrapping up #1356. At this point, we don't have any libp2p components left that we want to add dashboards for.

dashboards: finish metrics effort

---

p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_event_test.go

go-libp2p-kad-dht now listen to both EvtPeerIdentificationCompleted and EvtPeerConnectednessChanged and EvtPeerIdentificationCompleted calls .ConnsToPeer inorder to do some filtering.
However it happens that it deadlocks because if the swarm is trying to emit a EvtPeerConnectednessChanged while the subscriber is trying to process an EvtPeerIdentificationCompleted, the subscriber is stuck on s.conns.RLock() while the swarm wont release it before having sent EvtPeerConnectednessChanged. Deadlock !
I havn't confirmed this fixes my bug given this takes time to reproduce, I'll startup a new experiment later.

fix: in the swarm move Connectedness emit after releasing conns

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

identify: set stream deadlines for Identify and Identify Push streams

---

dashboards/README.md
dashboards/autonat/autonat.json
dashboards/autorelay/autorelay.json
dashboards/dashboard.yml
dashboards/datasources.yml
dashboards/docker-compose.yml
dashboards/eventbus/eventbus.json
dashboards/holepunch/holepunch.json
dashboards/identify/identify.json
dashboards/prometheus.yml
dashboards/relaysvc/relaysvc.json
dashboards/resource-manager/resource-manager.json
dashboards/swarm/swarm.json

As a last step to finish our metrics story, here's an easy way to make them more useful for local development.Just run
```bash
docker-compose up
```
and your local Grafana instance is up and running, collecting metrics from your libp2p node! See README for more instructions.

metrics: make it possible to spin up Grafana using docker-compose

---

config/config.go
dashboards/resource-manager/README.md
p2p/host/resource-manager/obs/stats.go

If the caller forgot to call rcmgrObs.MustRegisterWith, we will still get the metrics. If they have a StatsTraceReporter, they're anyway updating the counters. If they didn't provide a StatsTraceReporter, we will have registered a few extra metrics with prometheus. 
fixes: https://github.com/libp2p/go-libp2p/issues/2371

rcmgr: register prometheus metrics with the libp2p registerer

---

core/network/network.go
core/network/network_test.go

core: don't allocate in DedupAddrs

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/host/blank/blank.go

The goal here is to improve the experience of working with errors returned by the Host. With the current state, it's PITA to debug exactly what went wrong during a stream open and this feat attempts to solve it.
* Inspired by errors in std `net`.
* I wanted to improve the RoutedHost as well, but I will wait until you migrate to v1.20, as I need `errors.Join`
* I am open to any other suggestions on how to make this even better
* Can we include this in 0.28? 🙏🏻 🙏🏻 🙏🏻 
Closes https://github.com/libp2p/go-libp2p/issues/2334

basichost / blankhost: wrap errors

---

config/config.go
dashboards/resource-manager/README.md
p2p/host/resource-manager/README.md
p2p/host/resource-manager/noalloc_test.go
p2p/host/resource-manager/obs/obs.go
p2p/host/resource-manager/stats.go
p2p/host/resource-manager/stats_test.go
p2p/test/resource-manager/rcmgr_test.go

Required for https://github.com/libp2p/go-libp2p/issues/2372
Moves the exported types and functions of package `obs` to  `rcmgr`
Deprecates package `obs`

rcmgr: move StatsTraceReporter to rcmgr package

---

p2p/net/swarm/dial_ranker.go
p2p/net/swarm/dial_ranker_test.go

Depends on #2320 
Ignores https://github.com/libp2p/go-libp2p/issues/2349 We can take that up after this.

swarm: implement Happy Eyeballs ranking

---

p2p/test/transport/transport_test.go

See https://github.com/libp2p/specs/issues/553.

transport tests: remove mplex tests

---

dashboards/resource-manager/README.md
p2p/host/resource-manager/README.md
p2p/host/resource-manager/rcmgr.go
p2p/host/resource-manager/stats.go
p2p/test/resource-manager/rcmgr_test.go

#2389 targeted #2388, but #2388 was merged first so the changed in #2389 got left hanging.
Changes are Sukun's and I approved.

rcmgr: enable metrics by default

---

p2p/net/mock/interface.go
p2p/net/mock/mock_net.go
p2p/net/mock/mock_peernet.go
p2p/net/mock/mock_test.go

Adds support for enforcing `ConnectionGater` checks to `MockNet`. This enables integration tests to test connection gating policies such as peer blocking policies.
MockNet doesn't actually use security handshakes or a connection upgrade process, so the whole cycle is simulated with calls to `InterceptSecured` and `InterceptUpgraded` being done when the connection is opened.

net/mock: support ConnectionGater in MockNet

---

config/config.go
options.go
p2p/net/swarm/black_hole_detector.go
p2p/net/swarm/black_hole_detector_test.go
p2p/net/swarm/swarm.go

swarm: make black hole detection configurable

---

p2p/net/swarm/dial_ranker.go

This is a bug. It should've been 500ms always.

swarm: change relay dial delay to 500ms

---

p2p/protocol/holepunch/holepunch_test.go

Similar tests are skipped [elsewhere](https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/holepunch/holepunch_test.go#L409-L411)
Disabling blackhole detection will not work. We first [check](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/black_hole_detector.go#L233) if it's a public address and only then look at UDP and IPv6 black hole filters. 
Closes: #2411

holepunch: skip racy TestDirectDialWorks

---

p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_glass_test.go

fixes #2349 
For details see https://github.com/libp2p/go-libp2p/issues/2349#issuecomment-1608033872

identify: filter nat64 well-known prefix ipv6 addresses

---

p2p/net/swarm/dial_worker.go

First merge this to backoff cleanup and then we can merge both to master. 
Opening small PRs for individual items since this piece is complicated

swarm: remove unnecessary reqno for pending request tracking

---

p2p/host/autonat/options.go

- "agressive" -> "aggressive": spelling fix
- "confident" -> "confidence": grammar fix; replace adjective with noun
- "refresh interval" -> "refreshInterval": to match the parameter name

autonat: fix typo in WithSchedule option comment

---

p2p/host/basic/basic_host.go

This was copied from RoutedHost.NewStream. It is only relevant for RoutedHost

basichost: remove invalid comment

---

README.md

Also some typo and formatting fixes

chore: add notable project requirement

---

core/crypto/rsa_common.go
core/crypto/rsa_go.go
core/crypto/rsa_test.go

At a certain point these become too much effort to compute. This limits the max size.

core/crypto: restrict RSA keys to <= 8192 bits

---

p2p/net/swarm/swarm.go
p2p/test/basichost/basic_host_test.go

related to #1603 
We should not rely on type assertion here for this work. Ideally we should move Transient field to `network.ConnectionState` which is supported by `transport.CapableConn`. I'll do that in a later PR.

swarm: bugfix: don't open new stream over transient connection

---

go.mod
go.sum
p2p/host/peerstore/pstoreds/addr_book.go

See https://github.com/hashicorp/golang-lru/issues/142

chore: update golang-lru to v2.0.4, fixing semver violation

---

go.mod
go.sum
p2p/protocol/identify/id.go
p2p/protocol/identify/obsaddr.go
test-plans/go.mod
test-plans/go.sum

This is getting in two important changes in go-multiaddr that many users have been complaining about (see release notes).

update go-multiaddr to v0.11.0

---

p2p/host/peerstore/pstoreds/deprecate.go

For #2329.
Not removing the code yet, but at least we can give people a heads-up that this code is destined to die. This deprecation notice will (hopefully) be surfaced by our users' IDEs and CI.

peerstore: deprecate the database-backed peerstore

---

defaults.go
libp2p_test.go
p2p/host/autorelay/addrsplosion_test.go
p2p/net/swarm/dial_ranker_test.go
p2p/net/swarm/dial_worker_test.go
p2p/net/swarm/swarm_addr_test.go
p2p/net/swarm/swarm_dial_test.go
p2p/net/swarm/swarm_metrics_test.go
p2p/net/swarm/swarm_test.go
p2p/net/swarm/testing/testing.go
p2p/net/swarm/util_test.go
p2p/protocol/holepunch/metrics_noalloc_test.go
p2p/protocol/holepunch/metrics_test.go
p2p/protocol/identify/obsaddr_glass_test.go
p2p/test/quic/quic_test.go
p2p/transport/quic/conn_test.go
p2p/transport/quic/listener.go
p2p/transport/quic/listener_test.go
p2p/transport/quic/transport_test.go
p2p/transport/quicreuse/config.go
p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/connmgr_test.go
p2p/transport/quicreuse/listener.go
p2p/transport/quicreuse/options.go
p2p/transport/quicreuse/quic_multiaddr.go
p2p/transport/quicreuse/quic_multiaddr_test.go
test-plans/cmd/ping/main.go
test-plans/ping-version.json

This does the minimal amount of changes to drop draft29 without updating quic-go.
I'm thinking, for now at least, that we'll leave machinery of the multiversion QUIC for a couple of reasons:
1. It'll make adding support for QUIC-v2 very easy.
a. This would mostly be greasing exercise to avoid ossification on `quic-v1`. There's nothing QUIC-v2 gives us that we don't have with QUIC-v1.
2. It'll avoid us from reinventing this if we re-introduce this. This is tricky code and this code works and has been deployed for a bit.
3. It's stable as is, and a refactor would introduce more variables to the next release (already quite big with quic-go changes).

quic: drop support for QUIC draft-29

---

p2p/host/basic/basic_host.go

This does not do change anything because the transport always returns the same multiaddr you passed in in case of failure, it just looks wrong and relies on a obscure detail of the webtransport's AddCertHashes function, while this does not.

cleanup: add continue in case of failure in the (*BasicHost).Addrs certhash loop

---

core/crypto/ecdsa.go
core/crypto/key_test.go
core/crypto/rsa_go.go
core/crypto/secp256k1.go
internal/sha256/post_go1_21.go
internal/sha256/pre_go1_21.go
p2p/net/swarm/swarm_addr_test.go
p2p/security/noise/handshake.go

See rational and benchmarks in multiformats/go-multihash#173.
Fixes: #2308

use standard library sha256 implementation for Go 1.21

---

p2p/test/transport/deadline_test.go

Integrations test for deadlines
related to #2194

transport tests: add deadline tests

---

core/sec/security.go
p2p/security/noise/handshake.go
p2p/security/noise/transport_test.go
p2p/security/tls/crypto.go
p2p/security/tls/transport_test.go
p2p/test/transport/transport_test.go

partially resolves #2449.
This PR mostly works. However, it doesn't work with QUIC because QUIC encapsulates the error string instead of exposing it via unwrapping in https://github.com/quic-go/quic-go/blob/f3a0ce1599732cb56b958c2f0903074b62a7e9bf/internal/handshake/crypto_setup.go#L643.
Could add additional tests (or move over the ones from vole) if we're happy with this PR.
@marten-seemann is making a change to quic-go to allow inspection of the inner error inside the transport error reasonable?

feat: add ErrPeerIDMismatch error type to replace ad-hoc errors

---

p2p/net/swarm/black_hole_detector.go
p2p/net/swarm/black_hole_detector_test.go
p2p/net/swarm/dial_worker.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_dial_test.go

Depends on #2460 
This introduces a small breaking change. On no good addresses we previously used to return `ErrNoGoodAddress` not we return a `*DialError` which returns true on `errors.Is(err, ErrNoGoodAddress)`
This along with #2437 will allow us to check for all the reasons why dialing an address failed. 
The minor breaking change is easy enough to remove but in this case it seems worth it since we are returning more information and also preserving existing behaviour, the only change required in existing code is using `errors.Is` instead of `==`

swarm: return errors on filtered addresses when dialing

---

p2p/net/swarm/dial_error.go
p2p/net/swarm/dial_error_test.go
p2p/net/swarm/swarm_dial_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2436
Depends on #2460  #2461 
Blocked on go1.21 release.

swarm: fix Unwrap for DialError, implement Unwrap for TransportError

---

.github/workflows/interop-test.yml

Avoid running the interop tests on code changes to directories that do not need testing.
Ref: https://github.com/libp2p/test-plans/pull/272

ci: limit interop tests runs to core folders

---

p2p/protocol/identify/id_test.go

I suspect there's another test that's not shutting down cleanly, but I don't want to spend a lot of time debugging this.

identify: disable racy test when running with race detector

---

config/config.go

If the autonat server receives too many requests from private nodes, this can cause the autonat server to incorrectly skip QUIC or IPv6 dial back requests. 
Fixes: #2530

host: disable black hole detection on autonat dialer

---

p2p/http/libp2phttp.go

We are expecting this to be vastly read dominated, caching this makes sense.

p2p/http: cache json wellknown mappings in the .well-known handler

---

dashboards/swarm/swarm.json
p2p/net/swarm/dial_sync.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_metrics.go
p2p/net/swarm/swarm_metrics_test.go

swarm: track dial cancellation reason

---

examples/chat-with-mdns/main.go
examples/chat/chat.go
examples/chat/chat_test.go
examples/echo/main.go
examples/http-proxy/proxy.go
examples/pubsub/basic-chat-with-rendezvous/main.go
examples/pubsub/chat/README.md
examples/pubsub/chat/chatroom.go
examples/pubsub/chat/main.go
examples/routed-echo/main.go

The peerID Pretty method is already deprecated, switch it to call String method.
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)

examples: stop using deprecated peer.ID.Pretty

---

go.mod
go.sum
p2p/net/upgrader/upgrader.go
test-plans/go.mod
test-plans/go.sum

Fixes #2330. For https://github.com/libp2p/specs/issues/573.
Turns out there wasn't even a test for this...
We can also merge https://github.com/multiformats/go-multistream/pull/107 first, cut a new release, and then update go-multistream in this PR.

upgrader: drop support for multistream simultaneous open

---

core/peer/addrinfo.go
core/peer/addrinfo_test.go
core/peer/peer.go
p2p/host/autonat/svc.go
p2p/host/autorelay/relay_finder.go
p2p/host/peerstore/pstoreds/addr_book.go
p2p/host/peerstore/pstoreds/addr_book_gc.go
p2p/host/peerstore/pstoreds/keybook.go
p2p/host/peerstore/test/utils.go
p2p/net/connmgr/decay.go
p2p/net/gostream/gostream_test.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_conn.go
p2p/net/swarm/swarm_dial.go
p2p/net/swarm/swarm_dial_test.go
p2p/security/tls/cmd/tlsdiag/client.go
p2p/security/tls/cmd/tlsdiag/server.go
p2p/security/tls/transport_test.go
p2p/transport/quic/conn_test.go

This method has been deprecated for more than a year now.

core/peer: remove deprecated ID.Pretty method

---

p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go

/dnsaddr allows forwarding to arbitrary multiaddresses. We can't assume that the host name stays the same.
Thanks to @sukunrt for pointing this out in https://github.com/libp2p/go-libp2p/pull/2564#pullrequestreview-1621750665.

websocket: don't resolve /dnsaddr addresses

---

p2p/net/swarm/dial_worker.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_dial.go
p2p/test/swarm/swarm_test.go

This fixes a bug where the first call to `swarm.DialPeer` succeeds and returns a transient connection with no error while the second call to `swarm.DialPeer` returns `(nil, network.ErrTransientConn)`.
For dialing, we now only rely on `network.WithForceDirectDial` to force a direct connection.
For new stream, we open a stream on a transient connection only if `network.WithUseTransient` is used.
This feels correct to me since once we fix #1603 we can have `NewStream` called without `network.WithUseTransient` or `network.WithForceDirectDial` and it'll wait for the transient connection to be upgraded to a direct connection before returning.  
I'm not fixing it the other way round, i.e. Failing if `network.WithUseTransient` is not used, because there are users of this API who are probably …

swarm: fix DialPeer behaviour for transient connections

---

p2p/transport/webrtc/stream_write.go
p2p/transport/webrtc/transport_test.go

fixing a bug where some small writes can succeed after the deadline has passed

webrtc: fail Write early if deadline has exceeded before the call

---

p2p/transport/webrtc/udpmux/muxed_connection.go

initialised here: https://github.com/libp2p/go-libp2p/blob/master/p2p/transport/webrtc/udpmux/mux.go#L131
and pushed to queue here: 
https://github.com/libp2p/go-libp2p/blob/master/p2p/transport/webrtc/udpmux/mux.go#L160

webrtc: put buffer back to pool

---

p2p/transport/webrtc/stream.go

also fixes a persistent failure in CI: https://github.com/libp2p/go-libp2p/actions/runs/6261705440/job/17007197102

webrtc: fix deadlock on connection close

---

test-plans/README.md

we use the lower case string in https://github.com/libp2p/go-libp2p/blob/master/test-plans/cmd/ping/main.go#L42

interop: fix redis env var

---

p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

This allows us to serve `/a/b` when we mount a `http.ServeMux` handler for `/b` on a libp2phost at path `/a`.
Currently this is a 404 as `/a/b` will reach the handler for `/b` with the url `b` as we strip `/a/`.
The paths on a `ServeMux` have to begin with `/` as `cleanPath` [here](https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/net/http/server.go;l=2345) will add the prefix `/` and then the comparison [here](https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/net/http/server.go;l=2475-2479) will redirect to the cleaned path. This redirect will cause a 404. See the added test and linked issue for details. 
There is an annoying case [though](https://github.com/libp2p/go-libp2p/pull/2552/files#r1314250807), 
closes: #2545

libp2phttp: don't strip `/` suffix when mounting handler

---

p2p/transport/webrtc/udpmux/mux.go
p2p/transport/webrtc/udpmux/mux_test.go
p2p/transport/webrtc/udpmux/muxed_connection.go

The address in ReadFrom should be the address of the received packet and not the address of the first packet received from the peer. If the interface used to send the first packet disallows incoming packets, this will lead to a connection not being established. 
The simplest way to test this is to use tailscale. Packets originated from tailscale address can be sent to localhost addresses, packets from localhost can't be sent to tailscale listeners. So if the first packet from the dialer is from the tailscale interface, the connection will never be established because muxedConnection.ReadFrom will always return the address of the packet as the tailscale address and we will ignore all reachable localhost packets.
My theory is that this is what is causing flakiness like the one observed …

webrtc: correctly report incoming packet address on muxed connection

---

p2p/host/resource-manager/README.md
p2p/host/resource-manager/docs/allowlist.md

Typos: 
ellucidate --> elucidate
protcol --> protocol
transfered --> transferred

Spell Check: Fix typos

---

p2p/net/swarm/swarm.go
p2p/test/basichost/basic_host_test.go
p2p/test/swarm/swarm_test.go

depends on #2547, This PR is just the last commit. This might help to review it independently https://github.com/libp2p/go-libp2p/pull/2542/commits/b2377e9b625ffa328047b0298daa71c1f5793059
closes #1603

swarm: wait for transient connections to upgrade for NewStream

---

options.go

The pkg.go.dev website shows `DEPRECATED` tags for functions that are marked as deprecated, but the libp2p `DialRanker` function is missing a newline before the `// Deprecated:` line. As a result, even though the function is deprecated, pkg.go.dev does not tag/label it as deprecated.
This also affects language servers such as gopls.
With gopls enabled in VSCode (using the Go extension), deprecated functions are indicated with a strikethough. This strikethrough does not appear for `DialRanker` because of the missing newline.
I published my own module to test this.
See: https://pkg.go.dev/github.com/librick/go-deprecated@v0.1.0/deprecated

Fix missing deprecation tag

---

core/transport/transport.go
p2p/net/swarm/dial_ranker.go
p2p/net/swarm/dial_ranker_test.go
p2p/net/swarm/dial_worker.go
p2p/net/swarm/dial_worker_test.go
p2p/net/swarm/limiter.go
p2p/net/swarm/limiter_test.go
p2p/net/swarm/swarm_dial.go
p2p/transport/tcp/tcp.go
p2p/transport/tcp/tcp_test.go

The required change is much simpler than my previous tries. Closing other open PRs in favour of this.

swarm: use happy eyeballs ranking for TCP dials

---

p2p/protocol/circuitv2/relay/constraints.go

This is responsible for some of the flakiness of the autorelay testsuite. Loading the ASN table takes a lot of time. I think we can optimise the underlying library but this change is harmless since localhost / private addresses wouldn't be associated with an ASN.

circuitv2: don't check ASN for private addrs

---

.github/workflows/interop-test.yml
test-plans/README.md

ci: migrate to renamed interop test action

---

p2p/transport/webrtc/udpmux/mux_test.go

1. Checking pointer equality here is fine. 
2. require.Equal(x, y) does a field by field comparison of x and y's fields. This causes a race condition when comparing fields accessed by other goroutines.

webrtc: fix race in TestRemoveConnByUfrag

---

go.mod
go.sum
p2p/protocol/identify/id.go
p2p/protocol/identify/id_glass_test.go
p2p/protocol/identify/id_test.go
test-plans/go.mod
test-plans/go.sum

identify: don't filter dns addresses based on remote addr type

---

p2p/net/swarm/dial_worker.go

Ensure we never leak timers out of the dial loop.
See https://discuss.ipfs.tech/t/constant-100-cpu-utilization-on-aws-ec2-ipfs-node/17172

swarm: fix timer Leak in the dial loop

---

libp2p.go

The docs for libp2p's `func New` say:
>If no peer identity is provided, it generates a random RSA 2048
key-pair and derives a new identity from it
Maybe I'm misinterpreting the docs, but I've observed that the default is actually Ed25519:
```go
node, err := libp2p.New()
if err != nil {
panic(err)
}
fmt.Printf("Peer ID key type: %s\n", node.Peerstore().PrivKey(node.ID()).Type())
```
Which prints "Peer ID key type: Ed25519".
This is further supported by the [Peer Id spec](https://github.com/libp2p/specs/blob/d2106f43e878ae4c3a1c6465a7c329835290fe22/peer-ids/peer-ids.md?plain=1#L119):
>Implementations MUST support Ed25519. Implementations SHOULD support RSA…
This commit updates the function docs to express that the default is Ed25519, not RSA.

Update docs from RSA to Ed25519

---

examples/echo/main.go

in this echo case, sender is no need to SetStreamHandler, the sender node only used to interact with listener node.

examples: remove unused 'SetStreamHandler'

---

p2p/host/basic/basic_host.go
p2p/host/pstoremanager/pstoremanager.go
p2p/host/pstoremanager/pstoremanager_test.go

For https://github.com/libp2p/go-libp2p/issues/2643.
@juligasa could you try out this PR?

pstoremanager: fix race condition when removing peers from peer store

---

dashboards/docker-compose.base.yml

The existing Grafana dashboard for resource manager wasn't mapped into the Grafana Docker container.

chore: add resource manager dashboard to docker-compose

---

dashboards/swarm/swarm.json

When using the existing Grafana setup, the newer versions of Grafana fail to provision the Swarm dashboard. It works when importing it manually, but it fails during the automatic provisioning, complaining about not being able to transform legacy templates.
Apparently the issues is in the format of the `templating` field of the dashboard JSON. I adapted it from the other dashboards that seem to work just fine with provisioning.

Fix Swarm Grafana Dashboard

---

p2p/host/resource-manager/extapi.go

closes: #2628 
The ConnLimit is associated with Connection scope and always has connection limit 1 because within a connection scope you only need 1 connection. 
The correct system connection limit is provided by the system scope. 
Thanks! @juligasa

rcmgr: fix connmgr connection limit conflict warning

---

README.md

This existing link has a redirect loop. The new link is the actual security policy url that includes the two latest go version guideline.

chore: update go security policy url

---

examples/chat-with-mdns/main.go

Close #2418 
Add a simply logic(by compare peer id) to avoid call `NewStream` from both side.
----

examples: call NewStream from only one side

---

examples/chat-with-mdns/README.md

Ref #2677
😂 Forgot to update the chat-with-mdns example readme in that pr, updated it here

chore: update chat-with-mdns example readme

---

p2p/http/example_test.go

This fails once a while with addr in use error

libp2phttp: fix flaky ExampleHost_listenOnHTTPTransportAndStreams

---

core/crypto/key.go
core/crypto/key_test.go

This was used for SECIO which has been long deprecated.

chore: remove unused GenerateEKeyPair function

---

p2p/transport/webrtc/listener.go
p2p/transport/webrtc/stream_test.go
p2p/transport/webrtc/transport_test.go
p2p/transport/webrtc/udpmux/mux.go

There is currently a leak in the webrtc listener. When the listener is closed the udp mux readloop just keeps running.
depends on #2716

webrtc: close mux when closing listener

---

p2p/discovery/backoff/backoffcache.go
p2p/discovery/backoff/backoffcache_test.go
p2p/host/resource-manager/scope.go
p2p/transport/webrtc/stream.go

Here are a few small changes.
Happy to do 3 PRs if you want a single one per change.
The only actual code change that is reachable is that I have now interlocked the Locks in the stream `spawnControlMessageReader` function. 
This could be an issue if another goroutine were to lock the stream lock and wait on being able to lock on the reader lock before releasing the stream lock, but if that were the case, it would also mean that the previous code didn't get the guarantee no other function was able to "do reader.ReadMsg" as the comment says.
This is the reason why we should Lock the stream mutex before unlocking the reader one, IMO.

Small code improvements

---

go.mod
p2p/transport/webrtc/listener.go
p2p/transport/webrtc/logger.go
p2p/transport/webrtc/transport.go

Internally pion uses a lot of logger objects. It's better to just share one logger across everything.
Depends on: #2717

webrtc: use a common logger for all pion logging

---

p2p/security/noise/handshake.go

After #1657 #2309 #2708 modifications, the unnecessary code can be removed here

security: remove unnecessary noise code

---

p2p/host/basic/basic_host.go

We also met [this issue](https://github.com/libp2p/go-libp2p/issues/339), it may help to provide more info besides "protocol mux failed"

add more info to "protocol mux failed"

---

p2p/test/transport/rcmgr_test.go
p2p/transport/webrtc/listener.go
p2p/transport/webrtc/stream.go
p2p/transport/webrtc/stream_write.go
p2p/transport/webrtc/transport.go

Based on numbers here: https://github.com/libp2p/go-libp2p/issues/1917#issuecomment-2007681530

webrtc: set sctp receive buffer size to 100kB

---

p2p/transport/quicreuse/listener.go

This was fixed in quic-go in v0.42
Introduced in: https://github.com/libp2p/go-libp2p/pull/2710

quicreuse: remove workaround for quic-go listener close deadlock

---

p2p/security/tls/crypto.go

`KeyLogWriter` can help us use Wireshark to analyze TLS decrypted network packets.
Details can be found at: https://wiki.wireshark.org/TLS#using-the-pre-master-secret

feat: add tls `WithKeyLogWriter` option

---

p2p/transport/webrtc/transport.go

Had issues dialling due to a null network.ResourceManager
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf76692]
goroutine 183 [running]:
github.com/libp2p/go-libp2p/p2p/transport/webrtc.(*WebRTCTransport).Dial(0xc00014d860, {0x16b4e00, 0xc000325c70}, {0x16c3dc0, 0xc000371e60}, {0xc00039ec60, 0x26})
/root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.33.1/p2p/transport/webrtc/transport.go:245 +0x52
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).dialAddr(0xc000465208, {0x16b4e00, 0xc000325c70}, {0xc00039ec60, 0x26}, {0x16c3dc0, 0xc000371e60}, 0xc00026e900)
/root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.33.1/p2p/net/swarm/swarm_dial.go:545 +0x41d …
```

webrtc: add NullResourceManager, fixes panic

---

config/config.go
leaky_tests/leaky_test.go
libp2p_test.go
p2p/host/autonat/autonat.go
p2p/host/autonat/svc.go
p2p/net/swarm/swarm.go

Autonat would leave a couple of dangling go routines because it wouldn't close the swarm or the peerstore. Fixes #2743.

autonat: Clean up after close

---

p2p/http/example_test.go
p2p/transport/quic/cmd/client/main.go
p2p/transport/quic/cmd/lib/lib.go
p2p/transport/quic/cmd/lib/lib_test.go
p2p/transport/quic/cmd/server/main.go

Continues from https://github.com/libp2p/go-libp2p/pull/2751. I was not able to push to that branch.
- Does the same as #2751 
- Moves run code to a lib package and runs a test on it.
Closes #2751

quic: make server cmd use RFC 9000 instead of draft-29 

---

p2p/http/example_test.go
p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

Renaming the well-known libp2p http resource. Context here: https://github.com/libp2p/specs/pull/508#discussion_r1550043195

libp2phttp: Rename well-known resource

---

go.mod
go.sum

fix https://github.com/libp2p/go-libp2p/issues/2762

fix: revert gorilla/websocket from 1.5.1 to 1.5.0

---

examples/chat-with-rendezvous/chat.go

closes #2137 
Uses the bootstrap peers option. Also sleeps a little since the `.Bootstrap` doesn't block until. Without the sleep this example doesn't work since it effectively queries with an empty routing table. Really Bootstrap should block, or we should repeat the query every so often.

Update chat with rendezvous example

---

core/event/identify.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go

Identify has an event that it emits, but it's not very useful in that it will only tell you a peer has been identified, but not tell you anything about that peer. This design is intended to have the user then lookup peer information somewhere else after they get the event. However, that approach is brittle because it relies on identify itself probing in and updating all the "somewhere elses". This issue is highlight in #2754 and #2355.
Instead, Identify should only concern itself with emitting an event about what it has learned. Other services can subscribe to those events and do their appropriate logic. This helps decouple these services from each other.
Relates to #2754 and #2355 
This is a partial fix for #2754. The next step after this is merged is to update GossipSub to make use of …

Identify: emit useful events after identification

---

p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

This tells clients not to reuse the stream. They should make new requests on new streams. Context https://github.com/libp2p/specs/pull/508/files#diff-8e568763d7d4e15f9465300afa93c121c7f8e399acfff4c2aee7e70ed1199401R125

libp2phttp: Return connection: close when doing http over streams

---

examples/README.md
examples/pubsub/README.md
examples/relay/README.md

This PR addresses the incompleteness of readmes in the examples section.
- The main readme does not list all the examples in the directory
- The pubsub readme does not list all the examples in this subcategory
- the relay example was missing a readme

Update: update incomplete readmes

---

p2p/host/basic/basic_host.go
p2p/test/basichost/basic_host_test.go
p2p/transport/webrtc/transport.go
p2p/transport/webrtc/transport_test.go

This change is similar to how we append certhashes for webtransport.

basichost: append certhash for webrtc addresses provided via address factory

---

config/config.go
core/peerstore/peerstore.go
libp2p_test.go
options.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/nat_emitter.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_glass_test.go
p2p/protocol/identify/obsaddr_test.go
p2p/protocol/identify/opts.go

Provides an option to disable observed address manager for users who know their external IP addresses.

identify: refactor observed address manager to do address mapping at thin waist(IP+TCP/UDP) layer

---

p2p/host/resource-manager/conn_limiter.go
p2p/host/resource-manager/conn_limiter_test.go
p2p/host/resource-manager/rcmgr.go
p2p/protocol/circuitv2/client/transport.go

This change makes the resource manager aware of IPs. Adds some reasonable defaults too.

rcmgr: Add conn_limiter to limit number of conns per ip cidr

---

p2p/net/gostream/listener.go
p2p/protocol/circuitv2/client/handlers.go
p2p/protocol/circuitv2/relay/relay.go

A couple of places were missing deadlines so I added them.

fix: Set missing deadlines

---

p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

This allows HTTP request timeout and cancellation to work.
Fixes #2533

Adhere to request.Context when roundtripping on a stream

---

p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

We've bike shedded on the well-known resource so long that we have a number of users that are relying on the old well-known path being at `.well-known/libp2p`. This patch gives them a migration path. Enabling this option allows clients to request both the new and old path in parallel (so it doesn't cost one whole round trip). On the server side, it serves both well-known resources so that legacy clients don't break.
This change is meant to give our early adopters of libp2phttp a migration path. The goal is to get rid of this code after some time (2 releases? 3?) to allow users to upgrade.

Add backwards compatibility option to libp2phttp for the well-known resource

---

p2p/net/swarm/swarm_dial_test.go

swarm: fix addr for TestBlackHoledAddrBlocked

---

libp2p_test.go
p2p/host/resource-manager/rcmgr.go
p2p/protocol/circuitv2/client/transport.go

I tried to introduce a new method to the ResourceManager without breaking the API. That was a mistake, I should have broken the API because the new method was effectively required.
Users who wrapped the default implementation of the ResourceManager wouldn't get the new method. The circuitv2 transport would not see the new method, and then call the fallback method, which would fail in the default implementation. This is a subtle footgun that could have been avoided by either changing the api or changing the default implementation's fallback method to know not to expect an IP address when doing a circuitv2 connection. This fix does the latter for now to not break the API. Another PR I'll introduce soon will break the API and I'll try to merge that before the next release.

rcmgr: Backwards compatibility if you wrap default impl

---

p2p/host/resource-manager/conn_limiter.go
p2p/host/resource-manager/conn_limiter_test.go
p2p/host/resource-manager/rcmgr.go
p2p/host/resource-manager/rcmgr_test.go

Despite the field being called "ConnLimitPerCIDR" you weren't able to define limits for a specific CIDR address block. I've renamed this to ConnLimitPerSubnet to make it clearer that this connection limit applies to each subnet with the same N bit prefix.
I've also added an option to allow defining limits on specific address prefix blocks. If an IP address matches one of these blocks then that limit is used instead of the more generic `ConnLimitPerSubnet`. By default you are allowed unlimited connections from localhost. This should prevent test breakages we've seen.
This does break the existing API. I think that's okay because:
- We just released this API, so hopefully no one is using it yet. Or, if they are, it's fresh on their mind.
- Most users probably just stuck with the defaults. …

rcmgr: Support specific network prefix in conn limiter

---

examples/libp2p-host/README.md
examples/libp2p-host/host.go

Remove out-dated code in example readme

---

p2p/protocol/ping/ping.go

so that ping streams cannot be squatted

limit ping duration to 30s

---

p2p/protocol/identify/id.go

Updates the `filterAddrs` logic to no-op if the address is neither public nor private.
This fixes an issue in mocknet that assigns each node an address in the [IPv6 discard prefix](https://datatracker.ietf.org/doc/html/rfc6666) space. That doesn't interact well with this logic in identify.
The issue mocknet hits is that it filters out all received listen addresses and then doesn't remember any address for the peer.

identify: Don't filter addr if remote is neither public nor private

---

p2p/protocol/identify/obsaddr.go

If a connection was closed before receiving an identify response, the corresponding observed address could be wrongly removed as the connection counter for the local address was being decremented on each disconnect even if no messages were consumed by `IDService` previously.
The issues began after #2793
Patch by @sukunrt

identify: fix observed address handling

---

p2p/protocol/identify/obsaddr_test.go

This modifies TestObservedAddrManager to verify the fix in #2825

identify: add test for observed address handling

---

p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go
p2p/net/gostream/conn.go
p2p/net/gostream/listener.go

ResponseWriter implements a deprecated `CloseNotifier` interface. The [implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.22.3:src/net/http/server.go;l=738) considers any error during a read an indication that the whole connection is closed. One of these errors is EOF.
When we do HTTP over streams, it's normal for an EOF to happen after reading the request (in fact, it's recommended in the spec).
The workaround here is to ignore EOF errors on read when it's a stream we accept a stream (Listener side). This should be fine since we know how to read a full request (doesn't rely on EOF) and if the stream is closed writing will fail

libp2phttp: workaround for ResponseWriter's CloseNotifier

---

p2p/transport/webrtc/transport.go
p2p/transport/webrtc/transport_test.go

Closes: #2827 
Should we reject connections attempts with ufrag that don't have this prefix? 
I think it is fine to accept all attempts. The purpose of this prefix is to allow us to extend this in the future. So when we do v2 we can make that check aggressive and consider all ufrags without any prefix to be v1.

webrtc: fix ufrag prefix for dialing

---

p2p/net/swarm/dial_worker.go
p2p/net/swarm/dial_worker_test.go

This makes the common case O(1) compared to O(N) before. Updating an element is a separate op and we check the element from the back of the slice as most inserts are sorted.

swarm: improve dial worker performance for common case

---

p2p/http/example_test.go
p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

After working on the js-libp2p API for libp2p+HTTP, I realized it's quite natural to make an HTTP request given a multiaddr URI (who would've guessed?).
This change makes using the HTTP client with libp2p easier and more natural. Instead of having to create a specialized roundtripper for each server, you can now have a single `http.Client` that can make requests to multiple servers. The usage feels very familiar to the classic HTTP api. You can now do this:
```
client := http.Client{Transport: &libp2phttp.Host{ options... }}
client.Get("https://example.com") // Standard way of making an HTTP request
client.Get("multiaddr:/dns/example.com/tls/http") // Same as above, but with a multiaddr scheme
client.Get("multiaddr:/dnsaddr/example.com/p2p/QmFoo") // galaxy brain; make an HTTP request …
```

libp2phttp.Host implements RoundTripper

---

p2p/metricshelper/conn.go
p2p/metricshelper/conn_test.go

minor quality of life improvements like nil checks and classifying dns4 as ipv4 addresses for purposes of tracking ip version.

metricshelper: improve checks for ip and transport

---

config/config.go
p2p/transport/webrtc/transport_test.go

libp2p: use rcmgr for autonat dials

---

p2p/test/transport/transport_test.go
p2p/transport/quic/listener.go
p2p/transport/quic/listener_test.go

When wrapping a quic connection into a transport.CapableConn we wouldn't always close the underlying connection if wrapping failed. This fixes that and adds some tests to ensure all transports do this properly.
I believe this closes #2841

fix: Close conn in quic listener when wrapping fails

---

go.mod
go.sum
test-plans/go.mod
test-plans/go.sum

This change has some history. Originally there was v1.5.0, then the
project stalled and eventually the repo got archived. Some new
maintainers stepped up and released v1.5.1. That version had some
controversial changes including excessive logging (see
https://github.com/gorilla/websocket/issues/880). This caused us to
downgrade this dep back to v1.5.0 (see #2762). The change was short
lived as I bumped this dep back up to v1.5.1 without remembering this
context.
Since then the maintainers of gorilla/websocket have released a new
version v1.5.3 that brings the project back to the state of when it got
archived (minus a README edit). Bumping to this version should solve our
issues with v1.5.1 without having to downgrade back down to v1.5.0.

chore: Bump gorilla/websocket to 1.5.3

---

p2p/host/basic/basic_host.go

We are missing one reset here: https://github.com/libp2p/go-libp2p/blob/master/p2p/host/basic/basic_host.go#L703
Possibly impacts #2858

basichost: reset new stream if rcmgr blocks

---

p2p/transport/websocket/listener.go

closes #2865
`ErrListenerClosed` is supposed to be returned by `Accept` when listener is closed.

websocket: don't return transport.ErrListenerClosed on closing listener

---

go.mod
go.sum
p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go
test-plans/go.mod
test-plans/go.sum

Adds support for multiaddr URIs that contain `/http-path` components. In other words, this works now:
```
client := http.Client{Transport: &libp2phttp.Host{ options... }}
client.Get("multiaddr:/dns/example.com/tls/http/http-path/some%2fpath")
// equivalent to
client.Get("https://example.com/some/path")
// And of course works with any libp2p stream transport:
client.Get("multiaddr:/dnsaddr/example.com/p2p/QmFoo/http-path/some%2fpath")
```

feat: libp2phttp `/http-path`

---

defaults.go
libp2p_test.go
p2p/transport/webrtc/transport.go
p2p/transport/webrtc/udpmux/mux.go

webrtc: remove experimental tag, enable by default

---

p2p/discovery/routing/routing.go

https://github.com/libp2p/go-libp2p/blob/cb81b3e48cfbda2cec9687d1341841822b58e050/p2p/discovery/routing/routing.go#L58-L76
`FindProvidersAsync` allows a limit of `0` to return all found providers. However, it is impossible to make use of this feature with `FindPeers` since it sets the limit to `100` if it was previously `0`.
This is a non breaking fix, users omitting the `Limit(X)` parameter will continue to have (at most) `100` results returned. Alternatively, we could change the default to return all found peers.
resolves https://github.com/libp2p/go-libp2p/issues/2859

fix(discovery): allow FindPeers limit to be 0

---

examples/chat-with-mdns/flags.go

Make sure it properly works if you start multiple instances on the same machine.

examples/chat-with-mdns: default to a random port

---

config/config.go
libp2p_test.go
p2p/net/swarm/swarm_listen.go
p2p/transport/quic/transport.go
p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/nonquic_packetconn.go
p2p/transport/webrtc/transport.go
p2p/transport/webrtc/transport_test.go

This lets users listen on the same port for WebRTC and QUIC. Kubo folks asked for this as it would be very beneficial to their deployment.
One open question for me is:
- Do we need to make sure this works well with the Observed Address Manager? I think it should just work, but we should double check. Ideally we should know our public webrtc-direct address if we've discovered our public quic address when they use the same port.

feat: WebRTC reuse QUIC conn

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_test.go

The Observed Address manager can now infer external addresses for transports that share the same listening address if another transport has an observation. 
For example, say I'm listening on UDP 0.0.0.0:4001 for QUIC, WebTransport, and WebRTC. And I learn that my external IP address for QUIC is 5.4.3.2:4001 (as reported by my peers). This means I can infer that my external WebTransport and WebRTC addresses are also 5.4.3.2:4001 since these other transports are using the same underlying socket.
This PR also removes the old hack that inferred WebTransport address. It was hacky because we didn't have access to the connection of external <-> local address like the observed address manager does.

ObsAddrManager: Infer external addresses for transports that share the same listening address.

---

config/config.go
libp2p_test.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

Using the `BasicHost` constructor transfers the ownership of the swarm. This is similar to how using `libp2p.New` transfers the ownership of user provided config options like `ResourceManager`, all of which are closed on `host.Close`.
closes #2911

basic_host: close swarm on Close

---

p2p/transport/webrtc/logger.go

webrtc: reduce loglevel for pion logs

---

p2p/net/swarm/black_hole_detector.go
p2p/net/swarm/black_hole_detector_test.go
p2p/net/swarm/swarm_metrics.go
p2p/net/swarm/swarm_metrics_test.go

This commit changes the `blackHoleState` type from private to public by renaming it to `BlackHoleState`. This modification allows other packages to access and use this type, which is essential for monitoring and debugging purposes within the libp2p system.
Related issue: #2890

metrics: BlackHoleState type public

---

p2p/transport/webrtc/transport_test.go

See failure log here: https://gist.github.com/MarcoPolo/7946a7a5d76e8c49b8f1873029c41a64
I don't know for sure why this failed without diving deep into the Pion stack, by my initial guess is that we close before the listener gets into a state it can fulfill the Accept call. If that's the case, simply waiting for the other side to have Accepted the conn would fix the issue.

test: Try to fix test timeout

---

scripts/test_analysis/main.go

This updates the test_analysis script to fail when a test times out. Not bothering retrying this since that could take a while, and we should prioritize fixing tests that fail and stall the pipeline.

ci: Fail on test timeout

---

p2p/transport/webrtc/listener.go

This should fix #2930. In any case, this is the correct change. No need to drop the connection after 20 seconds.

webrtc: wait for listener context before dropping connection

---

libp2p_test.go
p2p/transport/quic/transport.go
p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/connmgr_test.go
p2p/transport/quicreuse/reuse.go
p2p/transport/quicreuse/reuse_test.go
p2p/transport/webtransport/transport.go

Fixes #2913 
The issue is presented in https://github.com/libp2p/go-libp2p/issues/2913#issuecomment-2305818394.
The fix here introduces "associations" to refcountedTransports. a libp2p transport can associate itself with the transport used for listening, and then prefer to use that for dialing by passing itself as the association.

fix: QUIC/Webtransport Transports now will prefer their owned listeners for dialing out

---

p2p/protocol/holepunch/svc.go
p2p/protocol/holepunch/util.go

This change attempts to fix #2913.
In essence, it enables the `dctur` protocol, when a peer has a public IP (if it's bound to an interface with a public IP) without having to wait for an identify response (which would then make the public address visible via `OwnObservedAddrs()`).
- The `OwnObservedAddrs()` function in the identify service (which we rely on in the holepunch service) seems to **not** return observed addresses if they aren't dialable. Why is that? 
- Should be fixed by https://github.com/libp2p/go-libp2p/pull/2936

fix: enable dctur when interface address is public 

---

funding.json

This funding.json file is added here in order to apply for Optimism's rPGF round 5: https://retrofunding.optimism.io/application/5
The application process requires this file to exist in public github repositories that are linked to applications.
The go-libp2p repo will be listed in IP Shipyard's application for round 5.
The contents of this file were autogenerated:

chore: add a funding JSON file to apply for Optimism rPGF round 5

---

README.md
ROADMAP.md

Users and contributors can view roadmap in Github issues.

chore: remove Roadmap file

---

p2p/transport/quic/listener.go
p2p/transport/quic/transport.go
p2p/transport/quic/virtuallistener.go
p2p/transport/quicreuse/config.go
p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/quic_multiaddr.go

start from quic-go@0.47.0, quic.VersionNumber has been officially removed, commit can be seen at https://github.com/quic-go/quic-go/pull/4627

fix: use quic.Version instead of the deprecated quic.VersionNumber

---

p2p/net/connmgr/connmgr.go

Method UntagPeer() logs an "info" log message whenever it's called for a peer that is untracked. It generates a lot of noise in the logs for something that is basically harmless.
This commit reduces the log level to "debug" for this message.

connmgr: reduce log level for untagging untracked peers

---

.github/workflows/interop-test.yml

As we're setting up a new cache bucket, we'd like to be able to control its' configuration via GitHub vars/secrets fully.

chore: parameterise s3 build cache setup

---

core/peerstore/peerstore.go
p2p/host/basic/basic_host.go
p2p/host/peerstore/pstoremem/addr_book.go
p2p/host/peerstore/pstoremem/addr_book_test.go
p2p/host/peerstore/pstoremem/inmem_test.go

Closes #1698 
Makes GC ~60x faster (on my synthetic benchmark) under certain circumstances. So by that logic, it should be fine to run this more often.
Adds a min heap list to track the next address to expire. This lets us short circuit gc if we see the next address to expire isn't expired yet.
Also bumps the gc interval from 60 minutes to 1 minute. This should be fine since we don't traverse every address anymore.
This relies on existing tests to assert nothing has broken.
Of course there are many more improvements that could be made. See the linked issue for inspiration. The next lowest hanging fruit is to do something similar to this across peers.

fix: Better GC in membacked peerstore

---

go.mod
p2p/transport/websocket/listener.go

Does what it says on the box 😅.
The motivation behind this change is that while implementing https://github.com/ipfs/kubo/pull/10521 I noticed a large number of logs of the form `"http: TLS handshake error from ip:port: EOF"` and I couldn't control them in the same way I can logs for any other transport.
This error in particular is one I don't expect many folks have run into since my understanding is that the WSS listener within go-libp2p is not highly utilized with many applications dependent on WSS choosing to use WS + do TLS termination in front of the libp2p node instead. However, in the linked issue the idea is to do the TLS termination within go-libp2p and so the issue becomes apparent.

feat(websocket): switch the underlying http server logger to use ipfs/go-log

---

p2p/transport/websocket/websocket_test.go

Looking through the code I saw this test was disabled, I tried re-enabling and it seems to work locally as long as we pass a proper peerID. The linked issue didn't say this test was flaky so it it's passing might be good to re-enable it. If so we should probably add a WSS version of the test as well

fix(websocket): re-enable websocket transport test

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

fixes: https://github.com/libp2p/go-libp2p/issues/2972

basichost: ensure no duplicates in Addrs output

---

p2p/protocol/circuitv2/relay/constraints.go
p2p/protocol/circuitv2/relay/constraints_test.go
p2p/protocol/circuitv2/relay/relay.go
p2p/protocol/circuitv2/relay/resources.go

We only need 1 reservation per peer.
This PR also proactively removes relay reservations on disconnecting from the peer. This helps when the relay client is restarting frequently.
Fixes: https://github.com/libp2p/go-libp2p/issues/2963

relay: make only 1 reservation per peer

---

p2p/protocol/circuitv2/relay/relay.go
p2p/protocol/circuitv2/relay/relay_priv_test.go

fix: circuitv2: sanitize address inputs: check address peer id when returning a reservation message

---

core/transport/transport.go
libp2p_test.go
p2p/net/swarm/swarm_dial.go
p2p/protocol/circuitv2/client/transport.go
p2p/protocol/circuitv2/relay/relay.go
p2p/protocol/circuitv2/relay/relay_priv_test.go

Fixes an issue where the implied SNI is dropped when connecting over a p2p-circuit address. For example if you connected to a peer over `/dns/example.com/wss/p2p/qmFoo/p2p-circuit/p2p/qmTarget` the swarm would resolve example.com without preserving the SNI information needed for `WSS`. The WebSocket transport would only get the IP address of example.com without knowning the host name it needed to use for the SNI.
We had the same problem previously when dialing a wss address. See https://github.com/libp2p/go-libp2p/issues/1597. This was fixed by letting transports resolve the multiaddr instead of the swarm. This case is similar, except that we want to tell the swarm to just skip resolving altogether since the inner transport will resolve the multiaddr later.

feat: core/transport: Add SkipResolver interface

---

p2p/host/basic/basic_host.go
p2p/host/basic/internal/backoff/backoff.go
p2p/host/basic/internal/backoff/backoff_test.go

fix: basichost: Add backoff for updating local IP addresses on error

---

p2p/host/basic/basic_host.go
p2p/protocol/holepunch/holepunch_test.go
p2p/protocol/holepunch/holepuncher.go
p2p/protocol/holepunch/svc.go
p2p/protocol/holepunch/util.go

holepuncher: pass address function in constructor

---

dashboards/swarm/swarm.json
p2p/net/swarm/dial_worker.go
p2p/net/swarm/swarm_metrics.go
p2p/net/swarm/swarm_metrics_test.go

swarm: add a peer dial latency metric

---

config/config.go
core/host/host.go
p2p/host/autonat/autonat.go
p2p/host/autonat/autonat_test.go
p2p/host/autonat/client.go
p2p/host/autonat/options.go
p2p/host/autorelay/autorelay.go
p2p/host/autorelay/relay.go
p2p/host/basic/basic_host.go
p2p/protocol/holepunch/holepunch_test.go
p2p/protocol/holepunch/holepuncher.go
p2p/protocol/holepunch/svc.go
p2p/protocol/holepunch/util.go

autonat: fix interaction with autorelay

---

config/config.go
fx_options_test.go
options.go

While doing some refactoring of the p2p-forge client, I found that I wanted a way to get access to parts of the host earlier than `.New()` returning. I also wanted an option I could provide the constructor that would give me the host (or peer.ID, or something else) without having to have the user explicitly pass it to me.
In other words I think it's nicer to do this:
```go
// someServiceThatDependsOnHostAndConfiguresHost
service := NewServiceThatDependsOnHostAndConfiguresHost()
h, err := New(service.Libp2pOptions())
```
Rather than
```go
// someServiceThatDependsOnHostAndConfiguresHost
service := NewServiceThatDependsOnHostAndConfiguresHost()
h, err := New(service.Libp2pOptions())
service.ProvideHost(h)
```
And this change would enable the former (along with many other things as well). …

feat: Add WithFxOption

---

p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

in case no timeout was provided via context.
Closes #3019

fix: basichost: Use NegotiationTimeout as fallback timeout for NewStream

---

p2p/host/eventbus/basic.go
p2p/host/eventbus/basic_test.go

Slow consumers can stall libp2p in hard to debug ways. For example, a slow consumer of Identify events can prevent NewStreams from opening. In some cases we do want this back-pressure, but in other cases it is a bug in the user's application (or even in go-libp2p). The recommended approach has been to use metrics with Grafana and Prometheus to identify these issues. In practice, that's been a non-trivial task for users to setup. A simple log would help identify these issues.
Note that the codepath is relatively unchanged in the normal case. Only if a producer is stalled will the extra work be put in.
Closes #2361 . See my comment https://github.com/libp2p/go-libp2p/issues/2983#issuecomment-2463270292 for why this is brought up again.
@vyzo Could you please try to repro your issue on this …

feat: eventbus: log error on slow consumers

---

p2p/net/swarm/swarm_dial.go

Fix incorrect error message format order, which will cause error message not displayed correctly

fix(swarm): incorrect error message format order

---

p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_glass_test.go

These observations are telling us what the relay's IP address is. This isn't useful for us at all.
This also solves an issue during hole punching where we may report the relay's address as our own.

fix(obsaddr): do not record observations over relayed conn

---

p2p/protocol/holepunch/tracer.go

- Introduced the `peerInfo` struct to encapsulate peer metadata.
- Updated the `peers` map in the `tracer` struct to use `peerInfo`.
- Simplified code by avoiding inline struct definition for peers.

fix(holepunch/tracer): replace inline peer struct with peerInfo type

---

core/routing/routing.go

The ContentRouting interface does too much. One can think of systems that only Provide, and systems that only FindProviders.
Therefore I am proposing to split it further. While this can be done on user-code, core/routing interfaces are canonical and it is better to use interfaces coming from here.
As someone said: the best interface is that which does as little as possible.

refactor(core/routing): split ContentRouting interface

---

go.mod
go.sum
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/http/example_test.go
p2p/protocol/circuitv2/relay/relay.go
p2p/protocol/identify/obsaddr.go
p2p/protocol/identify/obsaddr_glass_test.go
p2p/transport/webrtc/listener.go
p2p/transport/webtransport/conn.go
test-plans/go.mod
test-plans/go.sum

This patch release should help solve some issues we've seen in WebRTC.

Release v0.37.1

---

p2p/transport/tcpreuse/demultiplex.go
p2p/transport/tcpreuse/listener.go
p2p/transport/tcpreuse/listener_test.go

There was an oversight here in the error reporting. A test should be added, but also probably this should've been caught by automated tooling (e.g. one of the linters), maybe there are more we should be enabling.

fix(tcpreuse): handle connection that failed to be sampled

---

dashboards/prometheus.yml

The error message was:
Error loading config (--config.file=/etc/prometheus/prometheus.yml): expected Alertmanager API version to be one of [v2] but got v1

chore(dashboard/alertmanager): update api version from v1 to v2

---

p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

This should match the semantics of the Go stdlib http server .Close which always returns an error

fix(libp2phttp): Return ErrServerClosed on Close

---

config/config.go
p2p/host/basic/basic_host.go

In some cases, `AddrsFactory` may return a reusable slice. This slice should not be modified.
In `BasicHost.Addrs()`, the slice was already being cloned before being passed to `ma.Unique()` (updated this place to use `slices.Clone()` function), but in other places, the slice was being modified without being cloned, which in some cases could lead to crashes / unpredictable behavior.

fix: avoid modifying slice returned by AddrsFactory

---

core/peer/pb/peer_record.pb.go
core/peer/pb/peer_record.proto

The previous link has expired and has been replaced with the latest address.

chore: fix broken link to record envelope protobuf file

---

p2p/net/swarm/dial_ranker.go
p2p/net/swarm/dial_ranker_test.go
p2p/net/swarm/dial_worker.go
p2p/test/basichost/basic_host_test.go

Previously these addresses weren't delayed at all. When I initially did the ranker implementation, I was too conservative regarding what to delay. So, non QUIC, WebTransport, TCP, WS addresses were ignored in ranking. We only ever need to dial /webrtc-direct when there's no other address available for the peer, in which case we will dial the addresses immediately.
This would have helped with https://github.com/libp2p/js-libp2p/issues/2805 as there would have been fewer peers dialing webrtc and then cancelling because they connected on a better transport.
This also introduces an additional 1 second delay for any fancy non IP transports

swarm: delay /webrtc-direct dials by 1 second

---

p2p/host/peerstore/pstoremem/peerstore.go
p2p/host/peerstore/pstoremem/peerstore_test.go

The constructor starts a goroutine, so we should pass these in the constructor.

peerstore: pass options to addrbook constructor

---

p2p/net/swarm/swarm.go

This causes discrepancy when the connection is closed before being added to the swarm. This happens only in dial_worker loop when adding to the swarm fails. It's nicer to fix this with a once than to ensure that Close is never called twice within the swarm.
Previously, we did something similar here for tcp connection metrics:
https://github.com/libp2p/go-libp2p/pull/2953/files

swarm: record conn metrics only once

---

p2p/host/peerstore/test/benchmarks_suite.go
p2p/host/peerstore/test/utils.go

The previous code was not accounting accurately for the time spent generating test cases. In the benchmark output below the difference between 100 address per peer suite is huge:
```
BenchmarkInMemoryPeerstore/SetAddrs-100Addrs-InMem-16              10000	    190198 ns/op
vs
BenchmarkInMemoryPeerstore/SetAddrs-100-16                	   10000	     42710 ns/op
```
old benchmark:
```
goos: linux
goarch: amd64
pkg: github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem
cpu: AMD Ryzen 7 7840U w/ Radeon  780M Graphics
BenchmarkInMemoryPeerstore
BenchmarkInMemoryPeerstore/AddAddrs-1Addrs-InMem
BenchmarkInMemoryPeerstore/AddAddrs-1Addrs-InMem-16         	   10000	      4158 ns/op
BenchmarkInMemoryPeerstore/AddAddrs-10Addrs-InMem
BenchmarkInMemoryPeerstore/AddAddrs-10Addrs-InMem-16 …
```

peerstore: fix addressbook benchmark timing

---

p2p/host/peerstore/pstoremem/addr_book.go
p2p/host/peerstore/test/benchmarks_suite.go

depends on #3092 
My intuition here was way off. The method spends most of the time either doing multiaddr ops or manipulating the heap(see the flamegraph). We don't need the sync.Pool. There's only a 5% difference without the pool. 
```
goos: linux
goarch: amd64
pkg: github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem
cpu: AMD Ryzen 7 7840U w/ Radeon  780M Graphics     
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
InMemoryPeerstore/GetAndClearAddrs-1-16     8.351µ ± 2%   8.711µ ± 6%  +4.31% (p=0.019 n=10)
InMemoryPeerstore/GetAndClearAddrs-10-16    49.04µ ± 1%   49.75µ ± 1%  +1.45% (p=0.000 n=10)
InMemoryPeerstore/GetAndClearAddrs-100-16   462.6µ ± 1%   495.5µ ± 3%  +7.10% (p=0.000 n=10)
geomean …
```

peerstore: remove sync.Pool for expiringAddrs

---

p2p/host/autorelay/relay_finder.go

Moves the cleanup of disconnected peers to its own Goroutine to consume these events in a timely manner (and avoid stalling libp2p).
The delay from consuming the events is likely from the `refreshReservations` that happens in the work loop.

fix(autorelay): Move relayFinder peer disconnect cleanup to separate goroutine

---

p2p/http/auth/auth_test.go
p2p/http/auth/server.go

I originally wrote this code assuming the hmac object was copied by value, but it's an interface. Concurrent requests were using the same pointer.

fix(httpauth): Correctly handle concurrent requests on server

---

.github/workflows/release-check.yml

@MarcoPolo Are we ready to get back to the main release track or is there some feature missing that you'd like us to add there?

ci: get back on the main release track of release checker

---

p2p/transport/tcp/metrics_test.go
p2p/transport/tcp/metrics_unix_test.go

This test works on all platforms. It tests for transport correctness in case we have metrics enabled. 
This removes the incorrect directive(whitespace in front of the name) and the platform specific file suffix.

tcp: fix metrics test build directive

---

p2p/net/nat/nat.go
p2p/net/nat/nat_test.go

closes: https://github.com/libp2p/go-libp2p/issues/3057
rest of the work is in: https://github.com/libp2p/go-libp2p/pull/3075

nat: ignore mapping if external port is 0

---

p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/connmgr_test.go
p2p/transport/quicreuse/listener.go
p2p/transport/quicreuse/nonquic_packetconn.go
p2p/transport/quicreuse/reuse.go

It would be nice if the application was able to construct its own `quic.Transport`, and have that transport used by libp2p.
This would allow an application:
* on the listener side: inject its own `tls.Config` on the `Listen` call, and `Accept` (a subset of) QUIC connections returned by the listener
* on the client side: dial QUIC connections without going through libp2p at all
This would make it possible to run a vanilla HTTP/3 server behind a NAT / firewall and use libp2p's NAT hole punching mechanism to create the NAT bindings.

quicreuse: make it possible to use an application-constructed quic.Transport

---

p2p/net/swarm/swarm_dial_test.go

We shouldn't be actually resolving DNS names for this test. The failure was due to example.com updating their A and AAAA records.

test: fix failing test

---

p2p/net/nat/nat.go

fix https://github.com/libp2p/go-libp2p/issues/3139

fix(net/nat): data race problem of `extAddr`

---

p2p/test/transport/transport_test.go
p2p/transport/tcp/metrics.go

Yet another interface embedding bug.
Running all transport integration tests is a bit overkill, but the rcmgr transport integration test is the only one that tests for this behavior.

tcpreuse: fix rcmgr accounting when tcp metrics are enabled

---

p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go

closes https://github.com/libp2p/go-libp2p/issues/286 (a 7 year old issue??)
This PR allows users to use a SOCKS5 proxy when dialing `/wss` addresses by using the `HTTPS_PROXY` environment variable. 
Here's an example using vole to dial through a socks proxy:
```
HTTPS_PROXY="socks5://127.0.0.1:9081" vole libp2p ping /dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb
```

feat(transport/websocket): support SOCKS proxy with wss

---

go.mod
go.sum
p2p/transport/quic/stream.go
p2p/transport/webtransport/crypto.go
p2p/transport/webtransport/transport_test.go
test-plans/go.mod
test-plans/go.sum

Small breaking change around Errors.Is for StreamError

Update quic-go to v0.49.0

---

libp2p_test.go
p2p/transport/tcp/tcp.go
p2p/transport/tcp/tcp_test.go

closes #3155. @parkan does this work for your use case? See the libp2p_test.go for an example on how to set this up.

feat: Implement Custom TCP Dialers

---

p2p/net/swarm/swarm_transport.go

There's no reason to log this error here, this is perfectly legal. We can make it a debug statement, but even that seems not useful.

swarm: remove unnecessary error log

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/internal/user-agent/user_agent.go

test(p2p/protocol/identify): Fix user agent assertion in Go 1.24

---

p2p/test/transport/gating_test.go
p2p/test/transport/transport_test.go
p2p/transport/tcpreuse/connwithscope.go
p2p/transport/tcpreuse/listener.go
p2p/transport/websocket/conn.go
p2p/transport/websocket/listener.go

Yet another interface embedding bug :sob:

tcpreuse: fix Scope() for *tls.Conn

---

p2p/net/swarm/swarm.go

When I tested the relay connection with the new version, I was able to successfully connect to the server peer, but a `context deadline exceeded` error occurred when calling `NewStream` because `WithAllowLimitedConn` was not used.
This error caused me trouble, and I finally found that it was a timeout in `waitForDirectConn` (because my environment could not successfully holepunch).
Logging the errors returned by waitForDirectConn can help more developers locate errors and know through code logic that WithAllowLimitedConn is needed.

feat(swarm): logging waitForDirectConn return error

---

p2p/protocol/autonatv2/options.go
p2p/protocol/autonatv2/server.go
p2p/protocol/autonatv2/server_test.go

This fixes the flaky test:
TestServerDialData(https://github.com/libp2p/go-libp2p/issues/3179) The exact sequence of events that flakiness is:
The client rejects the dial data request by resetting the stream. The client makes a new request to the server. The server rejects this request as it hasn't read the previous stream's reset yet.
It is better to allow multiple concurrent requests per peer. 5 concurrent requests per peer is okay.

autonatv2: allow multiple concurrent requests per peer

---

p2p/host/basic/basic_host.go

There is no reason to copy this slice. This is always called with a new slice that's not shared with anything else.
fixes: #3198

basichost: add certhashes to addrs in place

---

p2p/http/auth/auth_test.go
p2p/http/auth/client.go
p2p/http/auth/server.go
p2p/http/example_test.go
p2p/http/libp2phttp.go
p2p/http/libp2phttp_test.go

Auth is now uniform across HTTP and stream transports and easier to use. See `ExampleHost_authenticatedHTTP` for an example. This will also show up in the docs page.
Adds:
- `ServerPeerID()` function to get a server's peer id from an `*http.Response`. Used by clients.
- `ClientPeerID()` function to get a client's peer id from an `*http.Request`. Used by servers.
- `ServerPeerIDAuth` and `ClientPeerIDAuth` fields in the http.Host struct, to specify the key used to authenticate.

feat(libp2phttp): More ergonomic auth

---

p2p/host/autonat/autonat.go
p2p/net/simconn/router.go
p2p/net/simconn/simconn.go
p2p/net/simconn/simconn_test.go
p2p/protocol/holepunch/holepunch_test.go
p2p/protocol/holepunch/holepuncher.go
p2p/protocol/holepunch/svc.go
p2p/protocol/holepunch/util.go
p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/options.go
p2p/transport/quicreuse/reuse.go
p2p/transport/quicreuse/reuse_test.go

Previously this PR sought to migrate away from the legacy behavior. Now it just tests the hole punching behavior using a simulated network. It also adds a flag to control the legacy behavior, but this is set to default to the current behavior.
Most of the code introduced here is related to the new `simconn` package which lets us create simulated UDP connections for use with the QUIC transport. This lets us set up arbitrary networks to test holepunching. The End to End test now places hosts A and B behind a firewall that requires holepunching for a direct connection.
The plan is to merge this PR to actually test holepunching, then #3171 by coming up with a migration strategy and use these tests to verify the strategy.

fix(dcutr): Fix end to end tests and add legacy behavior flag (default=true)

---

p2p/net/conngater/conngater.go

Since we have already checked err before and returned != nil, err must be nil here. In fact, it should return `r.Error`.

fix: fix incorrect nil return value

---

p2p/http/libp2phttp.go

`libp2phttp.streamRoundTripper.RoundTrip` uses a context from `http.Request` when establishing a new stream.
Suppose a user expects to fetch very large files with multiplexed http so they set very large timeout into `http.Request` context. Then suppose one of the servers does not respond to protocols negotiation for some reason (for example by reaching out max connections set via resource manager).
This makes `NewStream` to stuck in reading server response for potentially for very long time until the context with high timeout value expires.
Tested manually.

fix(libp2phttp): bound NewStream timeout

---

p2p/transport/webrtc/udpmux/mux.go
p2p/transport/webrtc/udpmux/mux_test.go
p2p/transport/webrtc/udpmux/muxed_connection.go

This context wasn't being cancelled on all code paths. In particular, contexts for connections that didn't complete negotiation were not being cancelled.
The change arranges for either udpmux.muxedConnection.Close or  RemoveConnByUfrag to call the other.
Fixes: #3223

webrtc: fix memory leak with udpmux.muxedConnection context

---

p2p/protocol/holepunch/holepunch_test.go
p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/connmgr_test.go
p2p/transport/quicreuse/reuse.go

The second listen for the same IP:Port combination doesn't get tagged with the association. So if you listen on webtransport after quic, the wt dials won't reuse the transport. 
We should refactor this is bit more, but any change will probably change the refCountedTransport interface which is returned from one public method, so I'd like to do that in a separate PR, and use this for a patch release.  
This probably impacts: #3165

connmgr: fix transport association bug

---

p2p/transport/webtransport/stream.go

fix: Add wrapped error type in `stream.go`

---

p2p/protocol/autonatv2/server.go
p2p/protocol/autonatv2/server_test.go

The policy was comparing the connection local addr to the observed addr. This should be comparing the connection remote addr to the requested dial addr.
The impact here is:
if we refresh reachability for addresses every hour, we will be spending 100kB per address per hour. That's equivalent to 30 B/s. For 10 addrs  this will be 300 B/s or 3kb/s

autonatv2: fix server dial data request policy

---

p2p/protocol/autonatv2/server.go
p2p/protocol/autonatv2/server_test.go

We do allow dns addrs for autonatv2. This function handles them correcly, but the comment is wrong, and the handling is accidental.  Make it explicity.

autonatv2: explicitly handle dns addrs

---

config/config.go
core/transport/transport.go
p2p/net/upgrader/listener.go
p2p/net/upgrader/listener_test.go
p2p/net/upgrader/upgrader.go
p2p/protocol/circuitv2/client/transport.go
p2p/test/transport/gating_test.go
p2p/transport/tcp/metrics.go
p2p/transport/tcp/metrics_none.go
p2p/transport/tcp/metrics_test.go
p2p/transport/tcp/tcp.go
p2p/transport/tcpreuse/connwithscope.go
p2p/transport/tcpreuse/listener.go
p2p/transport/tcpreuse/listener_test.go
p2p/transport/websocket/addrs_test.go
p2p/transport/websocket/conn.go
p2p/transport/websocket/listener.go
p2p/transport/websocket/websocket.go
p2p/transport/websocket/websocket_test.go

This introduces a new GatedMaListener type which gates conns
accepted from a manet.Listener with a gater and creates the rcmgr
scope for it. Explicitly passing the scope allows for many guardrails
that the previous interface assertion didn't.
This breaks the previous responsibility of the upgradeListener method
into two, one gating the connection initially, and the other upgrading
the connection with a security and muxer selection.
This split makes it easy to gate the connection with the resource
manager as early as possible. This is especially true for websocket
because we want to gate the connection just after the TCP connection is
established, and not after the tls handshake + websocket upgrade is
completed.
fixes: #3182

transport: add GatedMaListener type

---

p2p/transport/quicreuse/tracer_test.go

logs:
```
➜  go-libp2p git:(master) ✗ go test -v ./p2p/transport/quicreuse/  -run '' 
=== RUN   TestListenOnSameProto
=== RUN   TestListenOnSameProto/with_reuseport
=== RUN   TestListenOnSameProto/without_reuseport
--- PASS: TestListenOnSameProto (0.02s)
--- PASS: TestListenOnSameProto/with_reuseport (0.01s)
--- PASS: TestListenOnSameProto/without_reuseport (0.01s)
=== RUN   TestConnectionPassedToQUICForListening
--- PASS: TestConnectionPassedToQUICForListening (0.00s)
=== RUN   TestAcceptErrorGetCleanedUp
connmgr_test.go:113: num goroutines: 7
connmgr_test.go:127: num goroutines: 7
--- PASS: TestAcceptErrorGetCleanedUp (0.00s)
=== RUN   TestConnectionPassedToQUICForDialing
--- PASS: TestConnectionPassedToQUICForDialing (0.00s)
=== RUN   TestListener
=== RUN   TestListener/with_reuseport …
```

optimize: using t.TempDir() replace os.MkdirTemp in testfile

---

p2p/host/autorelay/relay_finder.go

This PR fixes a data race condition in the relay finder. It was observed [here](https://github.com/pactus-project/pactus/actions/runs/14100227555/job/39494949146?pr=1713#step:4:511).  
The `cleanupDisconnectedPeers` function deletes `rf.relays` while, at the same time, `getCircuitAddrs` iterates over the map.  
This PR adds a lock in `getCircuitAddrs` to ensure it iterates over the map only when it is unlocked.

fix(relay): fix data-race in relayFinder

---

p2p/protocol/identify/id.go
p2p/protocol/identify/id_test.go
p2p/protocol/identify/opts.go

The max message size is about 100kB. 5 seconds are enough to transfer this.

identify: reduce timeout to 5 seconds

---

p2p/host/resource-manager/conn_limiter.go
p2p/host/resource-manager/conn_limiter_test.go

We're converting this prefix to string for storing in maps. There's no need to, as netip.prefix is a value type that can be used as a key. 
No functional change expected.

rcmgr: use netip.Prefix as map key instead of string

---

.github/workflows/go-check.yml
.golangci.yml
p2p/protocol/autonatv2/server.go
p2p/protocol/autonatv2/server_test.go

Configures ci to use golang-ci for linting. 
The workflow is copied from quic-go. The os specific checks don't add too much value, I guess. I am fine with keeping only linux. 
I couldn't get the unparam linter to detect unused parameters in functions. I guess it is aggressive about not raising failse positives. Using revive for unparam check. 
I fear errcheck may be too much some times. We can disable / configure that one when we come across a change that warrants it. 
See: https://github.com/libp2p/go-libp2p/actions/runs/14307422981/job/40094362132?pr=3269
for a failure. 
See: #1843 for past discussion on this.  
Fixes: #3248

ci: add golangci-lint for linting

---

p2p/net/nat/nat.go

This pull requestenhances the logging for NAT port mapping failures by replacing the
TODO with structured error logs that include more context. The improved logs now
contain the protocol, internal port, and specific error information, making it
easier to diagnose NAT-related issues. The log level was also upgraded from
warning to error to better reflect the severity of port mapping failures.

fix: Improve NAT port mapping failure logging

---

p2p/host/peerstore/pstoreds/addr_book_gc.go

This PR replaces a `// TODO` comment with an actual log statement in the `purgeStore()` method of the `dsAddrBookGc`:
- Added a `log.Warnf` when `proto.Unmarshal` fails during garbage collection:
```go
log.Warnf("failed to unmarshal record during GC purge: key=%s, err=%v", result.Key, err)
```

Add missing log for failed GC record unmarshalling in `purgeStore()`

---

p2p/transport/quicreuse/connmgr.go
p2p/transport/quicreuse/connmgr_test.go
p2p/transport/quicreuse/listener.go
p2p/transport/quicreuse/nonquic_packetconn.go
p2p/transport/quicreuse/reuse.go
p2p/transport/quicreuse/reuse_test.go

This adds some helpful documentation for the package and explicitly specifies the reuse and association logic for `ListenQUICAndAssociate` and `DialQUIC`. 
There's a minor refactoring where I've removed a redundant packet conn which is supposed to always be `quic.Transport.Conn`
I'd prefer renaming `ConnManager` to `SharedQUIC` which is more suggestive of the functionality, but that's for later.

quicreuse: add some documentation for the package

---

p2p/host/eventbus/basic.go
p2p/host/eventbus/basic_test.go

Change event bus slow consumer event logging from `ERROR` to `WARN`.
`WARN` seems more appropriate since this isn't an error.
Closes https://github.com/ipfs/kubo/issues/10778

eventbus: change slow consumer event from error to warn

---

.github/workflows/link-check.yml

The existing checker is consistently failing

chore: use tcort/github-action-markdown-link-check

---

.golangci.yml
config/config.go
core/event/reachability.go
p2p/host/basic/addrs_manager.go
p2p/host/basic/addrs_manager_test.go
p2p/host/basic/addrs_reachability_tracker.go
p2p/host/basic/addrs_reachability_tracker_test.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go
p2p/protocol/autonatv2/autonat.go
p2p/protocol/autonatv2/autonat_test.go
p2p/protocol/autonatv2/client.go
p2p/protocol/autonatv2/options.go
p2p/protocol/autonatv2/server.go
p2p/protocol/autonatv2/server_test.go

This introduces `addrsReachabilityTracker` that tracks reachability on
a set of addresses. It probes reachability for addresses periodically
and has an exponential backoff in case there are too many errors
or we don't have any valid autonatv2 peer. 
There's no smartness in the address selection logic currently. We just
test all provided addresses. It also doesn't use the addresses provided
by `AddrsFactory`, so currently there's no way to get a user provided
address tested for reachability, something that would be a problem for 
dns addresses. I intend to introduce an alternative to 
`AddrsFactory`, something like, `AnnounceAddrs(addrs []ma.Multiaddr)`
that's just appended to the set of addresses that we have, and check
reachability for those addresses. 
There's only one method exposed in …

basichost: use autonatv2 to verify reachability

---

p2p/net/mock/mock_peernet.go

This is causing a regression in kubo(https://github.com/ipfs/kubo/pull/10835#pullrequestreview-2914948501) with the new addrs manager which depends on being notified of new listen addresses instead of recomputing all the host's addresses every time on every `host.Addrs` call.

mocknet: notify listeners on listen

---

p2p/host/basic/addrs_manager.go
p2p/host/basic/addrs_manager_test.go
p2p/host/basic/basic_host.go
p2p/net/swarm/swarm.go
p2p/net/swarm/swarm_test.go

The simplified idea here is: if we can listen on the addr, we should try adding certhashes to the addr. 
This removes dependency on WebTransport and WebRTC Transports.

swarm: move AddCertHashes to swarm

---

p2p/transport/quicreuse/reuse.go

Refactored Close to use errors.Join for combining transport and packet connection closure errors

refactor(quicreuse): use errors.Join in Close method

---

p2p/protocol/circuitv2/relay/options.go
p2p/protocol/circuitv2/relay/relay.go
p2p/protocol/circuitv2/relay/relay_priv_test.go

Moved the code in my fork to its own branch. GitHub automatically closed [old](https://github.com/libp2p/go-libp2p/pull/3365)
https://github.com/libp2p/go-libp2p/issues/3361
Private based relays are unable to populate the `Reservation.Addrs` when non of its addresses are public.
Permit the relay to respond with all its public addresses which is already filtered with the following line:
https://github.com/libp2p/go-libp2p/blob/f6c14a215b2012f3839f1b7157dfec70a772143a/p2p/protocol/circuitv2/relay/relay.go#L596
But also include those addresses shared with the connected peer. This could be performed by comparing `stream.Conn().RemoteMultiaddr()` and `stream.Conn().LocalMultiaddr()`. 
Even so, **what about including all of its addresses with filtering?** Is there any security consideration. …

 enhancement: include non public relay addresses to be advertised too #3361 #3365 

---

p2p/discovery/mdns/mdns_test.go
p2p/host/basic/natmgr.go
p2p/net/nat/nat.go
p2p/net/nat/nat_test.go

This PR makes NAT port mappings self-healing after router restarts.
It also adds bunch of tests and eliminates duplicate mapping requests that occur on node start.
Router restarts can cause UPnP (SOAP) services to change their listening ports, leading to "connection refused" errors that permanently break port mappings. 
This is the problem described in https://github.com/libp2p/go-libp2p/issues/3224#issuecomment-2866844723 (cc @sukunrt @MarcoPolo)
We had Kubo users impacted this since forever, impacting their ability to provide data:
- https://github.com/ipfs/kubo/issues/8963
- https://github.com/ipfs/kubo/issues/9759
This PR implements automatic NAT rediscovery that detects consecutive connection failures, triggers rediscovery after 3 failures, and restores all existing port mappings on …

fix: self-healing NAT mappings with request deduplication

---

libp2p_test.go
p2p/discovery/backoff/backoffcache_test.go
p2p/discovery/routing/routing_test.go
p2p/host/autonat/svc_test.go
p2p/host/basic/basic_host_test.go
p2p/net/gostream/gostream_test.go
p2p/net/pnet/psk_conn_test.go
p2p/net/swarm/limiter_test.go
p2p/net/swarm/swarm_net_test.go
p2p/protocol/circuitv2/relay/relay_test.go
p2p/protocol/identify/id_test.go
p2p/protocol/ping/ping_test.go
p2p/test/backpressure/backpressure_test.go
p2p/test/transport/transport_test.go

Optimize code using a more concise and modern approach.

refactor: replace context.WithCancel with t.Context

---

scripts/download-protoc.sh

I forgot macOS runs an old version of bash

chore: add help comment

---

p2p/protocol/autonatv2/server.go

fixes: https://github.com/ipfs/kubo/issues/10992
```
caught panic: assignment to entry in nil map
goroutine 40717 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:26 +0x64
github.com/libp2p/go-libp2p/p2p/protocol/autonatv2.(*server).handleDialRequest.func1()
github.com/libp2p/go-libp2p@v0.43.0/p2p/protocol/autonatv2/server.go:96 +0x44
panic({0x1042e9c20?, 0x105b46720?})
runtime/panic.go:783 +0x120
github.com/libp2p/go-libp2p/p2p/protocol/autonatv2.(*rateLimiter).CompleteRequest(0x1400034b900, {0x14001c3c8a0, 0x26})
github.com/libp2p/go-libp2p@v0.43.0/p2p/protocol/autonatv2/server.go:500 +0xd0
github.com/libp2p/go-libp2p/p2p/protocol/autonatv2.(*server).serveDialRequest(0x14000a2b0e0, {0x104739370, 0x14001a1a280})
github.com/libp2p/go-libp2p@v0.43.0/p2p/protocol/autonatv2/server.go:2 …
```

fix: assignment to entry in nil map

---

p2p/host/basic/addrs_manager.go
p2p/host/basic/addrs_manager_test.go
p2p/host/basic/basic_host.go
p2p/host/basic/basic_host_test.go

We'll deprecate this event, but we still have to keep sending this for a few more releases. More importantly, we need to update the peerstore with the host's addresses and it's better to do this *before* sending update events so that consumers of the event can rely on the host addrs being updated in the peerstore.

basichost: move EvtLocalAddrsChanged to addrs_manager
